In [4]:
import requests
from bs4 import BeautifulSoup
import duckdb
import os

from pathlib import Path

# ensuring that os.chdir is idempotent and that we are in the project root directory,
# not inside the notebooks directory
if 'notebooks' not in os.listdir(Path.cwd()):
    print("Still inside notebooks directory, changing to project root directory.")
    os.chdir(Path.cwd().parent)
    print("Current working directory after change: ", Path.cwd())
else:
    print(f"Already in parent directory (current working directory: {Path.cwd()})")

# load config
from src.io.load_config import load_config
sw_config = load_config()['space_weather']


# load T2 dataset dir
T2_dir = sw_config['transform']['k_index']['T2_output_dir']

Already in parent directory (current working directory: d:\space-weather-project-scrub)

# Self exploration to scrape site location metadata in a structured way

In [2]:
def get_soup_content(url):

    try:
        # Send a GET request to the URL
        response = requests.get(url)

        # Check if the request was successful (status code 200)
        if response.status_code == 200:
            # Access the HTML content using the .text attribute
            html_content = response.text
            #print(html_content)
            soup = BeautifulSoup(html_content, 'html.parser')
            return soup
        else:
            print(f"Failed to retrieve the page. Status code: {response.status_code}")

    except requests.exceptions.RequestException as e:
        # Handle any potential errors during the request (e.g., connection issues)
        print(f"An error occurred: {e}")

In [50]:
url = 'https://sws.bom.gov.au/World_Data_Centre/2/1/7' 

soup = get_soup_content(url)

# Example: get the title of the page
page_title = soup.title.string
print(f"Page Title: {page_title}")

# Example: find all links
# for link in soup.find_all('a'):
#     link_url = link.get('href')
#     print(f'Link URL: {link_url},\n title: {link.get("title")}\n')

# Example: find all tables
tables = soup.find_all('table')
print(tables)

for table in tables:
    # Process each table (e.g., extract rows and cells)
    for row in table.find_all('tr'):
        cells = [cell.text.strip() for cell in row.find_all(['td', 'th'])]
        # Do something with the cell data (e.g., store in a list or print)
        print(cells)

Page Title: SWS - Data Catalogue - Alice Springs
[<table>
<tr class="hidden"><th>Item</th><th>Value</th></tr>
<tr><td>Station Name</td><td>Alice Springs</td> </tr>
<tr><td>Alternative Name</td><td>None</td> </tr>
</table>, <table>
<tr class="hidden"><th>Item</th><th>Value</th></tr>
<tr><td>Geographic</td><td>Lat. -23.81 Long. 133.90E</td> </tr>
<tr><td>Geomagnetic</td><td>Lat. -34.44 Long. 206.95</td> </tr>
<tr><td>Dip</td><td>-34.3</td> </tr>
<tr><td>Split (0.5*gyro frequency) </td><td>0.6</td> </tr>
<tr><td>L Shell</td><td>1.47</td> </tr>
<tr><td>Time Noon</td><td>03 UT</td> </tr>
</table>, <table>
<tr class="hidden"><th>Item</th><th>Value</th></tr>
<tr><td>Years of Data</td><td> 6 months</td> </tr>
<tr><td>Opened</td><td>May 1985</td> </tr>
<tr><td>Closed</td><td>November 1985</td> </tr>
<tr><td>Status</td><td>Closed</td> </tr>
</table>, <table>
<tr class="hidden"><th>Item</th><th>Value</th></tr>
<tr><td>IPS Code</td><td>3357</td> </tr>
<tr><td>URSI Code</td><td>AE42L</td> </tr>
<tr><td>ESSA Code</td><td>42L</td> </tr>
</table>, <table>
<tr class="hidden"><th>Item</th><th>Value</th></tr>
<tr><td>Ionogram</td><td>May 1985-November 1985, 16mm film</td> </tr>
</table>]
['Item', 'Value']
['Station Name', 'Alice Springs']
['Alternative Name', 'None']
['Item', 'Value']
['Geographic', 'Lat. -23.81 Long. 133.90E']
['Geomagnetic', 'Lat. -34.44 Long. 206.95']
['Dip', '-34.3']
['Split (0.5*gyro frequency)', '0.6']
['L Shell', '1.47']
['Time Noon', '03 UT']
['Item', 'Value']
['Years of Data', '6 months']
['Opened', 'May 1985']
['Closed', 'November 1985']
['Status', 'Closed']
['Item', 'Value']
['IPS Code', '3357']
['URSI Code', 'AE42L']
['ESSA Code', '42L']
['Item', 'Value']
['Ionogram', 'May 1985-November 1985, 16mm film']

```
<table>
<tr class="hidden"><th>Item</th><th>Value</th></tr>
<tr><td>Geographic</td><td>Lat. -12.45 Long. 130.95E</td></tr>
<tr><td>Geomagnetic</td><td>Lat. -21.96 Long. 202.84</td></tr>
<tr><td>Dip</td><td>-44.5</td></tr>
<tr><td>Split (0.5*gyro frequency) </td><td>0.6 MHz</td></tr>
<tr><td>L Shell</td><td>1.16</td></tr>
<tr><td>Time Noon</td><td>03 UT</td></tr>
</table>
```
Would correspond to the following table:



| Item | Value |
| :--- | :--- |
| **Geographic** | Lat. -12.45 Long. 130.95E |
| **Geomagnetic** | Lat. -21.96 Long. 202.84 |
| **Dip** | -44.5 |
| **Split (0.5 * gyro frequency)** | 0.6 MHz |
| **L Shell** | 1.16 |
| **Time Noon** | 03 UT |

**Each row is enclosed in `<tr></tr>` tags, and each cell is enclosed in `<td></td>` or `<th></th>` tags.**
- tr = table row
- td = table data
- th = table header

In [31]:
# the URL for the map page containing hyperlinks for each station's metadata
url = 'https://sws.bom.gov.au/World_Data_Centre/2/1/1'
get_soup_content(url).find_all('area')

[<area alt="Mawson" coords="0,465,40,535" href="/World_Data_Centre/2/1/23" shape="rect"/>,
 <area alt="Davis" coords="50,468,80,533" href="/World_Data_Centre/2/1/22" shape="rect"/>,
 <area alt="Casey" coords="90,467,125,535" href="/World_Data_Centre/2/1/24" shape="rect"/>,
 <area alt="Macquarie Island" coords="391,463,465,532" href="/World_Data_Centre/2/1/26" shape="rect"/>,
 <area alt="Scott Base" coords="583,467,642,531" href="/World_Data_Centre/2/1/25" shape="rect"/>,
 <area alt="Learmonth" coords="65,226,139,248" href="/World_Data_Centre/2/1/21" shape="rect"/>,
 <area alt="Culgoora" coords="342,311,396,330" href="/World_Data_Centre/2/1/27" shape="rect"/>,
 <area alt="Cocos Islands" coords="0,98,70,120" href="/World_Data_Centre/2/1/20" shape="rect"/>,
 <area alt="Niue" coords="666,170,707,194" href="/World_Data_Centre/2/1/18" shape="rect"/>,
 <area alt="Norfolk Island" coords="506,293,580,314" href="/World_Data_Centre/2/1/19" shape="rect"/>,
 <area alt="Vanimo" coords="309,12,371,37" href="/World_Data_Centre/2/1/2" shape="rect"/>,
 <area alt="Darwin" coords="206,122,265,150" href="/World_Data_Centre/2/1/3" shape="rect"/>,
 <area alt="Port Moresby" coords="357,81,418,107" href="/World_Data_Centre/2/1/4" shape="rect"/>,
 <area alt="Townsville" coords="377,188,429,212" href="/World_Data_Centre/2/1/5" shape="rect"/>,
 <area alt="Tennant Creek" coords="238,185,297,203" href="/World_Data_Centre/2/1/6" shape="rect"/>,
 <area alt="Alice Springs" coords="226,226,278,245" href="/World_Data_Centre/2/1/7" shape="rect"/>,
 <area alt="Watheroo" coords="86,298,126,312" href="/World_Data_Centre/2/1/8" shape="rect"/>,
 <area alt="Mundaring" coords="92,324,134,335" href="/World_Data_Centre/2/1/9" shape="rect"/>,
 <area alt="Brisbane" coords="415,273,456,296" href="/World_Data_Centre/2/1/10" shape="rect"/>,
 <area alt="Woomera" coords="255,310,294,323" href="/World_Data_Centre/2/1/11" shape="rect"/>,
 <area alt="Salisbury" coords="274,330,314,345" href="/World_Data_Centre/2/1/12" shape="rect"/>,
 <area alt="Camden" coords="386,339,459,359" href="/World_Data_Centre/2/1/13" shape="rect"/>,
 <area alt="Canberra" coords="352,359,391,375" href="/World_Data_Centre/2/1/14" shape="rect"/>,
 <area alt="Hobart" coords="339,426,387,447" href="/World_Data_Centre/2/1/15" shape="rect"/>,
 <area alt="Auckland" coords="583,360,626,381" href="/World_Data_Centre/2/1/16" shape="rect"/>,
 <area alt="Christchurch" coords="567,432,626,451" href="/World_Data_Centre/2/1/17" shape="rect"/>,
 <area alt="Weipa" coords="309,110,350,150" href="/World_Data_Centre/2/1/29" shape="rect"/>,
 <area alt="Perth" coords="60,340,110,360" href="/World_Data_Centre/2/1/30" shape="rect"/>,
 <area alt="Willis Island" coords="400,138,470,160" href="/World_Data_Centre/2/1/31" shape="rect"/>,
 <area alt="Lord Howe Island" coords="420,305,500,325" href="/World_Data_Centre/2/1/32" shape="rect"/>,
 <area alt="Launceston" coords="265,410,340,425" href="/World_Data_Centre/2/1/33" shape="rect"/>]

In [35]:
# raw HTML string parsed by BeautifulSoup
get_soup_content(url)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en-AU">
<head>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7N5HE7LPBD"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7N5HE7LPBD');
</script>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width,initial-scale=1.0" name="viewport"/>
<meta content="http://www.sws.bom.gov.au/" name="DC.Identifier" scheme="URI"/>
<meta content="c=AU; co=Commonwealth of Australia; ou=Department of Sustainability, Environment, Water, Population and Communities; ou=Central Office; ou=Bureau of Meteorology; ou=Space Weather Services" name="DC.Creator" scheme="GOLD"/>
<meta content="c=AU; co=Commonwealth of Australia; ou=Department of Sustainability, Environment, Water, Population and Communities; ou=Central Office; ou=Bureau of Meteorology; ou=Space Weather Services" name="DC.Publisher" scheme="GOLD"/>
<meta content="Copyright Commonwealth of Australia 2026" name="DC.Rights"/>
<meta content="Space Weather Services website" name="DC.Title"/>
<meta content="Outer space; Space sciences; Space environment; Satellites; Ionosphere; Radio wave propagation; Astronomical observatories; Scientific satellites; Shortwave radio; Auroras; Sunspots; Weather forecasting; Meteors; ;Transit of Venus; Magnetic Storms." name="DC.Subject" scheme="LCSH"/>
<meta content="Atmospheric Sciences; Satellite Communication, Spatial information research" name="AGLS.Function" scheme="AGIFT"/>
<meta content="ASWFCMap" name="DC.Description"/>
<meta content="en" name="DC.Language" scheme="RF3066"/>
<meta content="2012-07-19" name="DC.Date.Modified" scheme="ISO8601"/>
<meta content="collection" name="DC.Type.aggregationLevel"/>
<meta content="homepage" name="DC.Type.documentType"/>
<meta content="text/html" name="DC.Format" scheme="IMT"/>
<meta content="$filename" name="NoF"/>
<link ?version="2.2" href="/Styles/main.css" rel="stylesheet" type="text/css"/>
<link ?version="2.2" href="/Styles/ak_styles.css" rel="stylesheet" type="text/css"/>
<link ?version="2.2" href="/Styles/blink.css" rel="stylesheet" type="text/css"/>
<link ?version="2.2" href="/Styles/space-weather-conditions.css" rel="stylesheet" type="text/css"/>
<link ?version="2.2" href="/Styles/front_page_style.css" rel="stylesheet" type="text/css"/>
<meta content="Category/World Data Centre/Data Catalogue/ASWFC Stations/ASWFC Stations.php" name="filepath"/>
<title>SWS - Data Catalogue - ASWFCMap</title>
<script type="text/javascript">
  <!-- Begin
  function formHandler(form){
    var URL = form.site.options[form.site.selectedIndex].value;
    window.location.href = URL;
  }
  // End -->
  </script>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-33347372-1']);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="/scripts/jqplot/excanvas.min.js"></script><![endif]-->
<script language="javascript" src="/scripts/jquery/jquery-latest.min.js" type="text/javascript"></script>
<script language="javascript" src="/Styles/js/infinite-rotator.js?ver=1.1" type="text/javascript"></script>
<!-- add bootstrap core css-->
<!-- Add a Calendar Date Picker to the Aurora Report, Virgin and JetStar Route Tool date Form with jQuery source code from https://ajax.googleapis.com/ajax/libs-->
<script>!function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if("False"=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="47ZBW-6M9U8-RYDFR-8THM8-8HHHC",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,_,o,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",o=document.getElementsByTagName("script")[0],o.parentNode.insertBefore(r,o);try{_=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain='"+i+"';void(0);",_=r.contentWindow.document}_.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"47ZBW-6M9U8-RYDFR-8THM8-8HHHC",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},_.write("<bo"+'dy onload="document._l();">'),_.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e=""=="true"?1:0,t="",n="v4svh2vyktxce2pwzycq-f-1b96c6dbe-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,_={"ak.v":"41","ak.cp":"1078746","ak.ai":parseInt("639836",10),"ak.ol":"0","ak.cr":8,"ak.ipv":4,"ak.proto":"http/1.1","ak.rid":"477f9ea","ak.r":23099,"ak.a2":e,"ak.m":"a","ak.n":"essl","ak.cport":60406,"ak.gh":"184.84.238.6","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.0rtt.ed":"","ak.csrc":"-","ak.acc":"bbr","ak.t":"1777782277","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==k75G3v2GpeU0bgWaXVRXobQY83sw0K9CStSv9tMX0yr4sdhzMYMmsS9CEL81gFY8h1MEQBydT0kGFOKUFyxab8KblfZb8J8kUNFvkhDZxeieecCsCoGKBAQrvrGaktRSAHWHrSL7qSYaSsHhh2yBhLjvJXchtXWoFKhtdtAyhnNkoS6ISizYZNt4HkFfzwDGUldVIH5GPUx1Xlk7IrXBJN8dbIPhm1zw+1ywByvX7s5GqKzBLsX63id440tgV011xQFTBhVJwhZPFG7j+2fzy3bH51oCHwuCWztFRNs/bAjfsOng4dgr2NHSm29PiM+EDCdLHAb7rTHrX//6ESeu+v0RGwzvAn0cFOQjLI6yOMr3oLhE9JlKk/ul3Mu3daQeBfEH8zXWv0bZorFfraMgcnd9Uapqyg3XZ4DD6uhxUV4=","ak.pv":"23","ak.dpoabenc":"","ak.tf":i};if(""!==t)_["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))_["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(_)},rv:function(){var a=["ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.0rtt.ed","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:_,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>
<body><div id="page-shadow">
<div class="left-bkg" id="page-indent">
<div class="bodytext">
<!-- header -->
<a class="anchor" id="top"></a>
<a class="hidden" href="#category-menu">skip page header</a><link href="/Styles/rot.css" media="screen" rel="stylesheet" type="text/css">
<div class="row" id="bannerbox">
<a class="banner" href="http://www.bom.gov.au"><img alt="Australian Government - Bureau of Meteorology" height="67px" src="/Images/Banner/NewLogo349x67.png" title="Australian Government - Bureau of Meteorology" width="349px"/>
</a>
<a class="banner" href="/"><img alt="Australian Government - Bureau of Meteorology, Australian Space Weather Forecasting Centre" height="67px" src="/Images/Banner/IPSlogo418x67.png" title="Australian Government - Bureau of Meteorology, Australian Space Weather Forecasting Centre" width="418px"/>
</a>
<div class="banner">
<div id="rotating-item-wrapper">
<div> <img alt="Australian Government - Bureau of Meteorology, Australian Space Weather Forecasting Centre" src="/Images/Banner/Banner_right.png"/> </div> </div>
</div>
</div>
<!-- The Category menu and title, mini-forecast and search section -->
<!-- site menu -->
<div class="site-menu"><ul title="header menu"><li class="menu"><a accesskey="1" href="/" title="The Bureau of Meteorology Space Weather Home Page">Home</a></li><li class="menu"><a href="/Space_Weather" title="A summary of current Space Weather conditions">Space Weather</a></li><li class="menu"><a href="/Aurora" title="Aurora - Aurora viewing conditions, forecast and sightings">Aurora</a></li><li class="menu"><a href="/Satellite" title="Satellite - Ionospheric scintillation, GPS, TEC">Satellite</a></li><li class="menu"><a href="/Geophysical" title="Geophysical - Magnetograms, Cosmic rays">Geophysical</a></li><li class="menu"><a href="/Solar" title="Solar - Solar observations; visual and radio">Solar</a></li><li class="menu"><a href="/HF_Systems" title="HF Systems - Radio communications charts, the ionosphere">HF Systems</a></li><li class="menu"><a href="/Products_and_Services" title="Products and Services - software, training, client support, subscription services">Products and Services</a></li><li class="menu"><a href="/Educational" title="Educational - material about Space Weather">Educational</a></li><li class="menu"><a href="/World_Data_Centre" title="World Data Centre">World Data Centre</a></li><li class="menu last"><a href="/Research" title="Research - Research area and interests in ASWFC">Research</a></li></ul></div>
<!-- page category -->
<div id="head-category">World Data Centre</div>
<!-- mini-forecast and search links -->
<div id="head-extras">
<span id="forecast">FORECAST SOL: Moderate <a href="/Solar"><img align="TOP" alt="yellow" border="0" src="/Images/yellow.gif"/></a>    MAG: Normal <a href="/Geophysical"><img align="TOP" alt="green" border="0" src="/Images/green.gif"/></a>     ION: Normal <a href="/HF_Systems"><img align="TOP" alt="green" border="0" src="/Images/green.gif"/></a>
</span>
<span id="search">
<form action="https://www.bom.gov.au/search" class="searchform" enctype="application/x-www-form-urlencoded" method="get" target="_blank">
<label for="query">Search</label><input id="query" name="query" placeholder="Enter search terms" size="25" type="text" value=""/>
<input class="search" title="Search" type="submit" value="Search"/>
</form>
</span>
</div>
<!-- page navigation -->
<!-- breadcrumbs and current time -->
<div id="head-status">
<span id="bread-crumbs"><a href="/">Home</a><a class="separator" href="/World_Data_Centre">World Data Centre</a><span class="separator">Data Catalogue</span><a class="separator" href="/World_Data_Centre/2/1">ASWFC Stations</a><a class="separator" href="/World_Data_Centre/2/1/1">ASWFCMap</a></span>
<span id="current-time">
    Sunday, May 03 2026 04:24 UT  </span>
</div>
<!-- left-hand menu and page content -->
<a class="anchor" id="category-menu"></a><a accesskey="S" class="hidden" href="#content">skip category menu</a><div id="left-menu" title="Section navigation">
<h1>Data Display and Download</h1>
<ul>
<li><a href="/World_Data_Centre/1/1" title="Access to ASWFC data server to download ionospheric, geophysical, solar and GPS data files and ionospheric and solar viewers software tools.
">Data Download</a></li>
<li><a href="/World_Data_Centre/1/2" title="Access the web page to display magnetometer data plot and download data files.
">Magnetometer</a></li>
<li><a href="/World_Data_Centre/1/3" title="To plot scaled hourly ionospheric data and download data files.
">Ionospheric</a></li>
<li><a href="/World_Data_Centre/1/4" title="To plot monthly ionospheric medians of foF2 and M(3000)F2 data and download data files.
">Ionospheric_Medians</a></li>
<li><a href="/World_Data_Centre/1/6" title="To display The Southern Hemisphere Imaging Riometer Experiment (SHIRE) data images.
">Imaging Riometer</a></li>
<li><a href="/World_Data_Centre/1/7" title="To plot and download cosmic ray data of Kingston and Mawsom stations.
">Cosmic Ray</a></li>
<li><a href="/World_Data_Centre/1/8" title="To plot and download riometer data of Casey, Davis, Macquarie Island and Mawson stations.
">Riometer</a></li>
<li><a href="/World_Data_Centre/1/9" title="To display spectrograph images and download data files of Learmonth and Culgoora.
">Spectrograph</a></li>
<li><a href="/World_Data_Centre/1/10" title="To plot and download Learmonth solar radio data.
">Solar Radio</a></li>
<li><a href="/World_Data_Centre/1/11" title="To plot and download Ionospheric Scintillation Monitor(ISM) data of Darwin, Macquarie Island, Niue, Vanimo, Weipa and Wills Island.
">Ionospheric Scintillation</a></li>
<li><a href="/World_Data_Centre/1/12" title="To plot and download auto scaled Ionospheric data of ASWFC stations after 2014.
">Ionospheric_Autoscaled</a></li>
<li><a href="/World_Data_Centre/1/13" title="To plot and download auto scaled monthly median ionospheric data of ASWFC stations after 2014.
">Iono_Medians_Autoscaled</a></li>
</ul>
<h1 class="current">Data Catalogue</h1>
<ul>
<li><a href="/World_Data_Centre/2/8" title="To provide data format and data file name convention information of ASWFC data and other data sets. Some linked pages may contain extra information related to specific data sets.
">Data Formats</a></li>
<li><a href="/World_Data_Centre/2/1" title="To provide ASWFC ionosonde network and ASWFC stations map.
">ASWFC Stations</a></li>
<li><a href="/World_Data_Centre/2/2" title="To provide Australian ionosonde stations detailed information.
">Ionosonde Data</a></li>
<li><a href="/World_Data_Centre/2/3" title="To provide Australian magnetometer stations details and their log files.
">Magnetometer Data</a></li>
<li><a href="/World_Data_Centre/2/4" title="To provide information of four riometer stations at Australian Antarctic area.
">Riometer Data</a></li>
<li><a href="/World_Data_Centre/2/5" title="To provide historical spectrograph data information of Learmonth and Culgoora stations.
">Spectrograph Data</a></li>
<li><a href="/World_Data_Centre/2/6" title="To provide information of GPS stations at Darwin, Macquarie Island, Niue, Vanimo, Weipa, Lord Howe Island, Learmonth and Wills Island.
">GPS Data</a></li>
<li><a href="/World_Data_Centre/2/7" title="To provide solar data information of Learmonth and Culgoora stations.
">Solar Data</a></li>
</ul>
<h1>Metadata</h1>
<ul>
<li><a href="/World_Data_Centre/3/1" title="Space Weather Services metadata.
">ASWFC</a></li>
</ul>
<h1>Third Party Data</h1>
<ul>
<li><a href="/World_Data_Centre/4/1" title="GA scanned Mundaring iono and magnetograms data.
">Geoscience Data</a></li>
</ul>
<h1>Related Sites</h1>
<ul>
<li><a href="/World_Data_Centre/5/1" title="Links to other space weather related organizations web sites.
">WDC Links</a></li>
</ul>
<h1>Section Information</h1>
<ul>
<li><a href="/World_Data_Centre/6/1" title="News about the ASWFC WDC Section.
">Latest News</a></li>
<li><a href="/World_Data_Centre/6/2" title="A simple guide to the World Data Centre Section.
">WDC Help Page</a></li>
</ul></div>
<div id="page-content">
<!-- page content -->
<a class="anchor" id="content"></a>
<div id="section-hdr"><div id="section-name">Data Catalogue</div></div>
<div class="content">
<h1>ASWFC Stations Map</h1>
<p>For information about an ASWFC station, follow one of the links below, or click on the map.</p>
<div class="full indent">
<div class="oneOf4">
<ul class="none">
<li><a href="/World_Data_Centre/2/1/7">Alice Springs</a></li>
<li><a href="/World_Data_Centre/2/1/16">Auckland</a></li>
<li><a href="/World_Data_Centre/2/1/10">Brisbane</a></li>
<li><a href="/World_Data_Centre/2/1/13">Camden</a></li>
<li><a href="/World_Data_Centre/2/1/14">Canberra</a></li>
<li><a href="/World_Data_Centre/2/1/24">Casey</a></li>
<li><a href="/World_Data_Centre/2/1/17">Christchurch</a></li>
<li><a href="/World_Data_Centre/2/1/20">Cocos Islands</a></li>
</ul>
</div>
<div class="oneOf4">
<ul class="none">
<li><a href="/World_Data_Centre/2/1/27">Culgoora</a></li>
<li><a href="/World_Data_Centre/2/1/3">Darwin</a></li>
<li><a href="/World_Data_Centre/2/1/22">Davis</a></li>
<li><a href="/World_Data_Centre/2/1/15">Hobart</a></li>
<li><a href="/World_Data_Centre/2/1/33">Launceston</a></li>
<li><a href="/World_Data_Centre/2/1/21">Learmonth</a></li>
<li><a href="/World_Data_Centre/2/1/32">Lord Howe Island</a></li>
<li><a href="/World_Data_Centre/2/1/26">Macquarie Island</a></li>
</ul>
</div>
<div class="oneOf4">
<ul class="none">
<li><a href="/World_Data_Centre/2/1/23">Mawson</a></li>
<li><a href="/World_Data_Centre/2/1/9">Mundaring</a></li>
<li><a href="/World_Data_Centre/2/1/18">Niue</a></li>
<li><a href="/World_Data_Centre/2/1/19">Norfolk Island</a></li>
<li><a href="/World_Data_Centre/2/1/30">Perth</a></li>
<li><a href="/World_Data_Centre/2/1/4">Port Moresby</a></li>
<li><a href="/World_Data_Centre/2/1/12">Salisbury</a></li>
<li><a href="/World_Data_Centre/2/1/25">Scott Base</a></li>
</ul>
</div>
<div class="oneOf4">
<ul class="none">
<li><a href="/World_Data_Centre/2/1/6">Tennant Creek</a></li>
<li><a href="/World_Data_Centre/2/1/5">Townsville</a></li>
<li><a href="/World_Data_Centre/2/1/2">Vanimo</a></li>
<li><a href="/World_Data_Centre/2/1/8">Watheroo</a></li>
<li><a href="/World_Data_Centre/2/1/29">Weipa</a></li>
<li><a href="/World_Data_Centre/2/1/31">Willis Island</a></li>
<li><a href="/World_Data_Centre/2/1/11">Woomera</a></li>
</ul>
</div>
</div>
<div class="full more-space">
<img border="0" height="536" src="/Images/World%20Data%20Centre/Data%20Catalogue/SWS%20Stations/SWSmap.jpg" usemap="#map" width="709">
<map name="map">
<area alt="Mawson" coords="0,465,40,535" href="/World_Data_Centre/2/1/23" shape="rect"/>
<area alt="Davis" coords="50,468,80,533" href="/World_Data_Centre/2/1/22" shape="rect"/>
<area alt="Casey" coords="90,467,125,535" href="/World_Data_Centre/2/1/24" shape="rect"/>
<area alt="Macquarie Island" coords="391,463,465,532" href="/World_Data_Centre/2/1/26" shape="rect"/>
<area alt="Scott Base" coords="583,467,642,531" href="/World_Data_Centre/2/1/25" shape="rect"/>
<area alt="Learmonth" coords="65,226,139,248" href="/World_Data_Centre/2/1/21" shape="rect"/>
<area alt="Culgoora" coords="342,311,396,330" href="/World_Data_Centre/2/1/27" shape="rect"/>
<area alt="Cocos Islands" coords="0,98,70,120" href="/World_Data_Centre/2/1/20" shape="rect"/>
<area alt="Niue" coords="666,170,707,194" href="/World_Data_Centre/2/1/18" shape="rect"/>
<area alt="Norfolk Island" coords="506,293,580,314" href="/World_Data_Centre/2/1/19" shape="rect"/>
<area alt="Vanimo" coords="309,12,371,37" href="/World_Data_Centre/2/1/2" shape="rect"/>
<area alt="Darwin" coords="206,122,265,150" href="/World_Data_Centre/2/1/3" shape="rect"/>
<area alt="Port Moresby" coords="357,81,418,107" href="/World_Data_Centre/2/1/4" shape="rect"/>
<area alt="Townsville" coords="377,188,429,212" href="/World_Data_Centre/2/1/5" shape="rect"/>
<area alt="Tennant Creek" coords="238,185,297,203" href="/World_Data_Centre/2/1/6" shape="rect"/>
<area alt="Alice Springs" coords="226,226,278,245" href="/World_Data_Centre/2/1/7" shape="rect"/>
<area alt="Watheroo" coords="86,298,126,312" href="/World_Data_Centre/2/1/8" shape="rect"/>
<area alt="Mundaring" coords="92,324,134,335" href="/World_Data_Centre/2/1/9" shape="rect"/>
<area alt="Brisbane" coords="415,273,456,296" href="/World_Data_Centre/2/1/10" shape="rect"/>
<area alt="Woomera" coords="255,310,294,323" href="/World_Data_Centre/2/1/11" shape="rect"/>
<area alt="Salisbury" coords="274,330,314,345" href="/World_Data_Centre/2/1/12" shape="rect"/>
<area alt="Camden" coords="386,339,459,359" href="/World_Data_Centre/2/1/13" shape="rect"/>
<area alt="Canberra" coords="352,359,391,375" href="/World_Data_Centre/2/1/14" shape="rect"/>
<area alt="Hobart" coords="339,426,387,447" href="/World_Data_Centre/2/1/15" shape="rect"/>
<area alt="Auckland" coords="583,360,626,381" href="/World_Data_Centre/2/1/16" shape="rect"/>
<area alt="Christchurch" coords="567,432,626,451" href="/World_Data_Centre/2/1/17" shape="rect"/>

In [23]:
# simply parsing the stations and their respective relative hyperlinks 
station_href_elements = {e.get('alt'):e.get('href') for e in get_soup_content(url).find_all('area')}
station_href_elements

{'Mawson': '/World_Data_Centre/2/1/23',
 'Davis': '/World_Data_Centre/2/1/22',
 'Casey': '/World_Data_Centre/2/1/24',
 'Macquarie Island': '/World_Data_Centre/2/1/26',
 'Scott Base': '/World_Data_Centre/2/1/25',
 'Learmonth': '/World_Data_Centre/2/1/21',
 'Culgoora': '/World_Data_Centre/2/1/27',
 'Cocos Islands': '/World_Data_Centre/2/1/20',
 'Niue': '/World_Data_Centre/2/1/18',
 'Norfolk Island': '/World_Data_Centre/2/1/19',
 'Vanimo': '/World_Data_Centre/2/1/2',
 'Darwin': '/World_Data_Centre/2/1/3',
 'Port Moresby': '/World_Data_Centre/2/1/4',
 'Townsville': '/World_Data_Centre/2/1/5',
 'Tennant Creek': '/World_Data_Centre/2/1/6',
 'Alice Springs': '/World_Data_Centre/2/1/7',
 'Watheroo': '/World_Data_Centre/2/1/8',
 'Mundaring': '/World_Data_Centre/2/1/9',
 'Brisbane': '/World_Data_Centre/2/1/10',
 'Woomera': '/World_Data_Centre/2/1/11',
 'Salisbury': '/World_Data_Centre/2/1/12',
 'Camden': '/World_Data_Centre/2/1/13',
 'Canberra': '/World_Data_Centre/2/1/14',
 'Hobart': '/World_Data_Centre/2/1/15',
 'Auckland': '/World_Data_Centre/2/1/16',
 'Christchurch': '/World_Data_Centre/2/1/17',
 'Weipa': '/World_Data_Centre/2/1/29',
 'Perth': '/World_Data_Centre/2/1/30',
 'Willis Island': '/World_Data_Centre/2/1/31',
 'Lord Howe Island': '/World_Data_Centre/2/1/32',
 'Launceston': '/World_Data_Centre/2/1/33'}

In [24]:
def get_station_metadata(base_url, href):
    
    url_station = base_url + href
    soup = get_soup_content(url_station)

    tables = soup.find_all('table')
    print(f'len(tables): {len(tables)}')

    for table in tables:
        # Process each table (e.g., extract rows and cells)
        for row in table.find_all('tr'): # tr = table row
            # td = table data, th = table header
            cells = [cell.text.strip() for cell in row.find_all(['td', 'th'])]
            # Do something with the cell data (e.g., store in a list or print)
            print(cells)
        print()


# in the space weather API get-k-index endpoint, "Narrabri" is used instead of "Culgoora"
base_url = 'https://sws.bom.gov.au'
get_station_metadata(base_url, station_href_elements['Auckland'])

# create json dict of `{station_name: {alternative_name:.., lat_raw:.., long_raw:.., geometry:.., source_url:base_url+href, retrieved_at_utc:..}}`
# so that when joining station location to T2, for each row in T2, check if its location exists in the metadata (station_name and alternative_name), but 
# for alternative_name I think we should not use exact matching, just check whether the location is in the Alternative Name entry or not, as per the following output
# if it exsits then parse the coordinates e.g. ['Geographic', 'Lat. -30.28 Long. 149.58E'] into geometry_raw e.g. 'Lat. -30.28 Long. 149.58E', lat, long, geometry.

# but to determine the format of the geo coordinates, we probably shoould gather them from all locations (e.g. long has 'E' indicator but not the latitude)

len(tables): 5
['Item', 'Value']
['Station Name', 'Auckland']
['Alternative Name', 'None']

['Item', 'Value']
['Geographic', 'Lat. -37.00 Long. 175.00E']
['Geomagnetic', 'Lat. -42.88 Long. 256.11']
['Dip', '-62.90']
['Split (0.5*gyro frequency)', '0.8']
['L Shell', '1.86']
['Time Noon', '00 UT']

['Item', 'Value']
['Years of Data', '31 years']
['Opened', 'December 1967']
['Closed', 'March 1998']
['Status', 'Closed']

['Item', 'Value']
['IPS Code', '4464']
['URSI Code', 'AU63P']
['WDC Code', '9063P']
['ESSA Code', '63P']

['Item', 'Value']
['Ionogram', 'December 1967-August 1998, Digital']

In [ ]:
def get_station_coord(base_url, href):
    
    url_station = base_url + href
    soup = get_soup_content(url_station)

    tables = soup.find_all('table')

    for table in tables:
        # Process each table (e.g., extract rows and cells)
        for row in table.find_all('tr'): # tr = table row
            # td = table data, th = table header
            cells = [cell.text.strip() for cell in row.find_all(['td', 'th'])]
            # Do something with the cell data (e.g., store in a list or print)
            if cells[0] == 'Geographic':
                return cells[1]
            #print(cells)
        #print()


station_coords = {e.get('alt'):get_station_coord(base_url, e.get('href')) for e in get_soup_content(url).find_all('area')}

In [15]:
station_coords

{'Mawson': 'Lat. -67.60 Long. 62.88E',
 'Davis': 'Lat. -68.58 Long. 77.96E',
 'Casey': 'Lat. -66.30 Long. 110.50E',
 'Macquarie Island': 'Lat. -54.50 Long. 158.95E',
 'Scott Base': 'Lat. -77.80 Long. 166.80E',
 'Learmonth': 'Lat. -22.25 Long. 114.08E',
 'Culgoora': 'Lat. -30.28 Long. 149.58E',
 'Cocos Islands': 'Lat. -12.20 Long. 96.80E',
 'Niue': 'Lat. -19.07 Long. 190.07E',
 'Norfolk Island': 'Lat. -29.03 Long. 167.97E',
 'Vanimo': 'Lat. -2.70 Long. 141.30E',
 'Darwin': 'Lat. -12.45 Long. 130.95E',
 'Port Moresby': 'Lat. -9.40 Long. 147.10E',
 'Townsville': 'Lat. -19.63 Long. 146.85E',
 'Tennant Creek': 'Lat. -19.65 Long. 134.25E',
 'Alice Springs': 'Lat. -23.81 Long. 133.90E',
 'Watheroo': 'Lat. -30.30 Long. 115.90E',
 'Mundaring': 'Lat. -31.98 Long. 116.22E',
 'Brisbane': 'Lat. -27.53 Long. 152.92E',
 'Woomera': 'Lat. -30.80 Long. 136.30E',
 'Salisbury': 'Lat. -34.70 Long. 138.60E',
 'Camden': 'Lat. -34.05 Long. 150.67',
 'Canberra': 'Lat. -35.32 Long. 149.00E',
 'Hobart': 'Lat. -42.92 Long. 147.32E',
 'Auckland': 'Lat. -37.00 Long. 175.00E',
 'Christchurch': 'Lat. -43.60 Long. 172.80E',
 'Weipa': 'Lat. -12.63 Long. 141.88E',
 'Perth': 'Lat. -31.94 Long. 115.95E',
 'Willis Island': 'Lat. -16.29 Long. 149.97E',
 'Lord Howe Island': 'Lat. -31.54 Long. 159.08E',
 'Launceston': 'Lat. -41.55 Long. 147.21E'}

# Developed code to parse station locations into a table

In [2]:
import re
from datetime import datetime, timezone
from urllib.parse import urljoin

import pandas as pd
import requests
from bs4 import BeautifulSoup


def get_soup_content(url: str, timeout: int = 30) -> BeautifulSoup:
    response = requests.get(url, timeout=timeout)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def extract_key_value_rows(soup: BeautifulSoup) -> dict[str, str]:
    """
    Extract all 2-column table rows into a flat dict.
    Example row:
        ['Geographic', 'Lat. -30.28 Long. 149.58E']
    """
    values = {}

    for table in soup.find_all("table"):
        for row in table.find_all("tr"):
            cells = [cell.get_text(strip=True) for cell in row.find_all(["td", "th"])]
            if len(cells) == 2 and cells[0] != "Item":
                values[cells[0]] = cells[1]

    return values


def parse_alternative_names(alternative_name_raw: str | None) -> list[str]:
    """
    Tentative rule:
    'Narrabri (although not used with data reports)' -> ['Narrabri']

    Keep this conservative:
    - preserve the raw string separately
    - only derive a leading alias before any parenthetical note
    """
    if not alternative_name_raw:
        return []

    candidate = re.sub(r"\s*\(.*?\)\s*", "", alternative_name_raw).strip()

    if not candidate:
        return []

    return [candidate]


def parse_geographic(geometry_raw: str | None) -> tuple[float | None, float | None, str | None]:
    """
    Parse strings like:
        'Lat. -30.28 Long. 149.58E'
        'Lat. -12.45 Long. 130.95E'

    Returns:
        (lat, lon, geometry_wkt)
    """
    if not geometry_raw:
        return None, None, None

    match = re.search(
        r"Lat\.\s*([+-]?\d+(?:\.\d+)?)\s+Long\.\s*([+-]?\d+(?:\.\d+)?)([EW])?",
        geometry_raw
    )
    if not match:
        return None, None, None

    lat = float(match.group(1))
    lon = float(match.group(2))
    lon_dir = match.group(3)

    if lon_dir == "W":
        lon = -abs(lon)
    elif lon_dir == "E":
        lon = abs(lon)

    geometry = f"POINT ({lon} {lat})"
    return lat, lon, geometry


def extract_station_metadata(
    base_url: str = "https://sws.bom.gov.au",
    map_page_url: str = "https://sws.bom.gov.au/World_Data_Centre/2/1/1",
) -> pd.DataFrame:
    
    """
    Build one canonical metadata row per station from the WDC map page.
    """

    retrieved_at_utc = datetime.now(timezone.utc).isoformat()

    # scrape station `href` links from the WDC map page 
    map_soup = get_soup_content(map_page_url)

    print("Scraping all <area> elements in the World Data Center map page..")
    area_elements = map_soup.find_all("area")
    num_areas = len(area_elements)
    print(f"{num_areas} sites found.")

    rows = []

    for i, area in enumerate(area_elements):
        
        station_display_name = area.get("alt")
        href = area.get("href")

        print(f"Obtaining metadata for station {station_display_name} ({i+1}/{num_areas})")

        if not station_display_name or not href:
            print(f"Station display name does not exist or link does not exist. Continuing to the next station...")
            continue

        # visit each defail page (base_url + corresponding `href`)
        source_url = urljoin(base_url, href)
        print(f"Visiting detail page for station {station_display_name}")
        station_soup = get_soup_content(source_url)

        print("Extracting metadata..")

        kv = extract_key_value_rows(station_soup)

        # extract `Station Name`, `Alternative Name` and `Geographic`
        station_name = kv.get("Station Name", station_display_name)

        # map page explicitly states non existent alternative names as "None"
        # for our purposes we parse it instead to a NoneType 
        alternative_name_raw = kv.get("Alternative Name") if kv.get("Alternative Name") != "None" else None
        alternative_names = parse_alternative_names(alternative_name_raw) if alternative_name_raw else None

        geometry_raw = kv.get("Geographic")

        # store station metadata as a canonical row
        lat, lon, geometry = parse_geographic(geometry_raw)

        rows.append(
            {
                "station_name": station_name,
                "alternative_name_raw": alternative_name_raw,
                "alternative_names": alternative_names,
                "geometry_raw": geometry_raw,
                "lat": lat,
                "long": lon,
                "geometry_txt": geometry,
                "source_url": source_url,
                "retrieved_at_utc": retrieved_at_utc,
            }
        )

    return pd.DataFrame(rows)

In [3]:
station_metadata = extract_station_metadata()
station_metadata

Scraping all <area> elements in the World Data Center map page..
31 sites found.
Obtaining metadata for station Mawson (1/31)
Visiting detail page for station Mawson
Extracting metadata..
Obtaining metadata for station Davis (2/31)
Visiting detail page for station Davis
Extracting metadata..
Obtaining metadata for station Casey (3/31)
Visiting detail page for station Casey
Extracting metadata..
Obtaining metadata for station Macquarie Island (4/31)
Visiting detail page for station Macquarie Island
Extracting metadata..
Obtaining metadata for station Scott Base (5/31)
Visiting detail page for station Scott Base
Extracting metadata..
Obtaining metadata for station Learmonth (6/31)
Visiting detail page for station Learmonth
Extracting metadata..
Obtaining metadata for station Culgoora (7/31)
Visiting detail page for station Culgoora
Extracting metadata..
Obtaining metadata for station Cocos Islands (8/31)
Visiting detail page for station Cocos Islands
Extracting metadata..
Obtaining metadata for station Niue (9/31)
Visiting detail page for station Niue
Extracting metadata..
Obtaining metadata for station Norfolk Island (10/31)
Visiting detail page for station Norfolk Island
Extracting metadata..
Obtaining metadata for station Vanimo (11/31)
Visiting detail page for station Vanimo
Extracting metadata..
Obtaining metadata for station Darwin (12/31)
Visiting detail page for station Darwin
Extracting metadata..
Obtaining metadata for station Port Moresby (13/31)
Visiting detail page for station Port Moresby
Extracting metadata..
Obtaining metadata for station Townsville (14/31)
Visiting detail page for station Townsville
Extracting metadata..
Obtaining metadata for station Tennant Creek (15/31)
Visiting detail page for station Tennant Creek
Extracting metadata..
Obtaining metadata for station Alice Springs (16/31)
Visiting detail page for station Alice Springs
Extracting metadata..
Obtaining metadata for station Watheroo (17/31)
Visiting detail page for station Watheroo
Extracting metadata..
Obtaining metadata for station Mundaring (18/31)
Visiting detail page for station Mundaring
Extracting metadata..
Obtaining metadata for station Brisbane (19/31)
Visiting detail page for station Brisbane
Extracting metadata..
Obtaining metadata for station Woomera (20/31)
Visiting detail page for station Woomera
Extracting metadata..
Obtaining metadata for station Salisbury (21/31)
Visiting detail page for station Salisbury
Extracting metadata..
Obtaining metadata for station Camden (22/31)
Visiting detail page for station Camden
Extracting metadata..
Obtaining metadata for station Canberra (23/31)
Visiting detail page for station Canberra
Extracting metadata..
Obtaining metadata for station Hobart (24/31)
Visiting detail page for station Hobart
Extracting metadata..
Obtaining metadata for station Auckland (25/31)
Visiting detail page for station Auckland
Extracting metadata..
Obtaining metadata for station Christchurch (26/31)
Visiting detail page for station Christchurch
Extracting metadata..
Obtaining metadata for station Weipa (27/31)
Visiting detail page for station Weipa
Extracting metadata..
Obtaining metadata for station Perth (28/31)
Visiting detail page for station Perth
Extracting metadata..
Obtaining metadata for station Willis Island (29/31)
Visiting detail page for station Willis Island
Extracting metadata..
Obtaining metadata for station Lord Howe Island (30/31)
Visiting detail page for station Lord Howe Island
Extracting metadata..
Obtaining metadata for station Launceston (31/31)
Visiting detail page for station Launceston
Extracting metadata..

,station_name,alternative_name_raw,alternative_names,geometry_raw,lat,long,geometry_txt,source_url,retrieved_at_utc
0,Mawson,None,None,Lat. -67.60 Long. 62.88E,-67.60,62.88,POINT (62.88 -67.6),https://sws.bom.gov.au/World_Data_Centre/2/1/23,2026-04-16T06:47:28.506502+00:00
1,Davis,None,None,Lat. -68.58 Long. 77.96E,-68.58,77.96,POINT (77.96 -68.58),https://sws.bom.gov.au/World_Data_Centre/2/1/22,2026-04-16T06:47:28.506502+00:00
2,Casey,Wilkes,[Wilkes],Lat. -66.30 Long. 110.50E,-66.30,110.50,POINT (110.5 -66.3),https://sws.bom.gov.au/World_Data_Centre/2/1/24,2026-04-16T06:47:28.506502+00:00
3,Macquarie Island,None,None,Lat. -54.50 Long. 158.95E,-54.50,158.95,POINT (158.95 -54.5),https://sws.bom.gov.au/World_Data_Centre/2/1/26,2026-04-16T06:47:28.506502+00:00
4,Scott Base,None,None,Lat. -77.80 Long. 166.80E,-77.80,166.80,POINT (166.8 -77.8),https://sws.bom.gov.au/World_Data_Centre/2/1/25,2026-04-16T06:47:28.506502+00:00
5,Learmonth,None,None,Lat. -22.25 Long. 114.08E,-22.25,114.08,POINT (114.08 -22.25),https://sws.bom.gov.au/World_Data_Centre/2/1/21,2026-04-16T06:47:28.506502+00:00
6,Culgoora,Narrabri (although not used with data reports),[Narrabri],Lat. -30.28 Long. 149.58E,-30.28,149.58,POINT (149.58 -30.28),https://sws.bom.gov.au/World_Data_Centre/2/1/27,2026-04-16T06:47:28.506502+00:00
7,Cocos Islands,Keeling Islands,[Keeling Islands],Lat. -12.20 Long. 96.80E,-12.20,96.80,POINT (96.8 -12.2),https://sws.bom.gov.au/World_Data_Centre/2/1/20,2026-04-16T06:47:28.506502+00:00
8,Niue,None,None,Lat. -19.07 Long. 190.07E,-19.07,190.07,POINT (190.07 -19.07),https://sws.bom.gov.au/World_Data_Centre/2/1/18,2026-04-16T06:47:28.506502+00:00
9,Norfolk Island,None,None,Lat. -29.03 Long. 167.97E,-29.03,167.97,POINT (167.97 -29.03),https://sws.bom.gov.au/World_Data_Centre/2/1/19,2026-04-16T06:47:28.506502+00:00
10,Vanimo,None,None,Lat. -2.70 Long. 141.30E,-2.70,141.30,POINT (141.3 -2.7),https://sws.bom.gov.au/World_Data_Centre/2/1/2,2026-04-16T06:47:28.506502+00:00
11,Darwin,none (although there are several - ASWFC and D...,[none],Lat. -12.45 Long. 130.95E,-12.45,130.95,POINT (130.95 -12.45),https://sws.bom.gov.au/World_Data_Centre/2/1/3,2026-04-16T06:47:28.506502+00:00
12,Port Moresby,None,None,Lat. -9.40 Long. 147.10E,-9.40,147.10,POINT (147.1 -9.4),https://sws.bom.gov.au/World_Data_Centre/2/1/4,2026-04-16T06:47:28.506502+00:00
13,Townsville,None,None,Lat. -19.63 Long. 146.85E,-19.63,146.85,POINT (146.85 -19.63),https://sws.bom.gov.au/World_Data_Centre/2/1/5,2026-04-16T06:47:28.506502+00:00
14,Tennant Creek,None,None,Lat. -19.65 Long. 134.25E,-19.65,134.25,POINT (134.25 -19.65),https://sws.bom.gov.au/World_Data_Centre/2/1/6,2026-04-16T06:47:28.506502+00:00
15,Alice Springs,None,None,Lat. -23.81 Long. 133.90E,-23.81,133.90,POINT (133.9 -23.81),https://sws.bom.gov.au/World_Data_Centre/2/1/7,2026-04-16T06:47:28.506502+00:00
16,Watheroo,Mundaring - nearby station,[Mundaring - nearby station],Lat. -30.30 Long. 115.90E,-30.30,115.90,POINT (115.9 -30.3),https://sws.bom.gov.au/World_Data_Centre/2/1/8,2026-04-16T06:47:28.506502+00:00
17,Mundaring,"Watheroo (an earlier, nearby site)",[Watheroo],Lat. -31.98 Long. 116.22E,-31.98,116.22,POINT (116.22 -31.98),https://sws.bom.gov.au/World_Data_Centre/2/1/9,2026-04-16T06:47:28.506502+00:00
18,Brisbane,Bribie Island,[Bribie Island],Lat. -27.53 Long. 152.92E,-27.53,152.92,POINT (152.92 -27.53),https://sws.bom.gov.au/World_Data_Centre/2/1/10,2026-04-16T06:47:28.506502+00:00
19,Woomera,None,None,Lat. -30.80 Long. 136.30E,-30.80,136.30,POINT (136.3 -30.8),https://sws.bom.gov.au/World_Data_Centre/2/1/11,2026-04-16T06:47:28.506502+00:00
20,Salisbury,None,None,Lat. -34.70 Long. 138.60E,-34.70,138.60,POINT (138.6 -34.7),https://sws.bom.gov.au/World_Data_Centre/2/1/12,2026-04-16T06:47:28.506502+00:00
21,Camden,Sydney,[Sydney],Lat. -34.05 Long. 150.67,-34.05,150.67,POINT (150.67 -34.05),https://sws.bom.gov.au/World_Data_Centre/2/1/13,2026-04-16T06:47:28.506502+00:00
22,Canberra,None,None,Lat. -35.32 Long. 149.00E,-35.32,149.00,POINT (149.0 -35.32),https://sws.bom.gov.au/World_Data_Centre/2/1/14,2026-04-16T06:47:28.506502+00:00
23,Hobart,None,None,Lat. -42.92 Long. 147.32E,-42.92,147.32,POINT (147.32 -42.92),https://sws.bom.gov.au/World_Data_Centre/2/1/15,2026-04-16T06:47:28.506502+00:00
24,Auckland,None,None,Lat. -37.00 Long. 175.00E,-37.00,175.00,POINT (175.0 -37.0),https://sws.bom.gov.au/World_Data_Centre/2/1/16,2026-04-16T06:47:28.506502+00:00
25,Christchurch,Godley Head (actually a different nearby locat...,[Godley Head],Lat. -43.60 Long. 172.80E,-43.60,172.80,POINT (172.8 -43.6),https://sws.bom.gov.au/World_Data_Centre/2/1/17,2026-04-16T06:47:28.506502+00:00
26,Weipa,None,None,Lat. -12.63 Long. 141.88E,-12.63,141.88,POINT (141.88 -12.63),https://sws.bom.gov.au/World_Data_Centre/2/1/29,2026-04-16T06:47:28.506502+00:00
27,Perth,Bickley,[Bickley],Lat. -31.94 Long. 115.95E,-31.94,115.95,POINT (115.95 -31.94),https://sws.bom.gov.au/World_Data_Centre/2/1/30,2026-04-16T06:47:28.506502+00:00
28,Willis Island,None,None,Lat. -16.29 Long. 149.97E,-16.29,149.97,POINT (149.97 -16.29),https://sws.bom.gov.au/World_Data_Centre/2/1/31,2026-04-16T06:47:28.506502+00:00
29,Lord Howe Island,None,None,Lat. -31.54 Long. 159.08E,-31.54,159.08,POINT (159.08 -31.54),https://sws.bom.gov.au/World_Data_Centre/2/1/32,2026-04-16T06:47:28.506502+00:00
30,Launceston,None,None,Lat. -41.55 Long. 147.21E,-41.55,147.21,POINT (147.21 -41.55),https://sws.bom.gov.au/World_Data_Centre/2/1/33,2026-04-16T06:47:28.506502+00:00

In [27]:
station_metadata.loc[
    station_metadata["alternative_name_raw"].notnull(),
    ["station_name", "alternative_name_raw", "alternative_names"]
]

,station_name,alternative_name_raw,alternative_names
2,Casey,Wilkes,[Wilkes]
6,Culgoora,Narrabri (although not used with data reports),[Narrabri]
7,Cocos Islands,Keeling Islands,[Keeling Islands]
11,Darwin,none (although there are several - ASWFC and D...,[none]
16,Watheroo,Mundaring - nearby station,[Mundaring - nearby station]
17,Mundaring,"Watheroo (an earlier, nearby site)",[Watheroo]
18,Brisbane,Bribie Island,[Bribie Island]
21,Camden,Sydney,[Sydney]
25,Christchurch,Godley Head (actually a different nearby locat...,[Godley Head]
27,Perth,Bickley,[Bickley]

# Version 2 code for site metadata, after rectifying the spec

- Note we decided to NOT parse `alternative_names` because we already used a lookup table.

In [ ]:
import re
import warnings
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin

import pandas as pd
import requests
from bs4 import BeautifulSoup


# Spec section 2:
# These are the source table keys the metadata builder is expected to extract.
SITE_METADATA_SOURCE_KEYS = {"Station Name", "Alternative Name", "Geographic"}



def get_soup_content(url: str, timeout: int = 30) -> BeautifulSoup:
    """
    Fetch a web page and parse its HTML into a BeautifulSoup object.

    Spec relevance:
    - `src/metadata/site_location.py::get_soup_content`
    - Used for both the WDC map page and each station detail page.

    Notes:
    - HTTP/network failures are not swallowed here. In a future entrypoint, the
      standard logging wrapper can record the stack trace.
    """
    response = requests.get(url, timeout=timeout)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def extract_key_value_rows(soup: BeautifulSoup) -> dict[str, str | None]:
    """
    Extract station-page 2-column table rows into a flat dict.

    Spec relevance:
    - Extract values that come immediately after `Station Name`,
      `Alternative Name`, and `Geographic`.
    - Failure mode: if a relevant row is jagged, e.g. only `['Geographic']`,
      warn and store null rather than failing fast.
    """
    values = {}

    for table in soup.find_all("table"):
        for row in table.find_all("tr"):
            cells = [cell.get_text(strip=True) for cell in row.find_all(["td", "th"])]

            if not cells:
                continue

            key = cells[0]

            # Ignore the repeated table header row: ['Item', 'Value'].
            if key == "Item":
                continue

            # Spec section 4:
            # Jagged table rows should warn, not fail fast.
            if key in SITE_METADATA_SOURCE_KEYS and len(cells) < 2:
                warnings.warn(
                    f"Expected value after '{key}', but parsed row only had: {cells!r}"
                )
                values[key] = None
                continue

            # The station detail pages are expected to be key-value rows.
            if len(cells) >= 2:
                values[key] = cells[1]

    return values


def parse_geographic(geometry_raw: str | None) -> tuple[float | None, float | None, str | None]:
    """
    Parse textual geographic coordinates into latitude, longitude, and WKT-like text.

    Spec relevance:
    - Expected input resembles: 'Lat. -30.28 Long. 149.58E'
    - Output schema fields: `lat`, `lon`, `geometry_txt`
    - Example: 'Lat. -31.54 Long. 159.08E' -> POINT (159.08 -31.54)

    Returns:
    - `(lat, lon, geometry_txt)`
    """
    if geometry_raw is None or pd.isna(geometry_raw):
        return None, None, None

    text = str(geometry_raw).strip()

    match = re.search(
        r"Lat\.\s*([+-]?\d+(?:\.\d+)?)\s+Long\.\s*([+-]?\d+(?:\.\d+)?)([EW])?",
        text,
    )

    if not match:
        # inconsistent with spec: should fail fast?
        warnings.warn(f"Could not parse Geographic value: {geometry_raw!r}")
        return None, None, None

    lat = float(match.group(1))
    lon = float(match.group(2))
    lon_direction = match.group(3)

    # Current observed WDC values mostly use E; this keeps W values correct too.
    if lon_direction == "W":
        lon = -abs(lon)
    elif lon_direction == "E":
        lon = abs(lon)

    geometry_txt = f"POINT ({lon} {lat})"
    return lat, lon, geometry_txt


def extract_station_metadata(
    base_url: str = "https://sws.bom.gov.au",
    map_page_url: str = "https://sws.bom.gov.au/World_Data_Centre/2/1/1",
    metadata_file_path: str = "notebooks/site-metadata.parquet",
) -> str:
    """
    Build one canonical station metadata row per WDC station and save as Parquet.

    Spec relevance:
    - Scrape station `<href>` links from the WDC map page.
    - Visit each station detail page using `base_url + href`.
    - Extract `Station Name`, `Alternative Name`, and `Geographic`.
    - Parse:
      - `Station Name` -> `station_name`
      - `Alternative Name` -> `alternative_name_raw`
      - `Geographic` -> `geometry_raw`, `lat`, `lon`, `geometry_txt`
    - Add `source_url` and `retrieved_at_utc`.
    - Materialize the station metadata as a Parquet table.

    Returns:
    - The output Parquet file path as a string.
    """
    retrieved_at_utc = datetime.now(timezone.utc).isoformat()

    # Spec section 2.1:
    # Scrape station href links from the WDC map page.
    map_soup = get_soup_content(map_page_url)
    area_elements = map_soup.find_all("area")
    num_area_elements = len(area_elements)

    rows = []

    for i, area in enumerate(area_elements):
        station_display_name = area.get("alt")
        print(f"Parsing {i+1} out of {num_area_elements} stations..")
        href = area.get("href")

        # Defensive guard: malformed map entries are skipped with a warning.
        if not station_display_name or not href:
            warnings.warn(
                f"Skipping map area because `alt` or `href` is missing: {area!r}"
            )
            continue

        # Spec section 2.2:
        # Visit the station detail page.
        source_url = urljoin(base_url, href)
        station_soup = get_soup_content(source_url)

        # Spec section 2.3:
        # Extract source fields from station metadata tables.
        kv = extract_key_value_rows(station_soup)

        station_name = kv.get("Station Name")
        alternative_name_raw = kv.get("Alternative Name")
        geometry_raw = kv.get("Geographic")

        # Spec section 4:
        # Missing key fields warn but do not fail fast.
        if station_name is None:
            warnings.warn(
                f"`Station Name` missing for {source_url}; using map display name "
                f"{station_display_name!r} as fallback."
            )
            station_name = station_display_name

        if alternative_name_raw is None:
            warnings.warn(f"`Alternative Name` missing for station {station_name!r}.")

        if geometry_raw is None:
            warnings.warn(f"`Geographic` missing for station {station_name!r}.")

        # Parse `Geographic` into `lat`, `lon`, and human-readable `geometry_txt`.
        lat, lon, geometry_txt = parse_geographic(geometry_raw)

        # Store one canonical row per station.
        rows.append(
            {
                "station_name": station_name,
                "alternative_name_raw": alternative_name_raw,
                "geometry_raw": geometry_raw,
                "lat": lat,
                "lon": lon,
                "geometry_txt": geometry_txt,
                "source_url": source_url,
                "retrieved_at_utc": retrieved_at_utc,
            }
        )

    station_metadata = pd.DataFrame(
        rows,
        columns=[
            "station_name",
            "alternative_name_raw",
            "geometry_raw",
            "lat",
            "lon",
            "geometry_txt",
            "source_url",
            "retrieved_at_utc",
        ],
    )

    output_path = Path(metadata_file_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Spec section 2:
    # Materialize station metadata as Parquet.
    station_metadata.to_parquet(output_path, index=False)

    return str(output_path)

# Try saving site metadata at `notebooks/` first

In [23]:
metadata_path = extract_station_metadata(
    metadata_file_path="notebooks/site-metadata.parquet"
)


station_metadata = pd.read_parquet(metadata_path)

station_metadata

Parsing 1 out of 31 stations..
Parsing 2 out of 31 stations..
Parsing 3 out of 31 stations..
Parsing 4 out of 31 stations..
Parsing 5 out of 31 stations..
Parsing 6 out of 31 stations..
Parsing 7 out of 31 stations..
Parsing 8 out of 31 stations..
Parsing 9 out of 31 stations..
Parsing 10 out of 31 stations..
Parsing 11 out of 31 stations..
Parsing 12 out of 31 stations..
Parsing 13 out of 31 stations..
Parsing 14 out of 31 stations..
Parsing 15 out of 31 stations..
Parsing 16 out of 31 stations..
Parsing 17 out of 31 stations..
Parsing 18 out of 31 stations..
Parsing 19 out of 31 stations..
Parsing 20 out of 31 stations..
Parsing 21 out of 31 stations..
Parsing 22 out of 31 stations..
Parsing 23 out of 31 stations..
Parsing 24 out of 31 stations..
Parsing 25 out of 31 stations..
Parsing 26 out of 31 stations..
Parsing 27 out of 31 stations..
Parsing 28 out of 31 stations..
Parsing 29 out of 31 stations..
Parsing 30 out of 31 stations..
Parsing 31 out of 31 stations..

,station_name,alternative_name_raw,geometry_raw,lat,lon,geometry_txt,source_url,retrieved_at_utc
0,Mawson,None,Lat. -67.60 Long. 62.88E,-67.60,62.88,POINT (62.88 -67.6),https://sws.bom.gov.au/World_Data_Centre/2/1/23,2026-04-30T06:58:11.575704+00:00
1,Davis,None,Lat. -68.58 Long. 77.96E,-68.58,77.96,POINT (77.96 -68.58),https://sws.bom.gov.au/World_Data_Centre/2/1/22,2026-04-30T06:58:11.575704+00:00
2,Casey,Wilkes,Lat. -66.30 Long. 110.50E,-66.30,110.50,POINT (110.5 -66.3),https://sws.bom.gov.au/World_Data_Centre/2/1/24,2026-04-30T06:58:11.575704+00:00
3,Macquarie Island,None,Lat. -54.50 Long. 158.95E,-54.50,158.95,POINT (158.95 -54.5),https://sws.bom.gov.au/World_Data_Centre/2/1/26,2026-04-30T06:58:11.575704+00:00
4,Scott Base,None,Lat. -77.80 Long. 166.80E,-77.80,166.80,POINT (166.8 -77.8),https://sws.bom.gov.au/World_Data_Centre/2/1/25,2026-04-30T06:58:11.575704+00:00
5,Learmonth,None,Lat. -22.25 Long. 114.08E,-22.25,114.08,POINT (114.08 -22.25),https://sws.bom.gov.au/World_Data_Centre/2/1/21,2026-04-30T06:58:11.575704+00:00
6,Culgoora,Narrabri (although not used with data reports),Lat. -30.28 Long. 149.58E,-30.28,149.58,POINT (149.58 -30.28),https://sws.bom.gov.au/World_Data_Centre/2/1/27,2026-04-30T06:58:11.575704+00:00
7,Cocos Islands,Keeling Islands,Lat. -12.20 Long. 96.80E,-12.20,96.80,POINT (96.8 -12.2),https://sws.bom.gov.au/World_Data_Centre/2/1/20,2026-04-30T06:58:11.575704+00:00
8,Niue,None,Lat. -19.07 Long. 190.07E,-19.07,190.07,POINT (190.07 -19.07),https://sws.bom.gov.au/World_Data_Centre/2/1/18,2026-04-30T06:58:11.575704+00:00
9,Norfolk Island,None,Lat. -29.03 Long. 167.97E,-29.03,167.97,POINT (167.97 -29.03),https://sws.bom.gov.au/World_Data_Centre/2/1/19,2026-04-30T06:58:11.575704+00:00
10,Vanimo,None,Lat. -2.70 Long. 141.30E,-2.70,141.30,POINT (141.3 -2.7),https://sws.bom.gov.au/World_Data_Centre/2/1/2,2026-04-30T06:58:11.575704+00:00
11,Darwin,none (although there are several - ASWFC and D...,Lat. -12.45 Long. 130.95E,-12.45,130.95,POINT (130.95 -12.45),https://sws.bom.gov.au/World_Data_Centre/2/1/3,2026-04-30T06:58:11.575704+00:00
12,Port Moresby,None,Lat. -9.40 Long. 147.10E,-9.40,147.10,POINT (147.1 -9.4),https://sws.bom.gov.au/World_Data_Centre/2/1/4,2026-04-30T06:58:11.575704+00:00
13,Townsville,None,Lat. -19.63 Long. 146.85E,-19.63,146.85,POINT (146.85 -19.63),https://sws.bom.gov.au/World_Data_Centre/2/1/5,2026-04-30T06:58:11.575704+00:00
14,Tennant Creek,None,Lat. -19.65 Long. 134.25E,-19.65,134.25,POINT (134.25 -19.65),https://sws.bom.gov.au/World_Data_Centre/2/1/6,2026-04-30T06:58:11.575704+00:00
15,Alice Springs,None,Lat. -23.81 Long. 133.90E,-23.81,133.90,POINT (133.9 -23.81),https://sws.bom.gov.au/World_Data_Centre/2/1/7,2026-04-30T06:58:11.575704+00:00
16,Watheroo,Mundaring - nearby station,Lat. -30.30 Long. 115.90E,-30.30,115.90,POINT (115.9 -30.3),https://sws.bom.gov.au/World_Data_Centre/2/1/8,2026-04-30T06:58:11.575704+00:00
17,Mundaring,"Watheroo (an earlier, nearby site)",Lat. -31.98 Long. 116.22E,-31.98,116.22,POINT (116.22 -31.98),https://sws.bom.gov.au/World_Data_Centre/2/1/9,2026-04-30T06:58:11.575704+00:00
18,Brisbane,Bribie Island,Lat. -27.53 Long. 152.92E,-27.53,152.92,POINT (152.92 -27.53),https://sws.bom.gov.au/World_Data_Centre/2/1/10,2026-04-30T06:58:11.575704+00:00
19,Woomera,None,Lat. -30.80 Long. 136.30E,-30.80,136.30,POINT (136.3 -30.8),https://sws.bom.gov.au/World_Data_Centre/2/1/11,2026-04-30T06:58:11.575704+00:00
20,Salisbury,None,Lat. -34.70 Long. 138.60E,-34.70,138.60,POINT (138.6 -34.7),https://sws.bom.gov.au/World_Data_Centre/2/1/12,2026-04-30T06:58:11.575704+00:00
21,Camden,Sydney,Lat. -34.05 Long. 150.67,-34.05,150.67,POINT (150.67 -34.05),https://sws.bom.gov.au/World_Data_Centre/2/1/13,2026-04-30T06:58:11.575704+00:00
22,Canberra,None,Lat. -35.32 Long. 149.00E,-35.32,149.00,POINT (149.0 -35.32),https://sws.bom.gov.au/World_Data_Centre/2/1/14,2026-04-30T06:58:11.575704+00:00
23,Hobart,None,Lat. -42.92 Long. 147.32E,-42.92,147.32,POINT (147.32 -42.92),https://sws.bom.gov.au/World_Data_Centre/2/1/15,2026-04-30T06:58:11.575704+00:00
24,Auckland,None,Lat. -37.00 Long. 175.00E,-37.00,175.00,POINT (175.0 -37.0),https://sws.bom.gov.au/World_Data_Centre/2/1/16,2026-04-30T06:58:11.575704+00:00
25,Christchurch,Godley Head (actually a different nearby locat...,Lat. -43.60 Long. 172.80E,-43.60,172.80,POINT (172.8 -43.6),https://sws.bom.gov.au/World_Data_Centre/2/1/17,2026-04-30T06:58:11.575704+00:00
26,Weipa,None,Lat. -12.63 Long. 141.88E,-12.63,141.88,POINT (141.88 -12.63),https://sws.bom.gov.au/World_Data_Centre/2/1/29,2026-04-30T06:58:11.575704+00:00
27,Perth,Bickley,Lat. -31.94 Long. 115.95E,-31.94,115.95,POINT (115.95 -31.94),https://sws.bom.gov.au/World_Data_Centre/2/1/30,2026-04-30T06:58:11.575704+00:00
28,Willis Island,None,Lat. -16.29 Long. 149.97E,-16.29,149.97,POINT (149.97 -16.29),https://sws.bom.gov.au/World_Data_Centre/2/1/31,2026-04-30T06:58:11.575704+00:00
29,Lord Howe Island,None,Lat. -31.54 Long. 159.08E,-31.54,159.08,POINT (159.08 -31.54),https://sws.bom.gov.au/World_Data_Centre/2/1/32,2026-04-30T06:58:11.575704+00:00
30,Launceston,None,Lat. -41.55 Long. 147.21E,-41.55,147.21,POINT (147.21 -41.55),https://sws.bom.gov.au/World_Data_Centre/2/1/33,2026-04-30T06:58:11.575704+00:00

# Join logic (lookup table)

## Hardcode lookup table

In [26]:
import pandas as pd

location_lookup = pd.DataFrame(
    [
        {"api_location": "Alice Springs", "canonical_station_name": "Alice Springs"},
        {"api_location": "Canberra", "canonical_station_name": "Canberra"},
        {"api_location": "Cocos Island", "canonical_station_name": "Cocos Islands"},
        {"api_location": "Narrabri", "canonical_station_name": "Culgoora"},
        {"api_location": "Darwin", "canonical_station_name": "Darwin"},
        {"api_location": "Hobart", "canonical_station_name": "Hobart"},
        {"api_location": "Launceston", "canonical_station_name": "Launceston"},
        {"api_location": "Learmonth", "canonical_station_name": "Learmonth"},
        {"api_location": "Melbourne", "canonical_station_name": None},
        {"api_location": "Norfolk Island", "canonical_station_name": "Norfolk Island"},
        {"api_location": "Perth", "canonical_station_name": "Perth"},
        {"api_location": "Sydney", "canonical_station_name": "Camden"},
        {"api_location": "Townsville", "canonical_station_name": "Townsville"},
        {"api_location": "Casey", "canonical_station_name": "Casey"},
        {"api_location": "Davis", "canonical_station_name": "Davis"},
        {"api_location": "Macquarie Island", "canonical_station_name": "Macquarie Island"},
        {"api_location": "Mawson", "canonical_station_name": "Mawson"},
        {"api_location": "Australian region", "canonical_station_name": None},
    ]
)

location_lookup

         api_location canonical_station_name
0       Alice Springs          Alice Springs
1            Canberra               Canberra
2        Cocos Island          Cocos Islands
3            Narrabri               Culgoora
4              Darwin                 Darwin
5              Hobart                 Hobart
6          Launceston             Launceston
7           Learmonth              Learmonth
8           Melbourne                   None
9      Norfolk Island         Norfolk Island
10              Perth                  Perth
11             Sydney                 Camden
12         Townsville             Townsville
13              Casey                  Casey
14              Davis                  Davis
15   Macquarie Island       Macquarie Island
16             Mawson                 Mawson
17  Australian region                   None

In [ ]:
# brief check on current T2
t2 = duckdb.read_parquet(T2_dir).df()
t2

                location          valid_time  kindex   flag
0      Australian region 2020-09-08 18:00:00       1  False
1      Australian region 2020-09-12 00:00:00       1  False
2      Australian region 2020-09-14 18:00:00       0  False
3      Australian region 2020-09-19 18:00:00       0  False
4      Australian region 2020-09-20 06:00:00       0  False
...                  ...                 ...     ...    ...
31628  Australian region 2022-11-03 09:00:00       5  False
31629  Australian region 2022-11-07 03:00:00       2  False
31630  Australian region 2022-11-08 06:00:00       2  False
31631  Australian region 2022-11-08 18:00:00       1  False
31632  Australian region 2022-11-10 06:00:00       0  False

[31633 rows x 4 columns]

In [27]:
import duckdb

T2_path = "data/02-preprocessed/space_weather/k_index/T2/**/*.parquet"
site_metadata_path = "notebooks/site-metadata.parquet"

duckdb.register("location_lookup", location_lookup)

query = f"""
WITH t2 AS (
    SELECT *
    FROM read_parquet('{T2_path}')
),

metadata AS (
    SELECT
        station_name,
        alternative_name_raw,
        geometry_raw,
        lat,
        lon,
        geometry_txt,
        source_url,
        retrieved_at_utc
    FROM read_parquet('{site_metadata_path}')
),

joined AS (
    SELECT
        t2.location,
        t2.valid_time,
        t2.kindex,
        t2.flag,
        l.canonical_station_name,
        m.station_name,
        m.alternative_name_raw,
        m.geometry_raw,
        m.lat,
        m.lon,
        m.geometry_txt,
        m.source_url,
        m.retrieved_at_utc,
        CASE
            WHEN l.api_location IS NULL THEN 'unmapped_api_location'
            WHEN l.canonical_station_name IS NULL THEN 'known_without_station'
            WHEN m.station_name IS NULL THEN 'lookup_target_missing_in_metadata'
            ELSE 'lookup_match'
        END AS match_type
    FROM t2
    LEFT JOIN location_lookup AS l
        ON t2.location = l.api_location
    LEFT JOIN metadata AS m
        ON l.canonical_station_name = m.station_name
)

SELECT *
FROM joined
"""

t2_with_metadata = duckdb.sql(query).df()

In [28]:
# view all matched and unmatched locations
t2_with_metadata[
    ["location", "canonical_station_name", "station_name", "geometry_txt", "match_type"]
].drop_duplicates().sort_values("location")

,location,canonical_station_name,station_name,geometry_txt,match_type
131,Alice Springs,Alice Springs,Alice Springs,POINT (133.9 -23.81),lookup_match
478,Australian region,None,None,None,known_without_station
296,Cocos Island,Cocos Islands,Cocos Islands,POINT (96.8 -12.2),lookup_match
0,Darwin,Darwin,Darwin,POINT (130.95 -12.45),lookup_match

In [29]:
t2_with_metadata["match_type"].value_counts(dropna=False)

match_type
known_without_station    23617
lookup_match              8016
Name: count, dtype: int64

In [30]:
t2_with_metadata.loc[
    t2_with_metadata["match_type"] != "lookup_match",
    ["location", "canonical_station_name", "match_type"]
].drop_duplicates().sort_values("location")

              location canonical_station_name             match_type
478  Australian region                   None  known_without_station