In [14]:
import duckdb
import os
from pathlib import Path

# ensuring that os.chdir is idempotent and that we are in the project root directory,
# not inside the notebooks directory
if 'notebooks' not in os.listdir(Path.cwd()):
    print("Still inside notebooks directory, changing to project root directory.")
    os.chdir(Path.cwd().parent)
    print("Current working directory after change: ", Path.cwd())
else:
    print(f"Already in parent directory (current working directory: {Path.cwd()})")


# load config
from src.io.load_config import load_config
sw_config = load_config()['space_weather']
omni_config = load_config()['omni']

Already in parent directory (current working directory: d:\data-sci-projects\space-weather-project-scrub)

# Test endpoints from CDAWeb HAPI

CDAWeb HAPI description can be found at https://cdaweb.gsfc.nasa.gov/hapi

In [15]:
import pandas as pd
import requests
from io import StringIO
import json

## `/info`

In [16]:
def fetch_info_omni_hro2_1min(dataset_id="OMNI_HRO2_1MIN",
                            base_url="https://cdaweb.gsfc.nasa.gov/hapi",
                            ):

    # as per HAPI description, endpoints respond to HTTP GET requests 
    response = requests.get(base_url + '/info',
                            params={"id": dataset_id},
                            timeout=120)
    
    response.raise_for_status()

    return response.json()

In [17]:
info_endpoint_test = fetch_info_omni_hro2_1min()

In [18]:
info_endpoint_test

{'HAPI': '2.0',
 'resourceURL': 'https://cdaweb.gsfc.nasa.gov/misc/NotesO.html#OMNI_HRO2_1MIN',
 'contact': 'J.H. King, N. Papatashvilli @ AdnetSystems, NASA GSFC',
 'parameters': [{'name': 'Time',
   'length': 24,
   'units': 'UTC',
   'type': 'isotime',
   'fill': None},
  {'name': 'IMF',
   'description': 'OMNI ID code for the source spacecraft for time-shifted IMF values (see OMNI documentation link for codes)',
   'units': None,
   'type': 'integer',
   'fill': '99'},
  {'name': 'PLS',
   'description': 'OMNI ID code for the source spacecraft  for time-shifted IP plasma values (see OMNI documentation link for codes)',
   'units': None,
   'type': 'integer',
   'fill': '99'},
  {'name': 'IMF_PTS',
   'description': 'Number of fine time scale points in IMF averages',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'PLS_PTS',
   'description': 'Number of fine time scale points in plasma averages',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'percent_interp',
   'description': 'Percent interpolated',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'Timeshift',
   'description': 'Timeshift (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'RMS_Timeshift',
   'description': 'RMS Timeshift (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'RMS_phase',
   'description': 'RMS, Phase front normal (nT) ',
   'units': 'nT',
   'type': 'double',
   'fill': '99.99'},
  {'name': 'Time_btwn_obs',
   'description': 'Time between observations (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'F',
   'description': 'Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BX_GSE',
   'description': 'Bx (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BY_GSE',
   'description': 'By (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BZ_GSE',
   'description': 'Bz (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BY_GSM',
   'description': 'By (nT), GSM, determined from post-shift GSE components',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BZ_GSM',
   'description': 'Bz (nT), GSM, determined from post-shift GSE components',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'RMS_SD_B',
   'description': 'RMS SD B scalar (nT)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'RMS_SD_fld_vec',
   'description': 'RMS SD field vector (nT)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'flow_speed',
   'description': 'Flow Speed (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vx',
   'description': 'Vx Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vy',
   'description': 'Vy Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vz',
   'description': 'Vz Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'proton_density',
   'description': 'Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)',
   'units': 'n/cc',
   'type': 'double',
   'fill': '999.99'},
  {'name': 'T',
   'description': 'Temperature (K)',
   'units': 'K',
   'type': 'double',
   'fill': '9999999.0'},
  {'name': 'NaNp_Ratio',
   'description': 'Alpha/Proton Density Ratio',
   'units': ' ',
   'type': 'double',
   'fill': '9.999'},
  {'name': 'Pressure',
   'description': 'Flow pressure (nPa)',
   'units': 'nPa',
   'type': 'double',
   'fill': '99.99'},
  {'name': 'E',
   'description': 'Electric Field (mV/m)',
   'units': 'mV/m',
   'type': 'double',
   'fill': '999.99'},
  {'name': 'Beta',
   'description': 'Plasma beta',
   'units': None,
   'type': 'double',
   'fill': '999.99'},
  {'name': 'Mach_num',
   'description': 'Alfven mach number',
   'units': None,
   'type': 'double',
   'fill': '999.9'},
  {'name': 'Mgs_mach_num',
   'description': '1AU IP Magnetosonic mach number',
   'units': None,
   'type': 'double',
   'fill': '99.9'},
  {'name': 'x',
   'description': 'X s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'y',
   'description': 'Y s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'z',
   'description': 'Z s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_x',
   'description': 'Bow Shock Nose (Re) location, X, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_y',
   'description': 'Bow Shock Nose (Re) location, Y, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_z',
   'description': 'Bow Shock Nose (Re) location, Z, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'AE_INDEX',
   'description': 'AE - 1-minute AE-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'AL_INDEX',
   'description': 'AL - 1-minute AL-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'AU_INDEX',
   'description': 'AU - 1-minute AU-index,from WDC Kyoto  (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'SYM_D',
   'description': 'SYM/D - 1-minute SYM/D index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'SYM_H',
   'description': 'SYM/H - 1-minute SYM/H index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'ASY_D',
   'description': 'ASY/D - 1-minute ASY/D index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'ASY_H',
   'description': 'ASY/H - 1-minute ASY/H index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'}],
 'startDate': '1995-01-01T00:00:00Z',
 'stopDate': '2026-04-13T01:15:00Z',
 'status': {'code': 1200, 'message': 'OK'}}

In [10]:
pd.DataFrame(info_endpoint_test['parameters'])

,name,length,units,type,fill,description
0,Time,24.0,UTC,isotime,None,NaN
1,IMF,NaN,None,integer,99,OMNI ID code for the source spacecraft for tim...
2,PLS,NaN,None,integer,99,OMNI ID code for the source spacecraft for ti...
3,IMF_PTS,NaN,None,integer,999,Number of fine time scale points in IMF averages
4,PLS_PTS,NaN,None,integer,999,Number of fine time scale points in plasma ave...
5,percent_interp,NaN,None,integer,999,Percent interpolated
6,Timeshift,NaN,seconds,integer,999999,Timeshift (seconds)
7,RMS_Timeshift,NaN,seconds,integer,999999,RMS Timeshift (seconds)
8,RMS_phase,NaN,nT,double,99.99,"RMS, Phase front normal (nT)"
9,Time_btwn_obs,NaN,seconds,integer,999999,Time between observations (seconds)
10,F,NaN,nT,double,9999.99,Magnitude of avg. field vector (nT) (last curr...
11,BX_GSE,NaN,nT,double,9999.99,"Bx (nT), GSE"
12,BY_GSE,NaN,nT,double,9999.99,"By (nT), GSE"
13,BZ_GSE,NaN,nT,double,9999.99,"Bz (nT), GSE"
14,BY_GSM,NaN,nT,double,9999.99,"By (nT), GSM, determined from post-shift GSE c..."
15,BZ_GSM,NaN,nT,double,9999.99,"Bz (nT), GSM, determined from post-shift GSE c..."
16,RMS_SD_B,NaN,nT,double,9999.99,RMS SD B scalar (nT)
17,RMS_SD_fld_vec,NaN,nT,double,9999.99,RMS SD field vector (nT)
18,flow_speed,NaN,km/s,double,99999.9,"Flow Speed (km/s), GSE"
19,Vx,NaN,km/s,double,99999.9,"Vx Velocity (km/s), GSE"
20,Vy,NaN,km/s,double,99999.9,"Vy Velocity (km/s), GSE"
21,Vz,NaN,km/s,double,99999.9,"Vz Velocity (km/s), GSE"
22,proton_density,NaN,n/cc,double,999.99,Proton density (n/cc) (last currently-availabl...
23,T,NaN,K,double,9999999.0,Temperature (K)
24,NaNp_Ratio,NaN,,double,9.999,Alpha/Proton Density Ratio
25,Pressure,NaN,nPa,double,99.99,Flow pressure (nPa)
26,E,NaN,mV/m,double,999.99,Electric Field (mV/m)
27,Beta,NaN,None,double,999.99,Plasma beta
28,Mach_num,NaN,None,double,999.9,Alfven mach number
29,Mgs_mach_num,NaN,None,double,99.9,1AU IP Magnetosonic mach number
30,x,NaN,Re,double,9999.99,"X s/c (Re), GSE"
31,y,NaN,Re,double,9999.99,"Y s/c (Re), GSE"
32,z,NaN,Re,double,9999.99,"Z s/c (Re), GSE"
33,BSN_x,NaN,Re,double,9999.99,"Bow Shock Nose (Re) location, X, GSE"
34,BSN_y,NaN,Re,double,9999.99,"Bow Shock Nose (Re) location, Y, GSE"
35,BSN_z,NaN,Re,double,9999.99,"Bow Shock Nose (Re) location, Z, GSE"
36,AE_INDEX,NaN,nT,integer,99999,"AE - 1-minute AE-index, from WDC Kyoto (Final ..."
37,AL_INDEX,NaN,nT,integer,99999,"AL - 1-minute AL-index, from WDC Kyoto (Final ..."
38,AU_INDEX,NaN,nT,integer,99999,"AU - 1-minute AU-index,from WDC Kyoto (Final ..."
39,SYM_D,NaN,nT,integer,99999,"SYM/D - 1-minute SYM/D index,from WDC Kyoto (1..."
40,SYM_H,NaN,nT,integer,99999,"SYM/H - 1-minute SYM/H index,from WDC Kyoto (1..."
41,ASY_D,NaN,nT,integer,99999,"ASY/D - 1-minute ASY/D index,from WDC Kyoto (1..."
42,ASY_H,NaN,nT,integer,99999,"ASY/H - 1-minute ASY/H index,from WDC Kyoto (1..."

In [ ]:
query_var = 'BX_GSE'
display(
    pd.DataFrame(info_endpoint_test['parameters']).query(f"name=='{query_var}'")
)

display(
    pd.DataFrame(info_endpoint_test['parameters']).query(f"name=='{query_var}'").fill.item()
)

## `/data` (with params)

In [29]:
# https://cdaweb.gsfc.nasa.gov/hapi/data?id=OMNI_HRO2_1MIN&parameters=F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure&time.min=2021-11-21T00:00:00Z&time.max=2021-11-22T00:00:00Z&format=csv
def fetch_data_omni_hro2_1min(start_utc: str,
                         end_utc: str,
                         vars: str="F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure",
                         format=None
                         ):

    url = "https://cdaweb.gsfc.nasa.gov/hapi/data"

    params = {
        "id": "OMNI_HRO2_1MIN",
        "time.min": start_utc,
        "time.max": end_utc,
        "format": format
    }
    
    if vars:
        # no intermediate or trailing whitespaces allowed
        vars = vars.replace(" ", "")
        params['parameters'] = vars

    print("Requesting solar dataset from OMNI_HRO2_1MIN...")
    response = requests.get(url, params=params, timeout=120)
    print(response.text)
    response.raise_for_status()
    print("Request succeeded.")
    
    if not format or format == 'csv':
        df = pd.read_csv(StringIO(response.text),
                        comment="#",
                        header=None)
        df.columns = ["time"] + vars.split(',')
        return df
    

    if format == 'json':
        try:
            return response.json()
        except Exception as e:
            print("⚠️⚠️ MALFOMED JSON RESPONSE ⚠️⚠️. Returning raw response instead.")
            print(repr(e))
            return response.text

### Return csv

#### Success

In [7]:
fetch_data_omni_hro2_1min(
    start_utc="2021-11-21T00:00:00Z",
    end_utc="2021-11-22T00:00:00Z"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
2021-11-21T00:00:00.000Z,4.79,1.87,-2.40,-3.37,99999.9,999.99,99.99
2021-11-21T00:01:00.000Z,5.73,4.25,0.29,2.60,99999.9,999.99,99.99
2021-11-21T00:02:00.000Z,4.90,1.72,-3.04,-3.39,583.6,4.70,3.20
2021-11-21T00:03:00.000Z,4.92,2.03,-3.04,-3.23,583.6,4.70,3.20
2021-11-21T00:04:00.000Z,5.00,1.68,-2.93,-3.67,583.6,4.70,3.20
2021-11-21T00:05:00.000Z,5.09,1.65,-3.44,-3.23,583.0,4.62,3.14
2021-11-21T00:06:00.000Z,5.13,1.61,-3.50,-3.36,583.0,4.62,3.14
2021-11-21T00:07:00.000Z,5.57,3.56,-0.86,0.89,574.7,4.18,2.76
2021-11-21T00:08:00.000Z,5.64,3.86,0.77,2.73,574.5,4.19,2.77
2021-11-21T00:09:00.000Z,5.35,4.26,-0.27,1.52,568.1,4.37,2.82
2021-11-21T00:10:00.000Z,5.46,4.09,-0.17,1.75,569.0,4.36,2.82
2021-11-21T00:11:00.000Z,5.36,3.95,-0.69,0.85,569.3,4.35,2.82
2021-11-21T00:12:00.000Z,5.34,4.09,-0.32,1.00,578.4,4.73,3.16
2021-11-21T00:13:00.000Z,5.20,3.99,-0.29,0.88,574.5,4.53,2.99
2021-11-21T00:14:00.000Z,5.08,3.89,-0.34,1.14,99999.9,999.99,99.99
2021-11-21T00:15:00.000Z,4.99,4.03,-0.08,1.19,570.2,4.22,2.74
2021-11-21T00:16:00.000Z,5.16,2.35,-2.30,-1.21,577.6,4.36,2.91
2021-11-21T00:17:00.000Z,4.86,2.52,-2.02,-1.65,583.4,4.93,3.36
2021-11-21T00:18:00.000Z,5.15,2.73,-2.16,-1.91,576.6,4.46,2.97
2021-11-21T00:19:00.000Z,5.06,3.02,-1.64,-0.80,583.4,4.73,3.22
2021-11-21T00:20:00.000Z,5.14,3.87,-0.92,0.49,575.8,4.56,3.02
2021-11-21T00:21:00.000Z,4.90,3.28,-2.01,-0.46,575.0,4.53,3.00
2021-11-21T00:22:00.000Z,5.19,3.83,0.08,0.52,573.3,4.48,2.94
2021-11-21T00:23:00.000Z,5.21,3.64,-0.28,0.37,572.8,4.46,2.93
2021-11-21T00:24:00.000Z,5.44,3.98,-0.15,1.33,578.9,4.61,3.09
2021-11-21T00:25:00.000Z,5.61,4.14,0.50,2.51,576.7,4.63,3.08
2021-11-21T00:26:00.000Z,5.78,3.93,1.36,3.76,574.7,4.66,3.08
2021-11-21T00:27:00.000Z,5.53,3.77,1.16,2.08,576.6,4.51,3.00
2021-11-21T00:28:00.000Z,5.63,4.03,1.15,2.38,576.6,4.51,3.00
2021-11-21T00:29:00.000Z,5.62,4.23,0.92,2.05,572.9,4.35,2.86
2021-11-21T00:30:00.000Z,6.06,4.62,1.47,3.64,572.7,4.34,2.85
2021-11-21T00:31:00.000Z,5.66,4.43,1.32,1.84,570.5,4.21,2.74
2021-11-21T00:32:00.000Z,5.67,4.35,1.33,1.64,570.5,4.21,2.74
2021-11-21T00:33:00.000Z,5.63,4.31,0.72,1.46,579.2,4.65,3.12
2021-11-21T00:34:00.000Z,5.39,4.28,1.38,2.79,583.2,4.68,3.18
2021-11-21T00:35:00.000Z,4.73,3.52,0.51,0.61,584.6,4.57,3.12
2021-11-21T00:36:00.000Z,4.70,3.63,0.32,0.40,99999.9,999.99,99.99
2021-11-21T00:37:00.000Z,5.27,4.81,0.43,1.67,575.5,4.18,2.77
2021-11-21T00:38:00.000Z,5.02,4.80,-0.45,1.00,579.2,4.32,2.90
2021-11-21T00:39:00.000Z,4.07,3.34,-1.18,-1.04,584.9,4.55,3.11
2021-11-21T00:40:00.000Z,3.95,3.57,-1.43,-0.11,582.4,4.56,3.09
2021-11-21T00:41:00.000Z,5.00,4.32,-2.19,0.20,581.5,4.46,3.02
2021-11-21T00:42:00.000Z,5.10,4.26,-1.85,1.01,585.7,4.78,3.28
2021-11-21T00:43:00.000Z,4.61,3.45,-2.59,-0.70,584.4,4.79,3.27
2021-11-21T00:44:00.000Z,5.07,4.30,-2.14,1.21,583.8,4.00,2.73
2021-11-21T00:45:00.000Z,5.05,4.41,-1.84,1.08,582.0,3.97,2.69
2021-11-21T00:46:00.000Z,4.18,3.31,-2.45,-0.06,583.0,4.61,3.13
2021-11-21T00:47:00.000Z,4.46,3.37,-2.88,-0.34,582.6,4.77,3.24
2021-11-21T00:48:00.000Z,4.33,2.28,-2.95,-1.84,582.1,4.96,3.36
2021-11-21T00:49:00.000Z,4.16,2.84,-2.49,-1.37,592.9,4.98,3.50
2021-11-21T00:50:00.000Z,4.23,2.74,-2.65,-1.10,592.9,4.98,3.50
2021-11-21T00:51:00.000Z,4.47,1.57,-3.61,-0.69,592.9,4.98,3.50
2021-11-21T00:52:00.000Z,4.52,1.47,-3.36,-1.87,590.7,4.36,3.04
2021-11-21T00:53:00.000Z,5.04,2.20,-3.75,-1.07,590.9,4.64,3.24
2021-11-21T00:54:00.000Z,5.22,2.45,-4.15,0.39,591.0,4.88,3.41
2021-11-21T00:55:00.000Z,4.94,1.86,-3.72,-1.99,99999.9,999.99,99.99
2021-11-21T00:56:00.000Z,5.20,2.53,-4.08,-1.62,99999.9,999.99,99.99
2021-11-21T00:57:00.000Z,5.32,2.95,-4.12,-1.38,587.9,4.28,2.96
2021-11-21T00:58:00.000Z,5.76,2.79,-4.12,-2.77,586.1,4.43,3.04
2021-11-21T00:59:00.000Z,5.54,3.45,-4.06,-1.48,581.5,4.70,3.18
2021-11-21T01:00:00.000Z,5.74,2.56,-3.74,-3.29,595.6,3.99,2.83
2021-11-21T01:01:00.000Z,5.83,3.03,-3.41,-3.55,595.6,3.99,2.83
2021-11-21T01:02:00.000Z,5.64,2.42,-3.55,-3.58,599.1,4.43,3.18
2021-11-21T01:03:00.000Z,5.45,1.61,-3.68,-3.65,600.8,4.65,3.36
2021-11-21T01:04:00.000Z,5.54,1.76,-3.77,-3.58,595.8,4.25,3.02
2021-11-21T01:05:00.000Z,5.28,2.57,-3.14,-3.26,595.8,4.25,3.02
2021-11-21T01:06:00.000Z,5.61,2.18,-4.29,-2.78,595.8,4.25,3.02
2021-11-21T01:07:00.000Z,5.50,2.30,-4.48,-2.20,599.5,4.29,3.08
2021-11-21T01:08:00.000Z,5.48,2.22,-4.41,-2.32,599.5,4.29,3.08
2021-11-21T01:09:00.000Z,5.48,2.22,-4.42,-2.32,99999.9,999.99,99.99
2021-11-21T01:10:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2021-11-21T01:11:00.000Z,5.53,2.32,-4.33,-2.55,99999.9,999.99,99.99
2021-11-21T01:12:00.000Z,5.43,2.19,-4.25,-2.56,99999.9,999.99,99.99
2021-11-21T01:13:00.000Z,5.32,1.96,-4.03,-2.86,99999.9,999.99,99.99
2021-11-21T01:14:00.000Z,5.40,2.04,-4.12,-2.80,99999.9,999.99,99.99
2021-11-21T01:15:00.000Z,6.02,1.30,-4.56,-3.70,609.8,4.32,3.21
2021-11-21T01:16:00.000Z,5.97,1.51,-4.40,-3.65,610.8,4.23,3.16
2021-11-21T01:17:00.000Z,5.88,1.72,-4.43,-3.25,605.6,4.22,3.10
2021-11-21T01:18:00.000Z,5.97,2.36,-4.45,-3.05,599.0,4.32,3.10
2021-11-21T01:19:00.000Z,5.97,2.61,-4.60,-2.61,600.4,4.21,3.04
2021-11-21T01:20:00.000Z,5.97,2.16,-4.49,-3.18,600.4,4.21,3.04
2021-11-21T01:21:00.000Z,6.21,2.80,-4.73,-2.87,605.3,4.35,3.19
2021-11-21T01:22:00.000Z,6.46,2.51,-5.11,-2.94,605.7,4.27,3.13
2021-11-21T01:23:00.000Z,6.39,2.76,-5.04,-2.66,607.5,4.21,3.11
2021-11-21T01:24:00.000Z,6.50,3.16,-5.24,-2.13,608.5,4.29,3.18
2021-11-21T01:25:00.000Z,6.52,2.49,-5.11,-2.83,607.7,4.23,3.12
2021-11-21T01:26:00.000Z,6.24,1.24,-4.32,-3.93,608.4,4.14,3.06
2021-11-21T01:27:00.000Z,6.28,1.98,-4.70,-3.09,615.4,4.06,3.08
2021-11-21T01:28:00.000Z,6.30,1.80,-4.32,-2.95,615.6,4.06,3.08
2021-11-21T01:29:00.000Z,6.47,3.12,-5.21,-1.56,610.2,4.30,3.20
2021-11-21T01:30:00.000Z,6.23,3.05,-4.76,-1.14,610.2,4.30,3.20
2021-11-21T01:31:00.000Z,6.28,3.62,-4.86,-0.01,606.8,4.21,3.10
2021-11-21T01:32:00.000Z,6.32,3.00,-5.20,-0.85,606.8,4.21,3.10
2021-11-21T01:33:00.000Z,6.53,3.16,-5.46,-1.44,609.5,4.06,3.02
2021-11-21T01:34:00.000Z,6.42,2.16,-5.45,-2.26,610.3,4.02,2.99
2021-11-21T01:35:00.000Z,6.56,2.63,-5.57,-2.08,610.3,4.02,2.99
2021-11-21T01:36:00.000Z,6.59,2.82,-5.51,-2.23,609.3,3.98,2.96
2021-11-21T01:37:00.000Z,6.54,2.82,-5.49,-1.95,611.0,3.97,2.96
2021-11-21T01:38:00.000Z,6.47,3.81,-5.02,1.18,613.2,3.98,2.99
2021-11-21T01:39:00.000Z,6.38,3.76,-4.66,0.31,607.8,4.20,3.10
2021-11-21T01:40:00.000Z,6.03,4.50,-3.64,1.57,607.8,4.20,3.10
2021-11-21T01:41:00.000Z,5.93,4.20,-4.07,0.78,607.9,4.27,3.16
2021-11-21T01:42:00.000Z,6.06,3.57,-4.75,-0.60,613.7,4.37,3.29
2021-11-21T01:43:00.000Z,6.09,2.60,-5.38,-1.07,619.9,4.48,3.44
2021-11-21T01:44:00.000Z,6.14,3.63,-4.80,0.86,619.9,4.48,3.44
2021-11-21T01:45:00.000Z,6.29,3.06,-5.20,-1.17,614.4,4.20,3.17
2021-11-21T01:46:00.000Z,6.54,3.55,-5.23,-1.58,614.4,4.20,3.17
2021-11-21T01:47:00.000Z,6.56,3.00,-5.36,-2.26,99999.9,999.99,99.99
2021-11-21T01:48:00.000Z,6.40,1.95,-5.40,-2.79,614.3,4.12,3.11
2021-11-21T01:49:00.000Z,6.36,2.79,-5.22,-2.16,614.3,4.12,3.11
2021-11-21T01:50:00.000Z,6.19,2.17,-5.01,-2.90,99999.9,999.99,99.99
2021-11-21T01:51:00.000Z,6.26,2.76,-4.94,-2.57,99999.9,999.99,99.99
2021-11-21T01:52:00.000Z,6.33,2.65,-5.38,-1.86,604.5,4.00,2.92
2021-11-21T01:53:00.000Z,6.35,2.97,-5.44,-1.29,604.5,4.00,2.92
2021-11-21T01:54:00.000Z,6.18,2.15,-5.63,-1.26,611.8,4.26,3.19
2021-11-21T01:55:00.000Z,6.27,2.76,-5.36,-1.64,617.3,4.45,3.39
2021-11-21T01:56:00.000Z,6.36,2.73,-5.42,-1.83,617.3,4.45,3.39
2021-11-21T01:57:00.000Z,6.13,2.13,-5.22,-2.24,99999.9,999.99,99.99
2021-11-21T01:58:00.000Z,6.29,2.92,-5.30,-1.15,601.0,4.06,2.93
2021-11-21T01:59:00.000Z,6.60,3.64,-5.38,-0.93,601.0,4.06,2.93
2021-11-21T02:00:00.000Z,6.77,4.37,-5.13,-0.24,603.8,4.37,3.19
2021-11-21T02:01:00.000Z,6.77,4.50,-4.98,-0.28,603.8,4.36,3.18
2021-11-21T02:02:00.000Z,6.75,4.40,-4.65,0.01,605.6,3.80,2.79
2021-11-21T02:03:00.000Z,6.83,5.77,-2.62,2.50,602.3,3.89,2.82
2021-11-21T02:04:00.000Z,6.82,6.05,-1.91,2.49,600.7,3.94,2.84
2021-11-21T02:05:00.000Z,6.79,5.95,-2.16,2.40,601.6,4.22,3.05
2021-11-21T02:06:00.000Z,6.79,5.78,-2.59,2.41,601.6,4.22,3.05
2021-11-21T02:07:00.000Z,6.81,5.73,-2.71,2.48,602.4,4.30,3.12
2021-11-21T02:08:00.000Z,6.82,5.78,-2.59,2.54,602.5,4.32,3.14
2021-11-21T02:09:00.000Z,6.87,6.00,-2.35,2.38,601.1,4.34,3.14
2021-11-21T02:10:00.000Z,6.80,5.92,-2.42,2.28,600.6,4.40,3.17
2021-11-21T02:11:00.000Z,6.78,5.86,-2.42,2.40,601.3,4.58,3.31
2021-11-21T02:12:00.000Z,6.84,6.02,-2.05,2.51,599.0,4.49,3.22
2021-11-21T02:13:00.000Z,6.86,6.06,-1.82,2.64,598.9,4.48,3.21
2021-11-21T02:14:00.000Z,6.88,6.20,-1.91,2.26,598.7,4.47,3.20
2021-11-21T02:15:00.000Z,6.88,6.15,-2.10,2.22,598.5,4.46,3.20
2021-11-21T02:16:00.000Z,6.81,5.73,-2.66,2.49,600.3,4.66,3.36
2021-11-21T02:17:00.000Z,7.02,1.94,-4.87,-1.14,605.4,4.61,3.38
2021-11-21T02:18:00.000Z,7.12,1.90,-4.22,-0.82,619.1,4.02,3.08
2021-11-21T02:19:00.000Z,7.13,1.00,-4.92,-1.62,606.0,3.94,2.89
2021-11-21T02:20:00.000Z,7.23,-0.23,-6.18,-3.74,99999.9,999.99,99.99
2021-11-21T02:21:00.000Z,7.25,-1.00,-6.00,-3.89,99999.9,999.99,99.99
2021-11-21T02:22:00.000Z,7.28,-0.76,-6.18,-3.75,626.7,4.09,3.21
2021-11-21T02:23:00.000Z,7.15,-1.22,-5.73,-4.02,624.1,4.13,3.22
2021-11-21T02:24:00.000Z,7.14,-0.35,-6.10,-3.13,623.2,4.26,3.31
2021-11-21T02:25:00.000Z,7.39,1.64,-6.54,-1.94,623.2,4.27,3.32
2021-11-21T02:26:00.000Z,7.04,2.15,-6.10,-1.68,99999.9,999.99,99.99
2021-11-21T02:27:00.000Z,7.20,1.96,-6.34,-1.98,610.9,3.69,2.75
2021-11-21T02:28:00.000Z,7.34,3.53,-6.12,-0.21,610.6,3.99,2.98
2021-11-21T02:29:00.000Z,7.54,3.42,-6.71,-0.03,616.6,4.14,3.15
2021-11-21T02:30:00.000Z,7.53,2.74,-6.95,-0.92,617.8,4.11,3.14
2021-11-21T02:31:00.000Z,7.51,3.12,-6.61,-1.67,619.7,4.24,3.26
2021-11-21T02:32:00.000Z,7.46,2.65,-6.85,-1.16,619.4,4.18,3.21
2021-11-21T02:33:00.000Z,7.32,2.13,-6.46,-2.59,619.0,3.99,3.06
2021-11-21T02:34:00.000Z,7.43,2.41,-6.84,-1.48,620.0,3.87,2.98
2021-11-21T02:35:00.000Z,7.41,2.62,-6.73,-1.56,620.0,3.87,2.98
2021-11-21T02:36:00.000Z,7.38,2.55,-6.74,-1.52,99999.9,999.99,99.99
2021-11-21T02:37:00.000Z,7.36,2.17,-6.73,-1.94,99999.9,999.99,99.99
2021-11-21T02:38:00.000Z,7.37,2.11,-6.61,-2.39,621.6,4.03,3.11
2021-11-21T02:39:00.000Z,7.28,2.66,-6.60,-1.07,621.6,4.03,3.11
2021-11-21T02:40:00.000Z,7.22,2.84,-6.59,-0.19,99999.9,999.99,99.99
2021-11-21T02:41:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2021-11-21T02:42:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2021-11-21T02:43:00.000Z,7.42,2.33,-6.01,-3.60,99999.9,999.99,99.99
2021-11-21T02:44:00.000Z,7.32,2.22,-6.71,-1.76,624.0,3.85,3.00
2021-11-21T02:45:00.000Z,7.33,2.32,-6.40,-2.21,624.2,3.91,3.05
2021-11-21T02:46:00.000Z,7.25,2.85,-6.48,-1.43,624.4,3.99,3.11
2021-11-21T02:47:00.000Z,7.31,2.36,-6.03,-3.36,99999.9,999.99,99.99
2021-11-21T02:48:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2021-11-21T02:49:00.000Z,7.27,3.39,-6.34,-0.74,99999.9,999.99,99.99
2021-11-21T02:50:00.000Z,7.28,2.88,-6.21,-2.00,99999.9,999.99,99.99
2021-11-21T02:51:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2021-11-21T02:52:00.000Z,7.30,2.34,-6.48,-2.34,99999.9,999.99,99.99
2021-11-21T02:53:00.000Z,7.22,2.98,-6.19,-1.09,595.6,3.17,2.25
2021-11-21T02:54:00.000Z,7.31,3.14,-6.43,-1.16,595.6,3.17,2.25
2021-11-21T02:55:00.000Z,7.35,5.39,-4.35,2.42,595.6,3.17,2.25
2021-11-21T02:56:00.000Z,7.32,5.53,-4.10,2.46,99999.9,999.99,99.99
2021-11-21T02:57:00.000Z,7.16,5.00,-4.94,1.26,99999.9,999.99,99.99
2021-11-21T02:58:00.000Z,7.20,4.68,-5.34,1.09,99999.9,999.99,99.99
2021-11-21T02:59:00.000Z,7.22,4.78,-5.36,0.66,99999.9,999.99,99.99
2021-11-21T03:00:00.000Z,7.36,4.99,-5.40,0.20,600.2,3.56,2.56
2021-11-21T03:01:00.000Z,7.51,5.70,-4.81,0.34,605.9,3.72,2.73
2021-11-21T03:02:00.000Z,7.48,5.36,-5.18,0.14,608.7,3.98,2.95
2021-11-21T03:03:00.000Z,7.45,5.60,-4.88,0.23,597.4,3.70,2.64
2021-11-21T03:04:00.000Z,7.24,6.12,-3.76,0.12,597.2,3.71,2.65
2021-11-21T03:05:00.000Z,7.19,6.05,-3.79,0.11,604.4,3.56,2.60
2021-11-21T03:06:00.000Z,6.51,5.35,-3.18,1.13,623.7,4.15,3.23
2021-11-21T03:07:00.000Z,5.58,4.87,-2.42,0.33,630.0,4.51,3.58
2021-11-21T03:08:00.000Z,5.61,4.22,-3.36,-0.03,641.5,4.93,4.06
2021-11-21T03:09:00.000Z,5.93,3.98,-4.24,-0.06,639.9,4.82,3.95
2021-11-21T03:10:00.000Z,5.58,3.61,-4.06,-0.41,634.9,4.38,3.53
2021-11-21T03:11:00.000Z,5.16,2.63,-4.29,-0.91,622.8,4.07,3.16
2021-11-21T03:12:00.000Z,6.24,2.97,-5.25,-0.68,660.5,4.58,4.00
2021-11-21T03:13:00.000Z,6.62,3.50,-5.52,0.07,653.1,4.25,3.63
2021-11-21T03:14:00.000Z,6.69,3.54,-5.64,-0.19,651.0,4.16,3.53
2021-11-21T03:15:00.000Z,6.71,3.08,-5.95,-0.19,651.0,4.16,3.53
2021-11-21T03:16:00.000Z,6.71,3.50,-5.70,0.01,653.7,4.38,3.74
2021-11-21T03:17:00.000Z,6.69,3.19,-5.86,-0.15,653.7,4.38,3.74
2021-11-21T03:18:00.000Z,6.57,3.13,-5.77,0.27,653.7,4.38,3.74
2021-11-21T03:19:00.000Z,6.68,3.49,-5.67,0.24,645.6,4.23,3.53
2021-11-21T03:20:00.000Z,6.75,3.93,-5.45,0.48,645.6,4.23,3.53
2021-11-21T03:21:00.000Z,6.67,3.98,-5.25,0.81,645.6,4.23,3.53
2021-11-21T03:22:00.000Z,6.74,4.28,-5.11,0.39,645.5,4.21,3.51
2021-11-21T03:23:00.000Z,6.82,4.19,-5.33,-0.16,646.6,4.27,3.57
2021-11-21T03:24:00.000Z,6.70,3.97,-5.34,0.74,644.6,4.28,3.56
2021-11-21T03:25:00.000Z,6.83,4.35,-5.05,1.13,638.6,4.00,3.26
2021-11-21T03:26:00.000Z,6.82,4.40,-4.96,1.49,638.4,3.99,3.25
2021-11-21T03:27:00.000Z,6.77,4.39,-4.91,1.32,632.1,3.46,2.76
2021-11-21T03:28:00.000Z,6.82,4.80,-4.53,1.52,632.1,3.46,2.76
2021-11-21T03:29:00.000Z,6.72,4.16,-4.68,2.41,637.0,3.83,3.11
2021-11-21T03:30:00.000Z,6.64,4.23,-4.40,2.61,637.2,3.85,3.13
2021-11-21T03:31:00.000Z,6.91,4.21,-4.81,2.63,633.7,3.79,3.04
2021-11-21T03:32:00.000Z,7.07,4.20,-5.02,2.64,633.7,3.79,3.04
2021-11-21T03:33:00.000Z,7.02,4.23,-4.64,3.14,633.4,3.70,2.97
2021-11-21T03:34:00.000Z,7.04,4.37,-4.40,3.33,633.4,3.70,2.97
2021-11-21T03:35:00.000Z,6.91,4.20,-4.18,3.51,638.2,3.97,3.23
2021-11-21T03:36:00.000Z,6.72,4.04,-4.05,3.41,638.2,3.97,3.23
2021-11-21T03:37:00.000Z,6.65,4.67,-3.76,2.84,638.2,3.97,3.23
2021-11-21T03:38:00.000Z,6.78,5.01,-3.88,2.34,632.1,3.82,3.05
2021-11-21T03:39:00.000Z,6.91,4.84,-3.81,3.11,632.1,3.82,3.05
2021-11-21T03:40:00.000Z,6.88,4.98,-2.82,3.79,632.1,3.82,3.05
2021-11-21T03:41:00.000Z,6.69,4.88,-3.33,3.10,627.5,4.23,3.33
2021-11-21T03:42:00.000Z,6.68,4.71,-3.55,3.14,627.5,4.23,3.33
2021-11-21T03:43:00.000Z,6.16,4.35,-3.73,2.21,629.6,4.56,3.62
2021-11-21T03:44:00.000Z,6.22,4.73,-3.32,2.23,629.7,4.55,3.61
2021-11-21T03:45:00.000Z,6.02,4.51,-3.18,2.31,631.3,4.44,3.54
2021-11-21T03:46:00.000Z,6.00,4.43,-3.64,1.72,631.3,4.44,3.54
2021-11-21T03:47:00.000Z,6.11,4.46,-3.79,1.74,99999.9,999.99,99.99
2021-11-21T03:48:00.000Z,6.00,4.37,-3.65,1.90,625.6,4.49,3.51
2021-11-21T03:49:00.000Z,5.86,4.22,-3.83,1.35,626.4,4.47,3.51
2021-11-21T03:50:00.000Z,6.08,4.49,-3.96,1.04,631.1,4.42,3.52
2021-11-21T03:51:00.000Z,6.75,4.83,-4.59,1.00,630.7,4.74,3.77
2021-11-21T03:52:00.000Z,7.72,5.72,-5.12,0.56,606.6,3.78,2.78
2021-11-21T03:53:00.000Z,7.82,5.62,-5.29,1.25,605.0,3.57,2.61
2021-11-21T03:54:00.000Z,7.94,5.84,-5.24,1.19,607.8,3.42,2.53
2021-11-21T03:55:00.000Z,7.98,5.78,-5.31,1.49,611.4,3.26,2.44
2021-11-21T03:56:00.000Z,8.04,5.69,-5.48,1.42,610.1,3.30,2.46
2021-11-21T03:57:00.000Z,8.01,5.73,-5.42,1.39,604.9,3.28,2.40
2021-11-21T03:58:00.000Z,8.01,5.74,-5.39,1.45,603.5,3.28,2.39
2021-11-21T03:59:00.000Z,8.01,5.80,-5.32,1.50,601.1,3.39,2.45
2021-11-21T04:00:00.000Z,8.07,6.00,-5.29,0.94,605.9,3.24,2.38
2021-11-21T04:01:00.000Z,8.04,5.88,-5.31,1.29,605.6,3.31,2.43
2021-11-21T04:02:00.000Z,8.11,5.78,-5.58,1.02,600.3,3.58,2.58
2021-11-21T04:03:00.000Z,8.13,5.79,-5.62,0.86,603.6,3.42,2.49
2021-11-21T04:04:00.000Z,8.24,6.00,-5.38,1.60,606.9,3.46,2.55
2021-11-21T04:05:00.000Z,8.16,5.78,-5.31,2.15,602.9,3.20,2.33
2021-11-21T04:06:00.000Z,8.16,5.82,-5.43,1.73,602.7,3.19,2.32
2021-11-21T04:07:00.000Z,8.14,5.80,-5.50,1.52,596.1,3.40,2.42
2021-11-21T04:08:00.000Z,8.17,5.68,-5.49,2.08,596.1,3.40,2.42
2021-11-21T04:09:00.000Z,8.18,5.69,-5.48,2.10,597.5,3.57,2.55
2021-11-21T04:10:00.000Z,8.19,5.72,-5.56,1.85,597.5,3.57,2.55
2021-11-21T04:11:00.000Z,8.18,5.75,-5.48,1.91,596.8,3.53,2.51
2021-11-21T04:12:00.000Z,8.20,5.82,-5.46,1.89,594.1,3.38,2.39
2021-11-21T04:13:00.000Z,8.23,5.84,-5.51,1.81,594.1,3.38,2.39
2021-11-21T04:14:00.000Z,8.25,5.87,-5.50,1.80,592.6,3.61,2.54
2021-11-21T04:15:00.000Z,8.31,5.98,-5.48,1.82,592.6,3.61,2.54
2021-11-21T04:16:00.000Z,8.35,5.98,-5.50,1.90,99999.9,999.99,99.99
2021-11-21T04:17:00.000Z,8.41,5.98,-5.60,1.87,99999.9,999.99,99.99
2021-11-21T04:18:00.000Z,8.35,5.89,-5.67,1.59,99999.9,999.99,99.99
2021-11-21T04:19:00.000Z,8.43,5.84,-5.90,1.44,99999.9,999.99,99.99
2021-11-21T04:20:00.000Z,8.49,5.90,-6.01,1.11,587.6,3.32,2.29
2021-11-21T04:21:00.000Z,8.75,6.11,-6.10,1.43,587.6,3.32,2.29
2021-11-21T04:22:00.000Z,8.79,6.02,-6.32,0.97,583.3,3.40,2.31
2021-11-21T04:23:00.000Z,8.70,5.76,-6.50,-0.03,583.1,3.40,2.31
2021-11-21T04:24:00.000Z,8.80,5.84,-6.47,-0.06,572.6,2.98,1.95
2021-11-21T04:25:00.000Z,8.97,5.70,-6.90,0.30,571.3,2.93,1.91
2021-11-21T04:26:00.000Z,8.84,5.60,-6.80,0.67,567.2,3.18,2.05
2021-11-21T04:27:00.000Z,8.87,5.45,-6.98,0.18,567.9,3.21,2.07
2021-11-21T04:28:00.000Z,8.94,5.96,-6.63,0.60,569.2,3.26,2.11
2021-11-21T04:29:00.000Z,8.91,5.87,-6.69,0.37,569.2,3.26,2.11
2021-11-21T04:30:00.000Z,8.90,5.73,-6.79,0.27,569.1,3.20,2.07
2021-11-21T04:31:00.000Z,8.90,5.61,-6.91,0.09,569.1,3.20,2.07
2021-11-21T04:32:00.000Z,9.04,5.55,-7.12,-0.09,568.6,3.24,2.10
2021-11-21T04:33:00.000Z,9.07,5.98,-6.78,0.44,568.6,3.24,2.10
2021-11-21T04:34:00.000Z,9.11,6.12,-6.71,0.45,99999.9,999.99,99.99
2021-11-21T04:35:00.000Z,9.15,6.15,-6.74,0.62,564.3,3.15,2.01
2021-11-21T04:36:00.000Z,9.20,6.16,-6.79,0.75,564.3,3.15,2.01
2021-11-21T04:37:00.000Z,9.20,6.21,-6.76,0.72,99999.9,999.99,99.99
2021-11-21T04:38:00.000Z,9.14,6.16,-6.70,0.77,99999.9,999.99,99.99
2021-11-21T04:39:00.000Z,9.02,6.10,-6.60,0.80,569.8,3.47,2.25
2021-11-21T04:40:00.000Z,8.96,5.99,-6.63,0.62,569.8,3.47,2.25
2021-11-21T04:41:00.000Z,8.81,5.61,-6.77,0.34,574.9,3.68,2.43
2021-11-21T04:42:00.000Z,8.92,5.52,-6.99,0.35,575.4,3.65,2.42
2021-11-21T04:43:00.000Z,8.85,5.61,-6.83,0.23,574.5,3.60,2.38
2021-11-21T04:44:00.000Z,8.73,5.67,-6.60,0.20,568.2,3.58,2.31
2021-11-21T04:45:00.000Z,8.59,5.62,-6.47,0.00,568.2,3.58,2.31
2021-11-21T04:46:00.000Z,8.40,5.96,-5.75,1.17,577.3,4.11,2.74
2021-11-21T04:47:00.000Z,8.18,5.82,-5.62,0.80,577.3,4.11,2.74
2021-11-21T04:48:00.000Z,8.19,5.79,-5.52,1.74,585.6,4.22,2.89
2021-11-21T04:49:00.000Z,8.17,5.89,-5.43,1.45,586.7,4.23,2.91
2021-11-21T04:50:00.000Z,8.26,5.84,-5.65,1.46,582.5,4.26,2.89
2021-11-21T04:51:00.000Z,8.27,5.97,-5.45,1.74,582.5,4.26,2.89
2021-11-21T04:52:00.000Z,8.30,6.04,-5.26,2.12,99999.9,999.99,99.99
2021-11-21T04:53:00.000Z,8.20,6.16,-4.60,2.78,99999.9,999.99,99.99
2021-11-21T04:54:00.000Z,8.30,6.21,-4.40,3.27,99999.9,999.99,99.99
2021-11-21T04:55:00.000Z,8.42,6.39,-4.75,2.72,99999.9,999.99,99.99
2021-11-21T04:56:00.000Z,8.41,6.36,-4.69,2.88,99999.9,999.99,99.99
2021-11-21T04:57:00.000Z,8.46,6.39,-4.87,2.63,99999.9,999.99,99.99
2021-11-21T04:58:00.000Z,8.41,6.36,-5.00,2.30,99999.9,999.99,99.99
2021-11-21T04:59:00.000Z,8.17,6.18,-4.99,1.88,99999.9,999.99,99.99
2021-11-21T05:00:00.000Z,8.23,6.06,-5.44,0.54,99999.9,999.99,99.99
2021-11-21T05:01:00.000Z,8.47,6.41,-5.33,0.98,588.9,3.78,2.62
2021-11-21T05:02:00.000Z,8.38,6.54,-4.96,1.66,588.9,3.78,2.62
2021-11-21T05:03:00.000Z,8.46,6.65,-4.73,2.22,99999.9,999.99,99.99
2021-11-21T05:04:00.000Z,8.51,6.69,-4.60,2.51,99999.9,999.99,99.99
2021-11-21T05:05:00.000Z,8.46,7.03,-4.12,2.19,588.9,4.01,2.78
2021-11-21T05:06:00.000Z,8.08,6.62,-2.78,3.08,588.9,4.01,2.78
2021-11-21T05:07:00.000Z,8.12,6.71,-2.54,3.38,588.9,4.01,2.78
2021-11-21T05:08:00.000Z,8.48,7.15,-3.91,2.13,99999.9,999.99,99.99
2021-11-21T05:09:00.000Z,8.28,7.24,-2.07,3.06,99999.9,999.99,99.99
2021-11-21T05:10:00.000Z,8.06,7.09,-0.42,3.72,99999.9,999.99,99.99
2021-11-21T05:11:00.000Z,7.96,6.85,-0.12,3.98,596.8,4.07,2.90
2021-11-21T05:12:00.000Z,7.84,6.59,-0.18,4.02,597.7,4.07,2.91
2021-11-21T05:13:00.000Z,8.09,5.68,1.00,5.25,599.1,4.05,2.91

,time,F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure
0,2021-11-21T00:00:00.000Z,4.79,1.87,-2.40,-3.37,99999.9,999.99,99.99
1,2021-11-21T00:01:00.000Z,5.73,4.25,0.29,2.60,99999.9,999.99,99.99
2,2021-11-21T00:02:00.000Z,4.90,1.72,-3.04,-3.39,583.6,4.70,3.20
3,2021-11-21T00:03:00.000Z,4.92,2.03,-3.04,-3.23,583.6,4.70,3.20
4,2021-11-21T00:04:00.000Z,5.00,1.68,-2.93,-3.67,583.6,4.70,3.20
...,...,...,...,...,...,...,...,...
1435,2021-11-21T23:55:00.000Z,3.69,2.28,-2.76,0.48,612.4,2.33,1.75
1436,2021-11-21T23:56:00.000Z,3.76,1.76,-3.15,0.31,619.3,2.45,1.88
1437,2021-11-21T23:57:00.000Z,3.75,-0.65,-3.07,-1.14,635.0,2.35,1.90
1438,2021-11-21T23:58:00.000Z,3.95,-1.41,-3.01,-2.11,643.1,2.31,1.91
1439,2021-11-21T23:59:00.000Z,3.93,-1.73,-2.52,-2.38,640.5,2.38,1.95

#### Fail: no data in time range

In [51]:
fetch_data_omni_hro2_1min(
    start_utc="1500-11-21T00:00:00Z",
    end_utc="1501-11-22T00:00:00Z"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
{
"HAPI": "2.0",
"status": {"code": 1201, "message": "OK - no data for time range"}
}

Request succeeded.

ParserError: Error tokenizing data. C error: Expected 1 fields in line 2, saw 2

In [73]:
# stopDate for omni_hro2_1min is 2026-04-13
fetch_data_omni_hro2_1min(
    start_utc="2026-07-01T00:00:00Z",
    end_utc="2026-07-02T00:00:00Z"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
{
"HAPI": "2.0",
"status": {"code": 1201, "message": "OK - no data for time range"}
}

Request succeeded.

ParserError: Error tokenizing data. C error: Expected 1 fields in line 2, saw 2

#### Fail: incorrect variable name

In [52]:
fetch_data_omni_hro2_1min(
    start_utc="1500-11-21T00:00:00Z",
    end_utc="1501-11-22T00:00:00Z",
    vars="unknown_variable_name,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
{
"HAPI": "2.0",
"status": {"code": 1407, "message": "Bad request - unknown dataset parameter"}}

HTTPError: 400 Client Error: 400 for url: https://cdaweb.gsfc.nasa.gov/hapi/data?id=OMNI_HRO2_1MIN&time.min=1500-11-21T00%3A00%3A00Z&time.max=1501-11-22T00%3A00%3A00Z&parameters=unknown_variable_name%2CBX_GSE%2CBY_GSM%2CBZ_GSM%2Cflow_speed%2Cproton_density%2CPressure

#### (Potential edge case) Partial overlap of time range

In [75]:
fetch_data_omni_hro2_1min(
    start_utc="2026-04-13T00:00:00Z",
    end_utc="2026-04-16T00:00:00Z",
    vars="F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
2026-04-13T00:00:00.000Z,4.47,-3.07,-1.13,2.88,464.3,3.54,1.53
2026-04-13T00:01:00.000Z,4.41,-3.08,-1.65,2.64,464.4,3.54,1.53
2026-04-13T00:02:00.000Z,4.47,-3.17,-0.93,2.90,99999.9,999.99,99.99
2026-04-13T00:03:00.000Z,4.49,-2.98,-1.52,2.95,465.4,3.15,1.36
2026-04-13T00:04:00.000Z,4.49,-3.20,-0.85,2.99,465.4,3.15,1.36
2026-04-13T00:05:00.000Z,4.47,-2.88,-1.60,2.98,465.0,3.33,1.44
2026-04-13T00:06:00.000Z,4.44,-3.15,0.38,2.98,465.0,3.33,1.44
2026-04-13T00:07:00.000Z,4.45,-3.20,0.65,3.02,465.0,3.33,1.44
2026-04-13T00:08:00.000Z,4.50,-2.51,2.94,2.22,99999.9,999.99,99.99
2026-04-13T00:09:00.000Z,4.48,-2.25,2.98,2.40,468.4,2.75,1.21
2026-04-13T00:10:00.000Z,4.60,-2.83,-0.47,3.33,468.4,2.75,1.21
2026-04-13T00:11:00.000Z,4.53,-2.97,0.14,3.05,468.4,2.75,1.21
2026-04-13T00:12:00.000Z,4.61,-2.78,-1.48,3.37,99999.9,999.99,99.99
2026-04-13T00:13:00.000Z,4.56,-3.25,-0.34,2.94,464.1,3.31,1.43
2026-04-13T00:14:00.000Z,4.53,-3.52,0.33,2.59,464.1,3.31,1.43
2026-04-13T00:15:00.000Z,4.52,-2.41,-1.17,2.72,458.4,3.19,1.34
2026-04-13T00:16:00.000Z,4.53,-2.75,-1.16,2.85,456.5,3.13,1.30
2026-04-13T00:17:00.000Z,4.53,-3.37,-1.18,2.62,459.4,3.17,1.34
2026-04-13T00:18:00.000Z,4.59,-3.10,-0.50,3.07,99999.9,999.99,99.99
2026-04-13T00:19:00.000Z,4.58,-3.26,-0.40,2.99,99999.9,999.99,99.99
2026-04-13T00:20:00.000Z,4.58,-2.89,-0.88,3.05,458.0,3.05,1.28
2026-04-13T00:21:00.000Z,4.59,-3.09,-0.53,3.09,467.3,3.15,1.38
2026-04-13T00:22:00.000Z,4.59,-3.06,-0.03,3.20,465.9,3.45,1.50
2026-04-13T00:23:00.000Z,4.55,-2.87,0.03,3.23,462.6,3.35,1.43
2026-04-13T00:24:00.000Z,4.55,-2.94,0.45,2.96,458.1,3.21,1.35
2026-04-13T00:25:00.000Z,4.60,-2.79,0.83,3.26,99999.9,999.99,99.99
2026-04-13T00:26:00.000Z,4.63,-3.21,0.59,2.76,461.8,3.25,1.39
2026-04-13T00:27:00.000Z,4.57,-2.39,1.81,3.18,461.8,3.25,1.39
2026-04-13T00:28:00.000Z,4.59,-2.63,0.07,2.93,483.1,3.45,1.61
2026-04-13T00:29:00.000Z,4.57,-2.22,-0.94,2.78,483.1,3.45,1.61
2026-04-13T00:30:00.000Z,4.59,-2.13,-0.58,2.89,99999.9,999.99,99.99
2026-04-13T00:31:00.000Z,4.62,-2.25,-0.08,3.13,99999.9,999.99,99.99
2026-04-13T00:32:00.000Z,4.60,-2.37,0.86,3.06,465.5,2.55,1.11
2026-04-13T00:33:00.000Z,4.56,-1.06,2.31,2.73,473.9,3.12,1.40
2026-04-13T00:34:00.000Z,4.52,-1.78,0.75,2.86,485.7,3.10,1.46
2026-04-13T00:35:00.000Z,4.57,-2.23,-1.02,2.79,479.0,3.57,1.64
2026-04-13T00:36:00.000Z,4.58,-1.74,-0.97,3.56,480.9,3.12,1.44
2026-04-13T00:37:00.000Z,4.59,-2.39,-0.28,3.41,472.9,3.32,1.48
2026-04-13T00:38:00.000Z,4.60,-2.35,-0.07,3.23,466.7,3.33,1.45
2026-04-13T00:39:00.000Z,4.59,-3.07,1.22,2.69,464.1,3.30,1.42
2026-04-13T00:40:00.000Z,4.60,-3.00,0.78,2.40,458.7,3.24,1.36
2026-04-13T00:41:00.000Z,4.57,-3.38,1.34,2.21,99999.9,999.99,99.99
2026-04-13T00:42:00.000Z,4.60,-3.32,0.32,2.72,99999.9,999.99,99.99
2026-04-13T00:43:00.000Z,4.63,-3.39,-0.05,2.99,99999.9,999.99,99.99
2026-04-13T00:44:00.000Z,4.62,-2.82,0.16,3.26,99999.9,999.99,99.99
2026-04-13T00:45:00.000Z,4.69,-3.68,1.07,2.69,99999.9,999.99,99.99
2026-04-13T00:46:00.000Z,4.62,-3.18,0.23,3.05,99999.9,999.99,99.99
2026-04-13T00:47:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T00:48:00.000Z,4.52,-2.59,-1.19,3.48,470.1,3.28,1.45
2026-04-13T00:49:00.000Z,4.54,-2.04,-1.70,3.67,470.1,3.28,1.45
2026-04-13T00:50:00.000Z,9999.99,9999.99,9999.99,9999.99,470.1,3.28,1.45
2026-04-13T00:51:00.000Z,4.52,-2.22,-1.48,3.61,99999.9,999.99,99.99
2026-04-13T00:52:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T00:53:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T00:54:00.000Z,4.53,-2.42,-1.74,3.37,465.8,3.26,1.41
2026-04-13T00:55:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T00:56:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T00:57:00.000Z,4.54,-2.33,-1.46,3.57,99999.9,999.99,99.99
2026-04-13T00:58:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T00:59:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:00:00.000Z,4.54,-2.39,-1.54,3.53,99999.9,999.99,99.99
2026-04-13T01:01:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:02:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:03:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:04:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:05:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:06:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:07:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:08:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:09:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:10:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:11:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:12:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:13:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
2026-04-13T01:14:00.000Z,4.62,-2.51,-0.50,3.80,99999.9,999.99,99.99
2026-04-13T01:15:00.000Z,4.65,-3.71,0.52,2.72,99999.9,999.99,99.99

Request succeeded.

,time,F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure
0,2026-04-13T00:00:00.000Z,4.47,-3.07,-1.13,2.88,464.3,3.54,1.53
1,2026-04-13T00:01:00.000Z,4.41,-3.08,-1.65,2.64,464.4,3.54,1.53
2,2026-04-13T00:02:00.000Z,4.47,-3.17,-0.93,2.90,99999.9,999.99,99.99
3,2026-04-13T00:03:00.000Z,4.49,-2.98,-1.52,2.95,465.4,3.15,1.36
4,2026-04-13T00:04:00.000Z,4.49,-3.20,-0.85,2.99,465.4,3.15,1.36
...,...,...,...,...,...,...,...,...
71,2026-04-13T01:11:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
72,2026-04-13T01:12:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
73,2026-04-13T01:13:00.000Z,9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99
74,2026-04-13T01:14:00.000Z,4.62,-2.51,-0.50,3.80,99999.9,999.99,99.99
75,2026-04-13T01:15:00.000Z,4.65,-3.71,0.52,2.72,99999.9,999.99,99.99

### Return json

#### Success

In [19]:
# success
json_data_success = fetch_data_omni_hro2_1min(
    start_utc="2021-11-21T00:00:00Z",
    end_utc="2021-11-22T00:00:00Z",
    format='json',
    vars="F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
{
"HAPI": "2.0",
"status": {"code": 1200, "message": "OK"},
"format": "json",
"parameters": [
{
"name": "Time",
"type": "isotime",
"units": "UTC",
"length":24,
"fill": null
},
{
"name": "F",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)"
},
{
"name": "BX_GSE",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bx (nT), GSE"
},
{
"name": "BY_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "By (nT), GSM, determined from post-shift GSE components"
},
{
"name": "BZ_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bz (nT), GSM, determined from post-shift GSE components"
},
{
"name": "flow_speed",
"type": "double",
"units": "km/s",
"fill": "99999.9",
"description": "Flow Speed (km/s), GSE"
},
{
"name": "proton_density",
"type": "double",
"units": "n/cc",
"fill": "999.99",
"description": "Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)"
},
{
"name": "Pressure",
"type": "double",
"units": "nPa",
"fill": "99.99",
"description": "Flow pressure (nPa)"
}
],
"data":[
["2021-11-21T00:00:00.000Z",4.79,1.87,-2.40,-3.37,99999.9,999.99,99.99],
["2021-11-21T00:01:00.000Z",5.73,4.25,0.29,2.60,99999.9,999.99,99.99],
["2021-11-21T00:02:00.000Z",4.90,1.72,-3.04,-3.39,583.6,4.70,3.20],
["2021-11-21T00:03:00.000Z",4.92,2.03,-3.04,-3.23,583.6,4.70,3.20],
["2021-11-21T00:04:00.000Z",5.00,1.68,-2.93,-3.67,583.6,4.70,3.20],
["2021-11-21T00:05:00.000Z",5.09,1.65,-3.44,-3.23,583.0,4.62,3.14],
["2021-11-21T00:06:00.000Z",5.13,1.61,-3.50,-3.36,583.0,4.62,3.14],
["2021-11-21T00:07:00.000Z",5.57,3.56,-0.86,0.89,574.7,4.18,2.76],
["2021-11-21T00:08:00.000Z",5.64,3.86,0.77,2.73,574.5,4.19,2.77],
["2021-11-21T00:09:00.000Z",5.35,4.26,-0.27,1.52,568.1,4.37,2.82],
["2021-11-21T00:10:00.000Z",5.46,4.09,-0.17,1.75,569.0,4.36,2.82],
["2021-11-21T00:11:00.000Z",5.36,3.95,-0.69,0.85,569.3,4.35,2.82],
["2021-11-21T00:12:00.000Z",5.34,4.09,-0.32,1.00,578.4,4.73,3.16],
["2021-11-21T00:13:00.000Z",5.20,3.99,-0.29,0.88,574.5,4.53,2.99],
["2021-11-21T00:14:00.000Z",5.08,3.89,-0.34,1.14,99999.9,999.99,99.99],
["2021-11-21T00:15:00.000Z",4.99,4.03,-0.08,1.19,570.2,4.22,2.74],
["2021-11-21T00:16:00.000Z",5.16,2.35,-2.30,-1.21,577.6,4.36,2.91],
["2021-11-21T00:17:00.000Z",4.86,2.52,-2.02,-1.65,583.4,4.93,3.36],
["2021-11-21T00:18:00.000Z",5.15,2.73,-2.16,-1.91,576.6,4.46,2.97],
["2021-11-21T00:19:00.000Z",5.06,3.02,-1.64,-0.80,583.4,4.73,3.22],
["2021-11-21T00:20:00.000Z",5.14,3.87,-0.92,0.49,575.8,4.56,3.02],
["2021-11-21T00:21:00.000Z",4.90,3.28,-2.01,-0.46,575.0,4.53,3.00],
["2021-11-21T00:22:00.000Z",5.19,3.83,0.08,0.52,573.3,4.48,2.94],
["2021-11-21T00:23:00.000Z",5.21,3.64,-0.28,0.37,572.8,4.46,2.93],
["2021-11-21T00:24:00.000Z",5.44,3.98,-0.15,1.33,578.9,4.61,3.09],
["2021-11-21T00:25:00.000Z",5.61,4.14,0.50,2.51,576.7,4.63,3.08],
["2021-11-21T00:26:00.000Z",5.78,3.93,1.36,3.76,574.7,4.66,3.08],
["2021-11-21T00:27:00.000Z",5.53,3.77,1.16,2.08,576.6,4.51,3.00],
["2021-11-21T00:28:00.000Z",5.63,4.03,1.15,2.38,576.6,4.51,3.00],
["2021-11-21T00:29:00.000Z",5.62,4.23,0.92,2.05,572.9,4.35,2.86],
["2021-11-21T00:30:00.000Z",6.06,4.62,1.47,3.64,572.7,4.34,2.85],
["2021-11-21T00:31:00.000Z",5.66,4.43,1.32,1.84,570.5,4.21,2.74],
["2021-11-21T00:32:00.000Z",5.67,4.35,1.33,1.64,570.5,4.21,2.74],
["2021-11-21T00:33:00.000Z",5.63,4.31,0.72,1.46,579.2,4.65,3.12],
["2021-11-21T00:34:00.000Z",5.39,4.28,1.38,2.79,583.2,4.68,3.18],
["2021-11-21T00:35:00.000Z",4.73,3.52,0.51,0.61,584.6,4.57,3.12],
["2021-11-21T00:36:00.000Z",4.70,3.63,0.32,0.40,99999.9,999.99,99.99],
["2021-11-21T00:37:00.000Z",5.27,4.81,0.43,1.67,575.5,4.18,2.77],
["2021-11-21T00:38:00.000Z",5.02,4.80,-0.45,1.00,579.2,4.32,2.90],
["2021-11-21T00:39:00.000Z",4.07,3.34,-1.18,-1.04,584.9,4.55,3.11],
["2021-11-21T00:40:00.000Z",3.95,3.57,-1.43,-0.11,582.4,4.56,3.09],
["2021-11-21T00:41:00.000Z",5.00,4.32,-2.19,0.20,581.5,4.46,3.02],
["2021-11-21T00:42:00.000Z",5.10,4.26,-1.85,1.01,585.7,4.78,3.28],
["2021-11-21T00:43:00.000Z",4.61,3.45,-2.59,-0.70,584.4,4.79,3.27],
["2021-11-21T00:44:00.000Z",5.07,4.30,-2.14,1.21,583.8,4.00,2.73],
["2021-11-21T00:45:00.000Z",5.05,4.41,-1.84,1.08,582.0,3.97,2.69],
["2021-11-21T00:46:00.000Z",4.18,3.31,-2.45,-0.06,583.0,4.61,3.13],
["2021-11-21T00:47:00.000Z",4.46,3.37,-2.88,-0.34,582.6,4.77,3.24],
["2021-11-21T00:48:00.000Z",4.33,2.28,-2.95,-1.84,582.1,4.96,3.36],
["2021-11-21T00:49:00.000Z",4.16,2.84,-2.49,-1.37,592.9,4.98,3.50],
["2021-11-21T00:50:00.000Z",4.23,2.74,-2.65,-1.10,592.9,4.98,3.50],
["2021-11-21T00:51:00.000Z",4.47,1.57,-3.61,-0.69,592.9,4.98,3.50],
["2021-11-21T00:52:00.000Z",4.52,1.47,-3.36,-1.87,590.7,4.36,3.04],
["2021-11-21T00:53:00.000Z",5.04,2.20,-3.75,-1.07,590.9,4.64,3.24],
["2021-11-21T00:54:00.000Z",5.22,2.45,-4.15,0.39,591.0,4.88,3.41],
["2021-11-21T00:55:00.000Z",4.94,1.86,-3.72,-1.99,99999.9,999.99,99.99],
["2021-11-21T00:56:00.000Z",5.20,2.53,-4.08,-1.62,99999.9,999.99,99.99],
["2021-11-21T00:57:00.000Z",5.32,2.95,-4.12,-1.38,587.9,4.28,2.96],
["2021-11-21T00:58:00.000Z",5.76,2.79,-4.12,-2.77,586.1,4.43,3.04],
["2021-11-21T00:59:00.000Z",5.54,3.45,-4.06,-1.48,581.5,4.70,3.18],
["2021-11-21T01:00:00.000Z",5.74,2.56,-3.74,-3.29,595.6,3.99,2.83],
["2021-11-21T01:01:00.000Z",5.83,3.03,-3.41,-3.55,595.6,3.99,2.83],
["2021-11-21T01:02:00.000Z",5.64,2.42,-3.55,-3.58,599.1,4.43,3.18],
["2021-11-21T01:03:00.000Z",5.45,1.61,-3.68,-3.65,600.8,4.65,3.36],
["2021-11-21T01:04:00.000Z",5.54,1.76,-3.77,-3.58,595.8,4.25,3.02],
["2021-11-21T01:05:00.000Z",5.28,2.57,-3.14,-3.26,595.8,4.25,3.02],
["2021-11-21T01:06:00.000Z",5.61,2.18,-4.29,-2.78,595.8,4.25,3.02],
["2021-11-21T01:07:00.000Z",5.50,2.30,-4.48,-2.20,599.5,4.29,3.08],
["2021-11-21T01:08:00.000Z",5.48,2.22,-4.41,-2.32,599.5,4.29,3.08],
["2021-11-21T01:09:00.000Z",5.48,2.22,-4.42,-2.32,99999.9,999.99,99.99],
["2021-11-21T01:10:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2021-11-21T01:11:00.000Z",5.53,2.32,-4.33,-2.55,99999.9,999.99,99.99],
["2021-11-21T01:12:00.000Z",5.43,2.19,-4.25,-2.56,99999.9,999.99,99.99],
["2021-11-21T01:13:00.000Z",5.32,1.96,-4.03,-2.86,99999.9,999.99,99.99],
["2021-11-21T01:14:00.000Z",5.40,2.04,-4.12,-2.80,99999.9,999.99,99.99],
["2021-11-21T01:15:00.000Z",6.02,1.30,-4.56,-3.70,609.8,4.32,3.21],
["2021-11-21T01:16:00.000Z",5.97,1.51,-4.40,-3.65,610.8,4.23,3.16],
["2021-11-21T01:17:00.000Z",5.88,1.72,-4.43,-3.25,605.6,4.22,3.10],
["2021-11-21T01:18:00.000Z",5.97,2.36,-4.45,-3.05,599.0,4.32,3.10],
["2021-11-21T01:19:00.000Z",5.97,2.61,-4.60,-2.61,600.4,4.21,3.04],
["2021-11-21T01:20:00.000Z",5.97,2.16,-4.49,-3.18,600.4,4.21,3.04],
["2021-11-21T01:21:00.000Z",6.21,2.80,-4.73,-2.87,605.3,4.35,3.19],
["2021-11-21T01:22:00.000Z",6.46,2.51,-5.11,-2.94,605.7,4.27,3.13],
["2021-11-21T01:23:00.000Z",6.39,2.76,-5.04,-2.66,607.5,4.21,3.11],
["2021-11-21T01:24:00.000Z",6.50,3.16,-5.24,-2.13,608.5,4.29,3.18],
["2021-11-21T01:25:00.000Z",6.52,2.49,-5.11,-2.83,607.7,4.23,3.12],
["2021-11-21T01:26:00.000Z",6.24,1.24,-4.32,-3.93,608.4,4.14,3.06],
["2021-11-21T01:27:00.000Z",6.28,1.98,-4.70,-3.09,615.4,4.06,3.08],
["2021-11-21T01:28:00.000Z",6.30,1.80,-4.32,-2.95,615.6,4.06,3.08],
["2021-11-21T01:29:00.000Z",6.47,3.12,-5.21,-1.56,610.2,4.30,3.20],
["2021-11-21T01:30:00.000Z",6.23,3.05,-4.76,-1.14,610.2,4.30,3.20],
["2021-11-21T01:31:00.000Z",6.28,3.62,-4.86,-0.01,606.8,4.21,3.10],
["2021-11-21T01:32:00.000Z",6.32,3.00,-5.20,-0.85,606.8,4.21,3.10],
["2021-11-21T01:33:00.000Z",6.53,3.16,-5.46,-1.44,609.5,4.06,3.02],
["2021-11-21T01:34:00.000Z",6.42,2.16,-5.45,-2.26,610.3,4.02,2.99],
["2021-11-21T01:35:00.000Z",6.56,2.63,-5.57,-2.08,610.3,4.02,2.99],
["2021-11-21T01:36:00.000Z",6.59,2.82,-5.51,-2.23,609.3,3.98,2.96],
["2021-11-21T01:37:00.000Z",6.54,2.82,-5.49,-1.95,611.0,3.97,2.96],
["2021-11-21T01:38:00.000Z",6.47,3.81,-5.02,1.18,613.2,3.98,2.99],
["2021-11-21T01:39:00.000Z",6.38,3.76,-4.66,0.31,607.8,4.20,3.10],
["2021-11-21T01:40:00.000Z",6.03,4.50,-3.64,1.57,607.8,4.20,3.10],
["2021-11-21T01:41:00.000Z",5.93,4.20,-4.07,0.78,607.9,4.27,3.16],
["2021-11-21T01:42:00.000Z",6.06,3.57,-4.75,-0.60,613.7,4.37,3.29],
["2021-11-21T01:43:00.000Z",6.09,2.60,-5.38,-1.07,619.9,4.48,3.44],
["2021-11-21T01:44:00.000Z",6.14,3.63,-4.80,0.86,619.9,4.48,3.44],
["2021-11-21T01:45:00.000Z",6.29,3.06,-5.20,-1.17,614.4,4.20,3.17],
["2021-11-21T01:46:00.000Z",6.54,3.55,-5.23,-1.58,614.4,4.20,3.17],
["2021-11-21T01:47:00.000Z",6.56,3.00,-5.36,-2.26,99999.9,999.99,99.99],
["2021-11-21T01:48:00.000Z",6.40,1.95,-5.40,-2.79,614.3,4.12,3.11],
["2021-11-21T01:49:00.000Z",6.36,2.79,-5.22,-2.16,614.3,4.12,3.11],
["2021-11-21T01:50:00.000Z",6.19,2.17,-5.01,-2.90,99999.9,999.99,99.99],
["2021-11-21T01:51:00.000Z",6.26,2.76,-4.94,-2.57,99999.9,999.99,99.99],
["2021-11-21T01:52:00.000Z",6.33,2.65,-5.38,-1.86,604.5,4.00,2.92],
["2021-11-21T01:53:00.000Z",6.35,2.97,-5.44,-1.29,604.5,4.00,2.92],
["2021-11-21T01:54:00.000Z",6.18,2.15,-5.63,-1.26,611.8,4.26,3.19],
["2021-11-21T01:55:00.000Z",6.27,2.76,-5.36,-1.64,617.3,4.45,3.39],
["2021-11-21T01:56:00.000Z",6.36,2.73,-5.42,-1.83,617.3,4.45,3.39],
["2021-11-21T01:57:00.000Z",6.13,2.13,-5.22,-2.24,99999.9,999.99,99.99],
["2021-11-21T01:58:00.000Z",6.29,2.92,-5.30,-1.15,601.0,4.06,2.93],
["2021-11-21T01:59:00.000Z",6.60,3.64,-5.38,-0.93,601.0,4.06,2.93],
["2021-11-21T02:00:00.000Z",6.77,4.37,-5.13,-0.24,603.8,4.37,3.19],
["2021-11-21T02:01:00.000Z",6.77,4.50,-4.98,-0.28,603.8,4.36,3.18],
["2021-11-21T02:02:00.000Z",6.75,4.40,-4.65,0.01,605.6,3.80,2.79],
["2021-11-21T02:03:00.000Z",6.83,5.77,-2.62,2.50,602.3,3.89,2.82],
["2021-11-21T02:04:00.000Z",6.82,6.05,-1.91,2.49,600.7,3.94,2.84],
["2021-11-21T02:05:00.000Z",6.79,5.95,-2.16,2.40,601.6,4.22,3.05],
["2021-11-21T02:06:00.000Z",6.79,5.78,-2.59,2.41,601.6,4.22,3.05],
["2021-11-21T02:07:00.000Z",6.81,5.73,-2.71,2.48,602.4,4.30,3.12],
["2021-11-21T02:08:00.000Z",6.82,5.78,-2.59,2.54,602.5,4.32,3.14],
["2021-11-21T02:09:00.000Z",6.87,6.00,-2.35,2.38,601.1,4.34,3.14],
["2021-11-21T02:10:00.000Z",6.80,5.92,-2.42,2.28,600.6,4.40,3.17],
["2021-11-21T02:11:00.000Z",6.78,5.86,-2.42,2.40,601.3,4.58,3.31],
["2021-11-21T02:12:00.000Z",6.84,6.02,-2.05,2.51,599.0,4.49,3.22],
["2021-11-21T02:13:00.000Z",6.86,6.06,-1.82,2.64,598.9,4.48,3.21],
["2021-11-21T02:14:00.000Z",6.88,6.20,-1.91,2.26,598.7,4.47,3.20],
["2021-11-21T02:15:00.000Z",6.88,6.15,-2.10,2.22,598.5,4.46,3.20],
["2021-11-21T02:16:00.000Z",6.81,5.73,-2.66,2.49,600.3,4.66,3.36],
["2021-11-21T02:17:00.000Z",7.02,1.94,-4.87,-1.14,605.4,4.61,3.38],
["2021-11-21T02:18:00.000Z",7.12,1.90,-4.22,-0.82,619.1,4.02,3.08],
["2021-11-21T02:19:00.000Z",7.13,1.00,-4.92,-1.62,606.0,3.94,2.89],
["2021-11-21T02:20:00.000Z",7.23,-0.23,-6.18,-3.74,99999.9,999.99,99.99],
["2021-11-21T02:21:00.000Z",7.25,-1.00,-6.00,-3.89,99999.9,999.99,99.99],
["2021-11-21T02:22:00.000Z",7.28,-0.76,-6.18,-3.75,626.7,4.09,3.21],
["2021-11-21T02:23:00.000Z",7.15,-1.22,-5.73,-4.02,624.1,4.13,3.22],
["2021-11-21T02:24:00.000Z",7.14,-0.35,-6.10,-3.13,623.2,4.26,3.31],
["2021-11-21T02:25:00.000Z",7.39,1.64,-6.54,-1.94,623.2,4.27,3.32],
["2021-11-21T02:26:00.000Z",7.04,2.15,-6.10,-1.68,99999.9,999.99,99.99],
["2021-11-21T02:27:00.000Z",7.20,1.96,-6.34,-1.98,610.9,3.69,2.75],
["2021-11-21T02:28:00.000Z",7.34,3.53,-6.12,-0.21,610.6,3.99,2.98],
["2021-11-21T02:29:00.000Z",7.54,3.42,-6.71,-0.03,616.6,4.14,3.15],
["2021-11-21T02:30:00.000Z",7.53,2.74,-6.95,-0.92,617.8,4.11,3.14],
["2021-11-21T02:31:00.000Z",7.51,3.12,-6.61,-1.67,619.7,4.24,3.26],
["2021-11-21T02:32:00.000Z",7.46,2.65,-6.85,-1.16,619.4,4.18,3.21],
["2021-11-21T02:33:00.000Z",7.32,2.13,-6.46,-2.59,619.0,3.99,3.06],
["2021-11-21T02:34:00.000Z",7.43,2.41,-6.84,-1.48,620.0,3.87,2.98],
["2021-11-21T02:35:00.000Z",7.41,2.62,-6.73,-1.56,620.0,3.87,2.98],
["2021-11-21T02:36:00.000Z",7.38,2.55,-6.74,-1.52,99999.9,999.99,99.99],
["2021-11-21T02:37:00.000Z",7.36,2.17,-6.73,-1.94,99999.9,999.99,99.99],
["2021-11-21T02:38:00.000Z",7.37,2.11,-6.61,-2.39,621.6,4.03,3.11],
["2021-11-21T02:39:00.000Z",7.28,2.66,-6.60,-1.07,621.6,4.03,3.11],
["2021-11-21T02:40:00.000Z",7.22,2.84,-6.59,-0.19,99999.9,999.99,99.99],
["2021-11-21T02:41:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2021-11-21T02:42:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2021-11-21T02:43:00.000Z",7.42,2.33,-6.01,-3.60,99999.9,999.99,99.99],
["2021-11-21T02:44:00.000Z",7.32,2.22,-6.71,-1.76,624.0,3.85,3.00],
["2021-11-21T02:45:00.000Z",7.33,2.32,-6.40,-2.21,624.2,3.91,3.05],
["2021-11-21T02:46:00.000Z",7.25,2.85,-6.48,-1.43,624.4,3.99,3.11],
["2021-11-21T02:47:00.000Z",7.31,2.36,-6.03,-3.36,99999.9,999.99,99.99],
["2021-11-21T02:48:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2021-11-21T02:49:00.000Z",7.27,3.39,-6.34,-0.74,99999.9,999.99,99.99],
["2021-11-21T02:50:00.000Z",7.28,2.88,-6.21,-2.00,99999.9,999.99,99.99],
["2021-11-21T02:51:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2021-11-21T02:52:00.000Z",7.30,2.34,-6.48,-2.34,99999.9,999.99,99.99],
["2021-11-21T02:53:00.000Z",7.22,2.98,-6.19,-1.09,595.6,3.17,2.25],
["2021-11-21T02:54:00.000Z",7.31,3.14,-6.43,-1.16,595.6,3.17,2.25],
["2021-11-21T02:55:00.000Z",7.35,5.39,-4.35,2.42,595.6,3.17,2.25],
["2021-11-21T02:56:00.000Z",7.32,5.53,-4.10,2.46,99999.9,999.99,99.99],
["2021-11-21T02:57:00.000Z",7.16,5.00,-4.94,1.26,99999.9,999.99,99.99],
["2021-11-21T02:58:00.000Z",7.20,4.68,-5.34,1.09,99999.9,999.99,99.99],
["2021-11-21T02:59:00.000Z",7.22,4.78,-5.36,0.66,99999.9,999.99,99.99],
["2021-11-21T03:00:00.000Z",7.36,4.99,-5.40,0.20,600.2,3.56,2.56],
["2021-11-21T03:01:00.000Z",7.51,5.70,-4.81,0.34,605.9,3.72,2.73],
["2021-11-21T03:02:00.000Z",7.48,5.36,-5.18,0.14,608.7,3.98,2.95],
["2021-11-21T03:03:00.000Z",7.45,5.60,-4.88,0.23,597.4,3.70,2.64],
["2021-11-21T03:04:00.000Z",7.24,6.12,-3.76,0.12,597.2,3.71,2.65],
["2021-11-21T03:05:00.000Z",7.19,6.05,-3.79,0.11,604.4,3.56,2.60],
["2021-11-21T03:06:00.000Z",6.51,5.35,-3.18,1.13,623.7,4.15,3.23],
["2021-11-21T03:07:00.000Z",5.58,4.87,-2.42,0.33,630.0,4.51,3.58],
["2021-11-21T03:08:00.000Z",5.61,4.22,-3.36,-0.03,641.5,4.93,4.06],
["2021-11-21T03:09:00.000Z",5.93,3.98,-4.24,-0.06,639.9,4.82,3.95],
["2021-11-21T03:10:00.000Z",5.58,3.61,-4.06,-0.41,634.9,4.38,3.53],
["2021-11-21T03:11:00.000Z",5.16,2.63,-4.29,-0.91,622.8,4.07,3.16],
["2021-11-21T03:12:00.000Z",6.24,2.97,-5.25,-0.68,660.5,4.58,4.00],
["2021-11-21T03:13:00.000Z",6.62,3.50,-5.52,0.07,653.1,4.25,3.63],
["2021-11-21T03:14:00.000Z",6.69,3.54,-5.64,-0.19,651.0,4.16,3.53],
["2021-11-21T03:15:00.000Z",6.71,3.08,-5.95,-0.19,651.0,4.16,3.53],
["2021-11-21T03:16:00.000Z",6.71,3.50,-5.70,0.01,653.7,4.38,3.74],
["2021-11-21T03:17:00.000Z",6.69,3.19,-5.86,-0.15,653.7,4.38,3.74],
["2021-11-21T03:18:00.000Z",6.57,3.13,-5.77,0.27,653.7,4.38,3.74],
["2021-11-21T03:19:00.000Z",6.68,3.49,-5.67,0.24,645.6,4.23,3.53],
["2021-11-21T03:20:00.000Z",6.75,3.93,-5.45,0.48,645.6,4.23,3.53],
["2021-11-21T03:21:00.000Z",6.67,3.98,-5.25,0.81,645.6,4.23,3.53],
["2021-11-21T03:22:00.000Z",6.74,4.28,-5.11,0.39,645.5,4.21,3.51],
["2021-11-21T03:23:00.000Z",6.82,4.19,-5.33,-0.16,646.6,4.27,3.57],
["2021-11-21T03:24:00.000Z",6.70,3.97,-5.34,0.74,644.6,4.28,3.56],
["2021-11-21T03:25:00.000Z",6.83,4.35,-5.05,1.13,638.6,4.00,3.26],
["2021-11-21T03:26:00.000Z",6.82,4.40,-4.96,1.49,638.4,3.99,3.25],
["2021-11-21T03:27:00.000Z",6.77,4.39,-4.91,1.32,632.1,3.46,2.76],
["2021-11-21T03:28:00.000Z",6.82,4.80,-4.53,1.52,632.1,3.46,2.76],
["2021-11-21T03:29:00.000Z",6.72,4.16,-4.68,2.41,637.0,3.83,3.11],
["2021-11-21T03:30:00.000Z",6.64,4.23,-4.40,2.61,637.2,3.85,3.13],
["2021-11-21T03:31:00.000Z",6.91,4.21,-4.81,2.63,633.7,3.79,3.04],
["2021-11-21T03:32:00.000Z",7.07,4.20,-5.02,2.64,633.7,3.79,3.04],
["2021-11-21T03:33:00.000Z",7.02,4.23,-4.64,3.14,633.4,3.70,2.97],
["2021-11-21T03:34:00.000Z",7.04,4.37,-4.40,3.33,633.4,3.70,2.97],
["2021-11-21T03:35:00.000Z",6.91,4.20,-4.18,3.51,638.2,3.97,3.23],
["2021-11-21T03:36:00.000Z",6.72,4.04,-4.05,3.41,638.2,3.97,3.23],
["2021-11-21T03:37:00.000Z",6.65,4.67,-3.76,2.84,638.2,3.97,3.23],
["2021-11-21T03:38:00.000Z",6.78,5.01,-3.88,2.34,632.1,3.82,3.05],
["2021-11-21T03:39:00.000Z",6.91,4.84,-3.81,3.11,632.1,3.82,3.05],
["2021-11-21T03:40:00.000Z",6.88,4.98,-2.82,3.79,632.1,3.82,3.05],
["2021-11-21T03:41:00.000Z",6.69,4.88,-3.33,3.10,627.5,4.23,3.33],
["2021-11-21T03:42:00.000Z",6.68,4.71,-3.55,3.14,627.5,4.23,3.33],
["2021-11-21T03:43:00.000Z",6.16,4.35,-3.73,2.21,629.6,4.56,3.62],
["2021-11-21T03:44:00.000Z",6.22,4.73,-3.32,2.23,629.7,4.55,3.61],
["2021-11-21T03:45:00.000Z",6.02,4.51,-3.18,2.31,631.3,4.44,3.54],
["2021-11-21T03:46:00.000Z",6.00,4.43,-3.64,1.72,631.3,4.44,3.54],
["2021-11-21T03:47:00.000Z",6.11,4.46,-3.79,1.74,99999.9,999.99,99.99],
["2021-11-21T03:48:00.000Z",6.00,4.37,-3.65,1.90,625.6,4.49,3.51],
["2021-11-21T03:49:00.000Z",5.86,4.22,-3.83,1.35,626.4,4.47,3.51],
["2021-11-21T03:50:00.000Z",6.08,4.49,-3.96,1.04,631.1,4.42,3.52],
["2021-11-21T03:51:00.000Z",6.75,4.83,-4.59,1.00,630.7,4.74,3.77],
["2021-11-21T03:52:00.000Z",7.72,5.72,-5.12,0.56,606.6,3.78,2.78],
["2021-11-21T03:53:00.000Z",7.82,5.62,-5.29,1.25,605.0,3.57,2.61],
["2021-11-21T03:54:00.000Z",7.94,5.84,-5.24,1.19,607.8,3.42,2.53],
["2021-11-21T03:55:00.000Z",7.98,5.78,-5.31,1.49,611.4,3.26,2.44],
["2021-11-21T03:56:00.000Z",8.04,5.69,-5.48,1.42,610.1,3.30,2.46],
["2021-11-21T03:57:00.000Z",8.01,5.73,-5.42,1.39,604.9,3.28,2.40],
["2021-11-21T03:58:00.000Z",8.01,5.74,-5.39,1.45,603.5,3.28,2.39],
["2021-11-21T03:59:00.000Z",8.01,5.80,-5.32,1.50,601.1,3.39,2.45],
["2021-11-21T04:00:00.000Z",8.07,6.00,-5.29,0.94,605.9,3.24,2.38],
["2021-11-21T04:01:00.000Z",8.04,5.88,-5.31,1.29,605.6,3.31,2.43],
["2021-11-21T04:02:00.000Z",8.11,5.78,-5.58,1.02,600.3,3.58,2.58],
["2021-11-21T04:03:00.000Z",8.13,5.79,-5.62,0.86,603.6,3.42,2.49],
["2021-11-21T04:04:00.000Z",8.24,6.00,-5.38,1.60,606.9,3.46,2.55],
["2021-11-21T04:05:00.000Z",8.16,5.78,-5.31,2.15,602.9,3.20,2.33],
["2021-11-21T04:06:00.000Z",8.16,5.82,-5.43,1.73,602.7,3.19,2.32],
["2021-11-21T04:07:00.000Z",8.14,5.80,-5.50,1.52,596.1,3.40,2.42],
["2021-11-21T04:08:00.000Z",8.17,5.68,-5.49,2.08,596.1,3.40,2.42],
["2021-11-21T04:09:00.000Z",8.18,5.69,-5.48,2.10,597.5,3.57,2.55],
["2021-11-21T04:10:00.000Z",8.19,5.72,-5.56,1.85,597.5,3.57,2.55],
["2021-11-21T04:11:00.000Z",8.18,5.75,-5.48,1.91,596.8,3.53,2.51],
["2021-11-21T04:12:00.000Z",8.20,5.82,-5.46,1.89,594.1,3.38,2.39],
["2021-11-21T04:13:00.000Z",8.23,5.84,-5.51,1.81,594.1,3.38,2.39],
["2021-11-21T04:14:00.000Z",8.25,5.87,-5.50,1.80,592.6,3.61,2.54],
["2021-11-21T04:15:00.000Z",8.31,5.98,-5.48,1.82,592.6,3.61,2.54],
["2021-11-21T04:16:00.000Z",8.35,5.98,-5.50,1.90,99999.9,999.99,99.99],
["2021-11-21T04:17:00.000Z",8.41,5.98,-5.60,1.87,99999.9,999.99,99.99],
["2021-11-21T04:18:00.000Z",8.35,5.89,-5.67,1.59,99999.9,999.99,99.99],
["2021-11-21T04:19:00.000Z",8.43,5.84,-5.90,1.44,99999.9,999.99,99.99],
["2021-11-21T04:20:00.000Z",8.49,5.90,-6.01,1.11,587.6,3.32,2.29],
["2021-11-21T04:21:00.000Z",8.75,6.11,-6.10,1.43,587.6,3.32,2.29],
["2021-11-21T04:22:00.000Z",8.79,6.02,-6.32,0.97,583.3,3.40,2.31],
["2021-11-21T04:23:00.000Z",8.70,5.76,-6.50,-0.03,583.1,3.40,2.31],
["2021-11-21T04:24:00.000Z",8.80,5.84,-6.47,-0.06,572.6,2.98,1.95],
["2021-11-21T04:25:00.000Z",8.97,5.70,-6.90,0.30,571.3,2.93,1.91],
["2021-11-21T04:26:00.000Z",8.84,5.60,-6.80,0.67,567.2,3.18,2.05],
["2021-11-21T04:27:00.000Z",8.87,5.45,-6.98,0.18,567.9,3.21,2.07],
["2021-11-21T04:28:00.000Z",8.94,5.96,-6.63,0.60,569.2,3.26,2.11],
["2021-11-21T04:29:00.000Z",8.91,5.87,-6.69,0.37,569.2,3.26,2.11],
["2021-11-21T04:30:00.000Z",8.90,5.73,-6.79,0.27,569.1,3.20,2.07],
["2021-11-21T04:31:00.000Z",8.90,5.61,-6.91,0.09,569.1,3.20,2.07],
["2021-11-21T04:32:00.000Z",9.04,5.55,-7.12,-0.09,568.6,3.24,2.10],
["2021-11-21T04:33:00.000Z",9.07,5.98,-6.78,0.44,568.6,3.24,2.10],

In [22]:
json_data_success.keys()

dict_keys(['HAPI', 'status', 'format', 'parameters', 'data'])

In [23]:
json_data_success['status']

{'code': 1200, 'message': 'OK'}

#### Fail: no data in time range

In [30]:
# fail
fetch_json_no_data = fetch_data_omni_hro2_1min(
    start_utc="1500-11-21T00:00:00Z",
    end_utc="1501-11-22T00:00:00Z",
    format='json',
    vars="F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
{
"HAPI": "2.0",
"status": {"code": 1200, "message": "OK"},
"format": "json",
"parameters": [
{
"name": "Time",
"type": "isotime",
"units": "UTC",
"length":24,
"fill": null
},
{
"name": "F",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)"
},
{
"name": "BX_GSE",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bx (nT), GSE"
},
{
"name": "BY_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "By (nT), GSM, determined from post-shift GSE components"
},
{
"name": "BZ_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bz (nT), GSM, determined from post-shift GSE components"
},
{
"name": "flow_speed",
"type": "double",
"units": "km/s",
"fill": "99999.9",
"description": "Flow Speed (km/s), GSE"
},
{
"name": "proton_density",
"type": "double",
"units": "n/cc",
"fill": "999.99",
"description": "Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)"
},
{
"name": "Pressure",
"type": "double",
"units": "nPa",
"fill": "99.99",
"description": "Flow pressure (nPa)"
}
],
"data":[
,
"status": {"code": 1201, "message": "OK - no data for time range"}
}

Request succeeded.
⚠️⚠️ MALFOMED JSON RESPONSE ⚠️⚠️. Returning raw response instead.
JSONDecodeError('Expecting value: line 64 column 1 (char 1183)')

In [31]:
fetch_json_no_data

'{\n"HAPI": "2.0",\n"status": {"code": 1200, "message": "OK"},\n"format": "json",\n"parameters": [\n{\n"name": "Time",\n"type": "isotime",\n"units": "UTC",\n"length":24,\n"fill": null\n},\n{\n"name": "F",\n"type": "double",\n"units": "nT",\n"fill": "9999.99",\n"description": "Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)"\n},\n{\n"name": "BX_GSE",\n"type": "double",\n"units": "nT",\n"fill": "9999.99",\n"description": "Bx (nT), GSE"\n},\n{\n"name": "BY_GSM",\n"type": "double",\n"units": "nT",\n"fill": "9999.99",\n"description": "By (nT), GSM, determined from post-shift GSE components"\n},\n{\n"name": "BZ_GSM",\n"type": "double",\n"units": "nT",\n"fill": "9999.99",\n"description": "Bz (nT), GSM, determined from post-shift GSE components"\n},\n{\n"name": "flow_speed",\n"type": "double",\n"units": "km/s",\n"fill": "99999.9",\n"description": "Flow Speed (km/s), GSE"\n},\n{\n"name": "proton_density",\n"type": "double",\n"units": "n/cc",\n"fill": "999.99",\n"description": "Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)"\n},\n{\n"name": "Pressure",\n"type": "double",\n"units": "nPa",\n"fill": "99.99",\n"description": "Flow pressure (nPa)"\n}\n],\n"data":[\n,\n"status": {"code": 1201, "message": "OK - no data for time range"}\n}\n'

In [71]:
fetch_json_no_data.replace('\n', '')

'{"HAPI": "2.0","status": {"code": 1200, "message": "OK"},"format": "json","parameters": [{"name": "Time","type": "isotime","units": "UTC","length":24,"fill": null},{"name": "F","type": "double","units": "nT","fill": "9999.99","description": "Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)"},{"name": "BX_GSE","type": "double","units": "nT","fill": "9999.99","description": "Bx (nT), GSE"},{"name": "BY_GSM","type": "double","units": "nT","fill": "9999.99","description": "By (nT), GSM, determined from post-shift GSE components"},{"name": "BZ_GSM","type": "double","units": "nT","fill": "9999.99","description": "Bz (nT), GSM, determined from post-shift GSE components"},{"name": "flow_speed","type": "double","units": "km/s","fill": "99999.9","description": "Flow Speed (km/s), GSE"},{"name": "proton_density","type": "double","units": "n/cc","fill": "999.99","description": "Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)"},{"name": "Pressure","type": "double","units": "nPa","fill": "99.99","description": "Flow pressure (nPa)"}],"data":[,"status": {"code": 1201, "message": "OK - no data for time range"}}'

#### Fail: Incorrect variable name

In [32]:
# fail: incorrect variable name
fetch_json_incorrect_variable_name = fetch_data_omni_hro2_1min(
    start_utc="2021-11-21T00:00:00Z",
    end_utc="2021-11-22T00:00:00Z",
    format='json',
    vars="unknown_variable_name,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure"
)

Requesting solar dataset from OMNI_HRO2_1MIN...
{
"HAPI": "2.0",
"status": {"code": 1407, "message": "Bad request - unknown dataset parameter"}}

HTTPError: 400 Client Error: 400 for url: https://cdaweb.gsfc.nasa.gov/hapi/data?id=OMNI_HRO2_1MIN&time.min=2021-11-21T00%3A00%3A00Z&time.max=2021-11-22T00%3A00%3A00Z&format=json&parameters=unknown_variable_name%2CBX_GSE%2CBY_GSM%2CBZ_GSM%2Cflow_speed%2Cproton_density%2CPressure

#### (Potential edge case) Partial overlap of time range

In [77]:
fetch_json_edge_case = fetch_data_omni_hro2_1min(
    start_utc="2026-04-13T00:00:00Z",
    end_utc="2026-04-16T00:00:00Z",
    vars="F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure",
    format='json'
)

Requesting solar dataset from OMNI_HRO2_1MIN...
{
"HAPI": "2.0",
"status": {"code": 1200, "message": "OK"},
"format": "json",
"parameters": [
{
"name": "Time",
"type": "isotime",
"units": "UTC",
"length":24,
"fill": null
},
{
"name": "F",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)"
},
{
"name": "BX_GSE",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bx (nT), GSE"
},
{
"name": "BY_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "By (nT), GSM, determined from post-shift GSE components"
},
{
"name": "BZ_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bz (nT), GSM, determined from post-shift GSE components"
},
{
"name": "flow_speed",
"type": "double",
"units": "km/s",
"fill": "99999.9",
"description": "Flow Speed (km/s), GSE"
},
{
"name": "proton_density",
"type": "double",
"units": "n/cc",
"fill": "999.99",
"description": "Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)"
},
{
"name": "Pressure",
"type": "double",
"units": "nPa",
"fill": "99.99",
"description": "Flow pressure (nPa)"
}
],
"data":[
["2026-04-13T00:00:00.000Z",4.47,-3.07,-1.13,2.88,464.3,3.54,1.53],
["2026-04-13T00:01:00.000Z",4.41,-3.08,-1.65,2.64,464.4,3.54,1.53],
["2026-04-13T00:02:00.000Z",4.47,-3.17,-0.93,2.90,99999.9,999.99,99.99],
["2026-04-13T00:03:00.000Z",4.49,-2.98,-1.52,2.95,465.4,3.15,1.36],
["2026-04-13T00:04:00.000Z",4.49,-3.20,-0.85,2.99,465.4,3.15,1.36],
["2026-04-13T00:05:00.000Z",4.47,-2.88,-1.60,2.98,465.0,3.33,1.44],
["2026-04-13T00:06:00.000Z",4.44,-3.15,0.38,2.98,465.0,3.33,1.44],
["2026-04-13T00:07:00.000Z",4.45,-3.20,0.65,3.02,465.0,3.33,1.44],
["2026-04-13T00:08:00.000Z",4.50,-2.51,2.94,2.22,99999.9,999.99,99.99],
["2026-04-13T00:09:00.000Z",4.48,-2.25,2.98,2.40,468.4,2.75,1.21],
["2026-04-13T00:10:00.000Z",4.60,-2.83,-0.47,3.33,468.4,2.75,1.21],
["2026-04-13T00:11:00.000Z",4.53,-2.97,0.14,3.05,468.4,2.75,1.21],
["2026-04-13T00:12:00.000Z",4.61,-2.78,-1.48,3.37,99999.9,999.99,99.99],
["2026-04-13T00:13:00.000Z",4.56,-3.25,-0.34,2.94,464.1,3.31,1.43],
["2026-04-13T00:14:00.000Z",4.53,-3.52,0.33,2.59,464.1,3.31,1.43],
["2026-04-13T00:15:00.000Z",4.52,-2.41,-1.17,2.72,458.4,3.19,1.34],
["2026-04-13T00:16:00.000Z",4.53,-2.75,-1.16,2.85,456.5,3.13,1.30],
["2026-04-13T00:17:00.000Z",4.53,-3.37,-1.18,2.62,459.4,3.17,1.34],
["2026-04-13T00:18:00.000Z",4.59,-3.10,-0.50,3.07,99999.9,999.99,99.99],
["2026-04-13T00:19:00.000Z",4.58,-3.26,-0.40,2.99,99999.9,999.99,99.99],
["2026-04-13T00:20:00.000Z",4.58,-2.89,-0.88,3.05,458.0,3.05,1.28],
["2026-04-13T00:21:00.000Z",4.59,-3.09,-0.53,3.09,467.3,3.15,1.38],
["2026-04-13T00:22:00.000Z",4.59,-3.06,-0.03,3.20,465.9,3.45,1.50],
["2026-04-13T00:23:00.000Z",4.55,-2.87,0.03,3.23,462.6,3.35,1.43],
["2026-04-13T00:24:00.000Z",4.55,-2.94,0.45,2.96,458.1,3.21,1.35],
["2026-04-13T00:25:00.000Z",4.60,-2.79,0.83,3.26,99999.9,999.99,99.99],
["2026-04-13T00:26:00.000Z",4.63,-3.21,0.59,2.76,461.8,3.25,1.39],
["2026-04-13T00:27:00.000Z",4.57,-2.39,1.81,3.18,461.8,3.25,1.39],
["2026-04-13T00:28:00.000Z",4.59,-2.63,0.07,2.93,483.1,3.45,1.61],
["2026-04-13T00:29:00.000Z",4.57,-2.22,-0.94,2.78,483.1,3.45,1.61],
["2026-04-13T00:30:00.000Z",4.59,-2.13,-0.58,2.89,99999.9,999.99,99.99],
["2026-04-13T00:31:00.000Z",4.62,-2.25,-0.08,3.13,99999.9,999.99,99.99],
["2026-04-13T00:32:00.000Z",4.60,-2.37,0.86,3.06,465.5,2.55,1.11],
["2026-04-13T00:33:00.000Z",4.56,-1.06,2.31,2.73,473.9,3.12,1.40],
["2026-04-13T00:34:00.000Z",4.52,-1.78,0.75,2.86,485.7,3.10,1.46],
["2026-04-13T00:35:00.000Z",4.57,-2.23,-1.02,2.79,479.0,3.57,1.64],
["2026-04-13T00:36:00.000Z",4.58,-1.74,-0.97,3.56,480.9,3.12,1.44],
["2026-04-13T00:37:00.000Z",4.59,-2.39,-0.28,3.41,472.9,3.32,1.48],
["2026-04-13T00:38:00.000Z",4.60,-2.35,-0.07,3.23,466.7,3.33,1.45],
["2026-04-13T00:39:00.000Z",4.59,-3.07,1.22,2.69,464.1,3.30,1.42],
["2026-04-13T00:40:00.000Z",4.60,-3.00,0.78,2.40,458.7,3.24,1.36],
["2026-04-13T00:41:00.000Z",4.57,-3.38,1.34,2.21,99999.9,999.99,99.99],
["2026-04-13T00:42:00.000Z",4.60,-3.32,0.32,2.72,99999.9,999.99,99.99],
["2026-04-13T00:43:00.000Z",4.63,-3.39,-0.05,2.99,99999.9,999.99,99.99],
["2026-04-13T00:44:00.000Z",4.62,-2.82,0.16,3.26,99999.9,999.99,99.99],
["2026-04-13T00:45:00.000Z",4.69,-3.68,1.07,2.69,99999.9,999.99,99.99],
["2026-04-13T00:46:00.000Z",4.62,-3.18,0.23,3.05,99999.9,999.99,99.99],
["2026-04-13T00:47:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:48:00.000Z",4.52,-2.59,-1.19,3.48,470.1,3.28,1.45],
["2026-04-13T00:49:00.000Z",4.54,-2.04,-1.70,3.67,470.1,3.28,1.45],
["2026-04-13T00:50:00.000Z",9999.99,9999.99,9999.99,9999.99,470.1,3.28,1.45],
["2026-04-13T00:51:00.000Z",4.52,-2.22,-1.48,3.61,99999.9,999.99,99.99],
["2026-04-13T00:52:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:53:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:54:00.000Z",4.53,-2.42,-1.74,3.37,465.8,3.26,1.41],
["2026-04-13T00:55:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:56:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:57:00.000Z",4.54,-2.33,-1.46,3.57,99999.9,999.99,99.99],
["2026-04-13T00:58:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:59:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:00:00.000Z",4.54,-2.39,-1.54,3.53,99999.9,999.99,99.99],
["2026-04-13T01:01:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:02:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:03:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:04:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:05:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:06:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:07:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:08:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:09:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:10:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:11:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:12:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:13:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:14:00.000Z",4.62,-2.51,-0.50,3.80,99999.9,999.99,99.99],
["2026-04-13T01:15:00.000Z",4.65,-3.71,0.52,2.72,99999.9,999.99,99.99]
]
}

Request succeeded.

In [83]:
json.loads(fetch_json_edge_case).keys()

dict_keys(['HAPI', 'status', 'format', 'parameters', 'data'])

In [81]:
print(fetch_json_edge_case)

{
"HAPI": "2.0",
"status": {"code": 1200, "message": "OK"},
"format": "json",
"parameters": [
{
"name": "Time",
"type": "isotime",
"units": "UTC",
"length":24,
"fill": null
},
{
"name": "F",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)"
},
{
"name": "BX_GSE",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bx (nT), GSE"
},
{
"name": "BY_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "By (nT), GSM, determined from post-shift GSE components"
},
{
"name": "BZ_GSM",
"type": "double",
"units": "nT",
"fill": "9999.99",
"description": "Bz (nT), GSM, determined from post-shift GSE components"
},
{
"name": "flow_speed",
"type": "double",
"units": "km/s",
"fill": "99999.9",
"description": "Flow Speed (km/s), GSE"
},
{
"name": "proton_density",
"type": "double",
"units": "n/cc",
"fill": "999.99",
"description": "Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)"
},
{
"name": "Pressure",
"type": "double",
"units": "nPa",
"fill": "99.99",
"description": "Flow pressure (nPa)"
}
],
"data":[
["2026-04-13T00:00:00.000Z",4.47,-3.07,-1.13,2.88,464.3,3.54,1.53],
["2026-04-13T00:01:00.000Z",4.41,-3.08,-1.65,2.64,464.4,3.54,1.53],
["2026-04-13T00:02:00.000Z",4.47,-3.17,-0.93,2.90,99999.9,999.99,99.99],
["2026-04-13T00:03:00.000Z",4.49,-2.98,-1.52,2.95,465.4,3.15,1.36],
["2026-04-13T00:04:00.000Z",4.49,-3.20,-0.85,2.99,465.4,3.15,1.36],
["2026-04-13T00:05:00.000Z",4.47,-2.88,-1.60,2.98,465.0,3.33,1.44],
["2026-04-13T00:06:00.000Z",4.44,-3.15,0.38,2.98,465.0,3.33,1.44],
["2026-04-13T00:07:00.000Z",4.45,-3.20,0.65,3.02,465.0,3.33,1.44],
["2026-04-13T00:08:00.000Z",4.50,-2.51,2.94,2.22,99999.9,999.99,99.99],
["2026-04-13T00:09:00.000Z",4.48,-2.25,2.98,2.40,468.4,2.75,1.21],
["2026-04-13T00:10:00.000Z",4.60,-2.83,-0.47,3.33,468.4,2.75,1.21],
["2026-04-13T00:11:00.000Z",4.53,-2.97,0.14,3.05,468.4,2.75,1.21],
["2026-04-13T00:12:00.000Z",4.61,-2.78,-1.48,3.37,99999.9,999.99,99.99],
["2026-04-13T00:13:00.000Z",4.56,-3.25,-0.34,2.94,464.1,3.31,1.43],
["2026-04-13T00:14:00.000Z",4.53,-3.52,0.33,2.59,464.1,3.31,1.43],
["2026-04-13T00:15:00.000Z",4.52,-2.41,-1.17,2.72,458.4,3.19,1.34],
["2026-04-13T00:16:00.000Z",4.53,-2.75,-1.16,2.85,456.5,3.13,1.30],
["2026-04-13T00:17:00.000Z",4.53,-3.37,-1.18,2.62,459.4,3.17,1.34],
["2026-04-13T00:18:00.000Z",4.59,-3.10,-0.50,3.07,99999.9,999.99,99.99],
["2026-04-13T00:19:00.000Z",4.58,-3.26,-0.40,2.99,99999.9,999.99,99.99],
["2026-04-13T00:20:00.000Z",4.58,-2.89,-0.88,3.05,458.0,3.05,1.28],
["2026-04-13T00:21:00.000Z",4.59,-3.09,-0.53,3.09,467.3,3.15,1.38],
["2026-04-13T00:22:00.000Z",4.59,-3.06,-0.03,3.20,465.9,3.45,1.50],
["2026-04-13T00:23:00.000Z",4.55,-2.87,0.03,3.23,462.6,3.35,1.43],
["2026-04-13T00:24:00.000Z",4.55,-2.94,0.45,2.96,458.1,3.21,1.35],
["2026-04-13T00:25:00.000Z",4.60,-2.79,0.83,3.26,99999.9,999.99,99.99],
["2026-04-13T00:26:00.000Z",4.63,-3.21,0.59,2.76,461.8,3.25,1.39],
["2026-04-13T00:27:00.000Z",4.57,-2.39,1.81,3.18,461.8,3.25,1.39],
["2026-04-13T00:28:00.000Z",4.59,-2.63,0.07,2.93,483.1,3.45,1.61],
["2026-04-13T00:29:00.000Z",4.57,-2.22,-0.94,2.78,483.1,3.45,1.61],
["2026-04-13T00:30:00.000Z",4.59,-2.13,-0.58,2.89,99999.9,999.99,99.99],
["2026-04-13T00:31:00.000Z",4.62,-2.25,-0.08,3.13,99999.9,999.99,99.99],
["2026-04-13T00:32:00.000Z",4.60,-2.37,0.86,3.06,465.5,2.55,1.11],
["2026-04-13T00:33:00.000Z",4.56,-1.06,2.31,2.73,473.9,3.12,1.40],
["2026-04-13T00:34:00.000Z",4.52,-1.78,0.75,2.86,485.7,3.10,1.46],
["2026-04-13T00:35:00.000Z",4.57,-2.23,-1.02,2.79,479.0,3.57,1.64],
["2026-04-13T00:36:00.000Z",4.58,-1.74,-0.97,3.56,480.9,3.12,1.44],
["2026-04-13T00:37:00.000Z",4.59,-2.39,-0.28,3.41,472.9,3.32,1.48],
["2026-04-13T00:38:00.000Z",4.60,-2.35,-0.07,3.23,466.7,3.33,1.45],
["2026-04-13T00:39:00.000Z",4.59,-3.07,1.22,2.69,464.1,3.30,1.42],
["2026-04-13T00:40:00.000Z",4.60,-3.00,0.78,2.40,458.7,3.24,1.36],
["2026-04-13T00:41:00.000Z",4.57,-3.38,1.34,2.21,99999.9,999.99,99.99],
["2026-04-13T00:42:00.000Z",4.60,-3.32,0.32,2.72,99999.9,999.99,99.99],
["2026-04-13T00:43:00.000Z",4.63,-3.39,-0.05,2.99,99999.9,999.99,99.99],
["2026-04-13T00:44:00.000Z",4.62,-2.82,0.16,3.26,99999.9,999.99,99.99],
["2026-04-13T00:45:00.000Z",4.69,-3.68,1.07,2.69,99999.9,999.99,99.99],
["2026-04-13T00:46:00.000Z",4.62,-3.18,0.23,3.05,99999.9,999.99,99.99],
["2026-04-13T00:47:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:48:00.000Z",4.52,-2.59,-1.19,3.48,470.1,3.28,1.45],
["2026-04-13T00:49:00.000Z",4.54,-2.04,-1.70,3.67,470.1,3.28,1.45],
["2026-04-13T00:50:00.000Z",9999.99,9999.99,9999.99,9999.99,470.1,3.28,1.45],
["2026-04-13T00:51:00.000Z",4.52,-2.22,-1.48,3.61,99999.9,999.99,99.99],
["2026-04-13T00:52:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:53:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:54:00.000Z",4.53,-2.42,-1.74,3.37,465.8,3.26,1.41],
["2026-04-13T00:55:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:56:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:57:00.000Z",4.54,-2.33,-1.46,3.57,99999.9,999.99,99.99],
["2026-04-13T00:58:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T00:59:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:00:00.000Z",4.54,-2.39,-1.54,3.53,99999.9,999.99,99.99],
["2026-04-13T01:01:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:02:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:03:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:04:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:05:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:06:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:07:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:08:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:09:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:10:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:11:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:12:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:13:00.000Z",9999.99,9999.99,9999.99,9999.99,99999.9,999.99,99.99],
["2026-04-13T01:14:00.000Z",4.62,-2.51,-0.50,3.80,99999.9,999.99,99.99],
["2026-04-13T01:15:00.000Z",4.65,-3.71,0.52,2.72,99999.9,999.99,99.99]
]
}

# Try modularizing code or at least specify interface

In [ ]:
from src.io.atomic import _atomic_write_json, write_success, write_failed
from typing import Any, Dict, Iterable, Iterator, List, Optional, Tuple
from datetime import datetime, timedelta, timezone
from dataclasses import dataclass
import time

CLI_UTC_FMT = "%Y-%m-%d %H:%M:%S"
HAPI_UTC_FMT = "%Y-%m-%dT%H:%M:%SZ"

def parse_cli_utc_datetime(value: str) -> datetime:
    """Parse CLI UTC string into UTC-naive datetime; reject ISO T/Z strings."""

def parse_hapi_utc_datetime(value: str) -> datetime:
    """Parse /info HAPI timestamp into UTC-naive datetime."""

def format_hapi_utc_datetime(value: datetime) -> str:
    """Format UTC-naive datetime for HAPI /data request."""

def _chunk_token(dt_: Optional[datetime]) -> str:

    """
    Returns the provided in datetime UTC format with non alphanumerics removed.
    
    Main use case is for chunk filenames
    """

    if dt_ is None:
        return "open"
    
    # defensive on the invariant that strdatetimes are UTC naive (no tzinfo)
    if dt_.tzinfo is not None:
        dt_ = dt_.astimezone(timezone.utc).replace(tzinfo=None)

    # Example: 20250101T000000Z
    return dt_.strftime("%Y%m%dT%H%M%SZ")

def _run_id_utc() -> str:
    """
    Returns the current datetime in UTC format with non alphanumerics removed.

    Main use case is an identifier proxy (generating run ids)
    """
    # Example: 20251229T103210Z
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

def omni_chunk_filename(chunk_start: datetime, chunk_end: datetime) -> str:
    return f"chunk_{_chunk_token(chunk_start)}__{_chunk_token(chunk_end)}.json"



# @dataclass autogenerates "dunder" methods, frozen=True makes instances immutable
@dataclass(frozen=True)
class OmniChunk:
    chunk_start: datetime
    chunk_end: datetime
    payload: dict


@dataclass(frozen=True) 
class OmniIngestionPlan:
    requested_start: datetime
    requested_end: datetime
    effective_start: datetime
    effective_end: datetime
    time_range_overlap_status: str  # "subset" | "partial" | "full"
    warnings: list[str]
    parameters: list[str]


def write_chunk_json(run_dir: Path, chunk: OmniChunk) -> Path:
    path = run_dir / omni_chunk_filename(chunk.chunk_start, chunk.chunk_end)
    _atomic_write_json(path, chunk.payload)
    return path


def fetch_hapi_info(base_url: str,
                    dataset_id: str,
                    timeout_s: int) -> dict:
    """
    Fetch dataset metadata at runtime from `/info` CDAWeb HAPI endpoint.
    Malformed dataset_id is expected to be caught as an exception.

    Args:
    - base_url: the base URL for the CDAWeb HAPI
    - dataset_id: the dataset id to fetch data from (e.g. "OMNI_HRO2_1MIN")
    - timeout_s: how long to wait before GET request fails
        

    Returns:
        

    Raises:
        
    """
    info_url = base_url + '/info'
    response = requests.get(info_url, params={"id": dataset_id}, timeout=timeout_s)

    try:
        payload = response.json()
    except ValueError as exc:
        response.raise_for_status()
        raise RuntimeError("CDAWeb HAPI /info returned non-JSON response") from exc

    hapi_status = payload.get("status", {})
    hapi_code = hapi_status.get("code")
    hapi_message = hapi_status.get("message")

    if response.status_code >= 400 or hapi_code != 1200:
        raise RuntimeError(
            f"CDAWeb HAPI /info failed for dataset_id={dataset_id} "
            f"| http_status={response.status_code} "
            f"| hapi_status={hapi_code} "
            f"| message={hapi_message}"
        )
    
    return payload

def validate_hapi_info(
    info: dict,
    supported_hapi_version: str,
    requested_parameters: list[str],
    start: datetime,
    end: datetime,
) -> OmniIngestionPlan:
    """
    Validates CLI args (start date, end date, requested parameters)
    against the /info HAPI payload. 

    - accepts start: datetime, end: datetime
    - parses /info startDate/stopDate internally
    - compares datetime intervals
    - returns a small validated request plan

    /info response keys
    ['HAPI', 'resourceURL', 'contact', 'parameters', 'startDate', 'stopDate', 'status']
    """
    
    # HAPI version mismatch -> RuntimeError
    current_hapi_version = info['HAPI']
    if supported_hapi_version != current_hapi_version:
        raise RuntimeError(f"Supported HAPI version ({supported_hapi_version}) does not match current HAPI version ({current_hapi_version})")

    # requested parameter missing -> ValueError
    parameters_glossary = set([param_metadata['name'] for param_metadata in info['parameters']])
    requested_parameters_set = set(requested_parameters)
    if not requested_parameters_set.issubset(parameters_glossary):
        raise ValueError(f"Unsupported parameters found: {requested_parameters_set - parameters_glossary}")

    # time range outside info startDate/stopDate -> ValueError
    # parse /info HAPI startDate and stopDate for date operations
    dataset_start  = parse_hapi_utc_datetime(info['startDate'])
    dataset_stop  = parse_hapi_utc_datetime(info['stopDate'])
    # perform the following
    """
    - If requested end <= dataset startDate, raise ValueError.
    - If requested start >= dataset stopDate, raise ValueError.
    - If intervals partially overlap, warn and continue.
    - If requested interval is fully inside dataset interval, continue silently.
    """
    if end <= dataset_start or start >= dataset_stop:
        raise ValueError(f"Date interval request [{start}, {end}] falls beyond dataset record period [{dataset_start}, {dataset_stop}]")

    # if no ValueError is raised, this means we have end > dataset_start and start < dataset_stop 
    effective_start = max(start, dataset_start)
    effective_end = min(end, dataset_stop)

    time_range_overlap_status = 'subset'
    if effective_start != start or effective_end != end:
        # warn and record partial overlap
        time_range_overlap_status = 'partial'
        pass

    return OmniIngestionPlan(
        requested_start=start, requested_end=end,
        effective_start=effective_start, effective_end=effective_end,
        time_range_overlap_status=time_range_overlap_status,
        parameters=requested_parameters
    )



def fetch_hapi_data(
    base_url: str,
    dataset_id: str,
    parameters: list[str],
    start: datetime,
    end: datetime,
    timeout_s: int,
) -> str:
    """
    Fetch solar wind observations from OMNI via
    `/data` CDAWeb HAPI endpoint.

    Assumptions:
    - parameters, base_url, dataset_id, start, date, are valid

    Args:
        

    Returns:
        

    Raises:
        
    """

    start_utc = format_hapi_utc_datetime(start)
    end_utc = format_hapi_utc_datetime(end)
    params_request = ','.join(parameters)

    data_url = base_url + '/data'

    response = requests.get(data_url,
                            params={"id": dataset_id,
                                    "parameters": params_request,
                                    "time.min": start_utc,
                                    "time.max": end_utc,
                                    "format": "json"},
                                    timeout=timeout_s)
    
    # parse response to json here or return response.text?
    return response.text

def iter_omni_chunks(
    base_url: str,
    dataset_id: str,
    parameters: list[str],
    start: datetime,
    end: datetime,
    timeout_s: int,
    chunk_days: int,
    sleep_s: float
) -> Iterator[OmniChunk]:
    """
    accepts start: datetime, end: datetime only
    performs arithmetic
    calls fetch_hapi_data with datetime chunk boundaries
    """
    chunk_start = start
    while chunk_start < end:
        chunk_end = min(chunk_start + timedelta(days=chunk_days), end)
        payload = fetch_hapi_data(base_url, dataset_id, parameters, chunk_start, chunk_end, timeout_s)
        # possibly return an OmniChunk data class
        # with attributes: payload, chunk_start, chunk_end
        yield OmniChunk(
            chunk_start=chunk_start,
            chunk_end=chunk_end,
            payload=payload,
        )

        # sleep between requests
        time.sleep(float(sleep_s))

        
        chunk_start = chunk_end



def write_manifest(run_dir: Path,
                   status: str,
                   Optional[Dict[str, Any]] = None) -> None:
    """
    Creates or updates a run manifest with a certain status.

    Args:
        

    Returns:
        

    Raises:
        
    """
    pass

def ingest_omni_run(
    omni_config: dict,
    *,
    parameters: list[str],
    start: object,
    end: object,
    raw_base_dir: object | None = None,
) -> Path:

    """
    parse and validate CLI start/end once 
    call `fetch_hapi_info` to fetch /info
    call `validate_hapi_info` using parsed datetimes
    call `iter_omni_chunks` with datetimes
    """
    
    # cache config outputs here first so that any modification 
    # to config keys can be done only here
    CONFIG_DATA_ID = omni_config['hapi']['dataset_id']
    CONFIG_SUPPORTED_HAPI_VER = omni_config['hapi']['supported_version']
    CONFIG_BASE_URL = omni_config['hapi']['base_url']
    CONFIG_CHUNK_DAYS = omni_config['hapi']['chunk_days']
    CONFIG_TIMEOUT = omni_config['hapi']['timeout_s']
    CONFIG_SLEEP = omni_config['hapi']['sleep_s']

    if not raw_base_dir:
        raw_base_dir = omni_config['hapi']['raw_output_dir']

    # parse and validate CLI start/end once
    start_dt = parse_cli_utc_datetime(start)
    end_dt = parse_cli_utc_datetime(end)
    
    # fetch /info for configured dataset_id specified in config
    info = fetch_hapi_info(CONFIG_BASE_URL, CONFIG_DATA_ID, CONFIG_TIMEOUT)

    # validate HAPI version, CLI args
    plan = validate_hapi_info(
        info,
        supported_hapi_version=CONFIG_SUPPORTED_HAPI_VER,
        requested_parameters=parameters,
        start=start_dt,
        end=end_dt,
    )

    # create runid + rundir at <raw_output_dir>/<dataset_id>/run_id=<run_id>
    run_id = _run_id_utc()
    # e.g. "data/01-raw/omni/OMNI_HRO2_1MIN"
    data_dir = Path(raw_base_dir) / CONFIG_DATA_ID
    # e.g. "data/01-raw/omni/OMNI_HRO2_1MIN/run_id=20260323T135622Z"
    run_dir = data_dir / f"run_id={run_id}"

    # write RUNNING manifest
    write_manifest(run_dir=run_dir,
                   status='RUNNING')

    # write dataset metadata from /info response 
    _atomic_write_json(data_dir / "hapi_info.json", info)


    try:
        total_rows = 0
        chunk_files = []
        chunk_statuses = []
        
        # iterate /data chunks
        for chunk in iter_omni_chunks(base_url=CONFIG_BASE_URL,
                                      dataset_id=CONFIG_DATA_ID,
                                      parameters=parameters,
                                      start=plan.effective_start,
                                      end=plan.effective_end,
                                      timeout_s=CONFIG_TIMEOUT,
                                      chunk_days=CONFIG_CHUNK_DAYS,
                                      sleep_s=CONFIG_SLEEP):
            
            # write raw chunk JSON files
            out_path = write_chunk_json(run_dir, chunk)

            # record information about the recently retrieved chunk
            rows = len(chunk.payload.get("data", []))
            status = chunk.payload.get("status", {})
            chunk_files.append(out_path.name)
            total_rows += rows
            chunk_statuses.append({
                "file": out_path.name,
                "chunk_start_utc_str": format_hapi_utc_datetime(chunk.chunk_start),
                "chunk_end_utc_str": format_hapi_utc_datetime(chunk.chunk_end),
                "hapi_status_code": status.get("code"),
                "hapi_status_message": status.get("message"),
                "rows": rows,
            })


        # write _SUCCESS
        write_success(run_dir)

        # write SUCCESS manifest
        write_manifest(run_dir=run_dir,
                   status='SUCCESS')
        
    except Exception as e:
        # write _FAILED
        write_failed(run_dir)

        # write FAILED manifest
        write_manifest(run_dir=run_dir,
                   status='SUCCESS')

        # reraise the original exception with full traceback.
        raise

In [87]:
omni_config

{'hapi': {'base_url': 'https://cdaweb.gsfc.nasa.gov/hapi',
  'supported_version': '2.0',
  'dataset_id': 'OMNI_HRO2_1MIN',
  'chunk_days': 10,
  'timeout_s': 120,
  'raw_output_dir': 'data/01-raw/omni'}}

In [89]:
CLI_PARAM = "F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure"
CLI_START = "2021-11-21T00:00:00Z"
CLI_END = "2021-11-22T00:00:00Z"
CONFIG_DATA_ID = omni_config['hapi']['dataset_id']
CONFIG_SUPPORTED_HAPI_VER = omni_config['hapi']['supported_version']
CONFIG_BASE_URL = omni_config['hapi']['base_url']
CONFIG_CHUNK_DAYS = omni_config['hapi']['chunk_days']
CONFIG_TIMEOUT = omni_config['hapi']['timeout_s']
CONFIG_OUTPUT_DIR = omni_config['hapi']['raw_output_dir']

In [91]:
fetch_hapi_info_test = fetch_hapi_info(CONFIG_BASE_URL, CONFIG_DATA_ID, CONFIG_TIMEOUT)
print(fetch_hapi_info_test)
print(fetch_hapi_info_test.keys())

{'HAPI': '2.0', 'resourceURL': 'https://cdaweb.gsfc.nasa.gov/misc/NotesO.html#OMNI_HRO2_1MIN', 'contact': 'J.H. King, N. Papatashvilli @ AdnetSystems, NASA GSFC', 'parameters': [{'name': 'Time', 'length': 24, 'units': 'UTC', 'type': 'isotime', 'fill': None}, {'name': 'IMF', 'description': 'OMNI ID code for the source spacecraft for time-shifted IMF values (see OMNI documentation link for codes)', 'units': None, 'type': 'integer', 'fill': '99'}, {'name': 'PLS', 'description': 'OMNI ID code for the source spacecraft  for time-shifted IP plasma values (see OMNI documentation link for codes)', 'units': None, 'type': 'integer', 'fill': '99'}, {'name': 'IMF_PTS', 'description': 'Number of fine time scale points in IMF averages', 'units': None, 'type': 'integer', 'fill': '999'}, {'name': 'PLS_PTS', 'description': 'Number of fine time scale points in plasma averages', 'units': None, 'type': 'integer', 'fill': '999'}, {'name': 'percent_interp', 'description': 'Percent interpolated', 'units': None, 'type': 'integer', 'fill': '999'}, {'name': 'Timeshift', 'description': 'Timeshift (seconds)', 'units': 'seconds', 'type': 'integer', 'fill': '999999'}, {'name': 'RMS_Timeshift', 'description': 'RMS Timeshift (seconds)', 'units': 'seconds', 'type': 'integer', 'fill': '999999'}, {'name': 'RMS_phase', 'description': 'RMS, Phase front normal (nT) ', 'units': 'nT', 'type': 'double', 'fill': '99.99'}, {'name': 'Time_btwn_obs', 'description': 'Time between observations (seconds)', 'units': 'seconds', 'type': 'integer', 'fill': '999999'}, {'name': 'F', 'description': 'Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'BX_GSE', 'description': 'Bx (nT), GSE', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'BY_GSE', 'description': 'By (nT), GSE', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'BZ_GSE', 'description': 'Bz (nT), GSE', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'BY_GSM', 'description': 'By (nT), GSM, determined from post-shift GSE components', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'BZ_GSM', 'description': 'Bz (nT), GSM, determined from post-shift GSE components', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'RMS_SD_B', 'description': 'RMS SD B scalar (nT)', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'RMS_SD_fld_vec', 'description': 'RMS SD field vector (nT)', 'units': 'nT', 'type': 'double', 'fill': '9999.99'}, {'name': 'flow_speed', 'description': 'Flow Speed (km/s), GSE', 'units': 'km/s', 'type': 'double', 'fill': '99999.9'}, {'name': 'Vx', 'description': 'Vx Velocity (km/s), GSE', 'units': 'km/s', 'type': 'double', 'fill': '99999.9'}, {'name': 'Vy', 'description': 'Vy Velocity (km/s), GSE', 'units': 'km/s', 'type': 'double', 'fill': '99999.9'}, {'name': 'Vz', 'description': 'Vz Velocity (km/s), GSE', 'units': 'km/s', 'type': 'double', 'fill': '99999.9'}, {'name': 'proton_density', 'description': 'Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)', 'units': 'n/cc', 'type': 'double', 'fill': '999.99'}, {'name': 'T', 'description': 'Temperature (K)', 'units': 'K', 'type': 'double', 'fill': '9999999.0'}, {'name': 'NaNp_Ratio', 'description': 'Alpha/Proton Density Ratio', 'units': ' ', 'type': 'double', 'fill': '9.999'}, {'name': 'Pressure', 'description': 'Flow pressure (nPa)', 'units': 'nPa', 'type': 'double', 'fill': '99.99'}, {'name': 'E', 'description': 'Electric Field (mV/m)', 'units': 'mV/m', 'type': 'double', 'fill': '999.99'}, {'name': 'Beta', 'description': 'Plasma beta', 'units': None, 'type': 'double', 'fill': '999.99'}, {'name': 'Mach_num', 'description': 'Alfven mach number', 'units': None, 'type': 'double', 'fill': '999.9'}, {'name': 'Mgs_mach_num', 'description': '1AU IP Magnetosonic mach number', 'units': None, 'type': 'double', 'fill': '99.9'}, {'name': 'x', 'description': 'X s/c (Re), GSE', 'units': 'Re', 'type': 'double', 'fill': '9999.99'}, {'name': 'y', 'description': 'Y s/c (Re), GSE', 'units': 'Re', 'type': 'double', 'fill': '9999.99'}, {'name': 'z', 'description': 'Z s/c (Re), GSE', 'units': 'Re', 'type': 'double', 'fill': '9999.99'}, {'name': 'BSN_x', 'description': 'Bow Shock Nose (Re) location, X, GSE', 'units': 'Re', 'type': 'double', 'fill': '9999.99'}, {'name': 'BSN_y', 'description': 'Bow Shock Nose (Re) location, Y, GSE', 'units': 'Re', 'type': 'double', 'fill': '9999.99'}, {'name': 'BSN_z', 'description': 'Bow Shock Nose (Re) location, Z, GSE', 'units': 'Re', 'type': 'double', 'fill': '9999.99'}, {'name': 'AE_INDEX', 'description': 'AE - 1-minute AE-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)', 'units': 'nT', 'type': 'integer', 'fill': '99999'}, {'name': 'AL_INDEX', 'description': 'AL - 1-minute AL-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)', 'units': 'nT', 'type': 'integer', 'fill': '99999'}, {'name': 'AU_INDEX', 'description': 'AU - 1-minute AU-index,from WDC Kyoto  (Final 1988/001-1988/182, Provisional 1990/001-2020/365)', 'units': 'nT', 'type': 'integer', 'fill': '99999'}, {'name': 'SYM_D', 'description': 'SYM/D - 1-minute SYM/D index,from WDC Kyoto (1981/001-2026/090)', 'units': 'nT', 'type': 'integer', 'fill': '99999'}, {'name': 'SYM_H', 'description': 'SYM/H - 1-minute SYM/H index,from WDC Kyoto (1981/001-2026/090)', 'units': 'nT', 'type': 'integer', 'fill': '99999'}, {'name': 'ASY_D', 'description': 'ASY/D - 1-minute ASY/D index,from WDC Kyoto (1981/001-2026/090)', 'units': 'nT', 'type': 'integer', 'fill': '99999'}, {'name': 'ASY_H', 'description': 'ASY/H - 1-minute ASY/H index,from WDC Kyoto (1981/001-2026/090)', 'units': 'nT', 'type': 'integer', 'fill': '99999'}], 'startDate': '1995-01-01T00:00:00Z', 'stopDate': '2026-04-13T01:15:00Z', 'status': {'code': 1200, 'message': 'OK'}}
dict_keys(['HAPI', 'resourceURL', 'contact', 'parameters', 'startDate', 'stopDate', 'status'])

In [92]:
fetch_hapi_info_test

{'HAPI': '2.0',
 'resourceURL': 'https://cdaweb.gsfc.nasa.gov/misc/NotesO.html#OMNI_HRO2_1MIN',
 'contact': 'J.H. King, N. Papatashvilli @ AdnetSystems, NASA GSFC',
 'parameters': [{'name': 'Time',
   'length': 24,
   'units': 'UTC',
   'type': 'isotime',
   'fill': None},
  {'name': 'IMF',
   'description': 'OMNI ID code for the source spacecraft for time-shifted IMF values (see OMNI documentation link for codes)',
   'units': None,
   'type': 'integer',
   'fill': '99'},
  {'name': 'PLS',
   'description': 'OMNI ID code for the source spacecraft  for time-shifted IP plasma values (see OMNI documentation link for codes)',
   'units': None,
   'type': 'integer',
   'fill': '99'},
  {'name': 'IMF_PTS',
   'description': 'Number of fine time scale points in IMF averages',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'PLS_PTS',
   'description': 'Number of fine time scale points in plasma averages',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'percent_interp',
   'description': 'Percent interpolated',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'Timeshift',
   'description': 'Timeshift (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'RMS_Timeshift',
   'description': 'RMS Timeshift (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'RMS_phase',
   'description': 'RMS, Phase front normal (nT) ',
   'units': 'nT',
   'type': 'double',
   'fill': '99.99'},
  {'name': 'Time_btwn_obs',
   'description': 'Time between observations (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'F',
   'description': 'Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BX_GSE',
   'description': 'Bx (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BY_GSE',
   'description': 'By (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BZ_GSE',
   'description': 'Bz (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BY_GSM',
   'description': 'By (nT), GSM, determined from post-shift GSE components',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BZ_GSM',
   'description': 'Bz (nT), GSM, determined from post-shift GSE components',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'RMS_SD_B',
   'description': 'RMS SD B scalar (nT)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'RMS_SD_fld_vec',
   'description': 'RMS SD field vector (nT)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'flow_speed',
   'description': 'Flow Speed (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vx',
   'description': 'Vx Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vy',
   'description': 'Vy Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vz',
   'description': 'Vz Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'proton_density',
   'description': 'Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)',
   'units': 'n/cc',
   'type': 'double',
   'fill': '999.99'},
  {'name': 'T',
   'description': 'Temperature (K)',
   'units': 'K',
   'type': 'double',
   'fill': '9999999.0'},
  {'name': 'NaNp_Ratio',
   'description': 'Alpha/Proton Density Ratio',
   'units': ' ',
   'type': 'double',
   'fill': '9.999'},
  {'name': 'Pressure',
   'description': 'Flow pressure (nPa)',
   'units': 'nPa',
   'type': 'double',
   'fill': '99.99'},
  {'name': 'E',
   'description': 'Electric Field (mV/m)',
   'units': 'mV/m',
   'type': 'double',
   'fill': '999.99'},
  {'name': 'Beta',
   'description': 'Plasma beta',
   'units': None,
   'type': 'double',
   'fill': '999.99'},
  {'name': 'Mach_num',
   'description': 'Alfven mach number',
   'units': None,
   'type': 'double',
   'fill': '999.9'},
  {'name': 'Mgs_mach_num',
   'description': '1AU IP Magnetosonic mach number',
   'units': None,
   'type': 'double',
   'fill': '99.9'},
  {'name': 'x',
   'description': 'X s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'y',
   'description': 'Y s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'z',
   'description': 'Z s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_x',
   'description': 'Bow Shock Nose (Re) location, X, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_y',
   'description': 'Bow Shock Nose (Re) location, Y, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_z',
   'description': 'Bow Shock Nose (Re) location, Z, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'AE_INDEX',
   'description': 'AE - 1-minute AE-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'AL_INDEX',
   'description': 'AL - 1-minute AL-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'AU_INDEX',
   'description': 'AU - 1-minute AU-index,from WDC Kyoto  (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'SYM_D',
   'description': 'SYM/D - 1-minute SYM/D index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'SYM_H',
   'description': 'SYM/H - 1-minute SYM/H index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'ASY_D',
   'description': 'ASY/D - 1-minute ASY/D index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'ASY_H',
   'description': 'ASY/H - 1-minute ASY/H index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'}],
 'startDate': '1995-01-01T00:00:00Z',
 'stopDate': '2026-04-13T01:15:00Z',
 'status': {'code': 1200, 'message': 'OK'}}

In [100]:
fetch_hapi_info_test['startDate']

'1995-01-01T00:00:00Z'

In [101]:
fetch_hapi_info_test['stopDate']

'2026-04-13T01:15:00Z'